### ISSUE TITLE
Entities without @id not working anymore in data 2.4.X

### ISSUE THREAD

**Issue by bzolivereckle** [micronaut-projects/micronaut-data#1001]
After updating Micronaut Data dependencies to 2.4.1 jdbc queries for entities without id do not work anymore.
We are using timescale db as a postgresql extension. Up to 2.3.1 having entities without an id works pretty fine.
After upgrading to 2.4.1 we got into trouble, cause he throws an exception on not finding an id - which is intended from our side.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Update to Micronaut Data 2.4.1
2. Implement GenericRepository with JDBC-annotation
3. Having some entity with only colums like name, value, timestamp
3. Find data by a specific column like name

### Expected Behaviour

JDBC repository should return data after querying by name.

### Actual Behaviour

JDBC repository fails to retrieve data and throws an error.

```
SQL Error executing Query: Entity doesn't have an id!
io.micronaut.data.exceptions.DataAccessException: SQL Error executing Query: Entity doesn't have an id!
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:555)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$10(DefaultJdbcRepositoryOperations.java:579)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:577)
	at io.micronaut.data.runtime.intercept.DefaultFindPageInterceptor.intercept(DefaultFindPageInterceptor.java:56)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.4.2
- **JDK Version:** AdoptOpenJDK 11.0.11

**Comment by dstepanov** [comment]
I have a fix, but the operations you can do are limited.
https://github.com/micronaut-projects/micronaut-data/pull/1005/files#diff-59b9a8f685a70fa77a20d5a3ec3b001959a4a7497fecd0b3d6be4abf43d94cdd
