### ISSUE TITLE
R2DBC crash after update 2.4.4 -> 2.5.0 

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [micronaut-projects/micronaut-data#1006]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Update Micronaut 2.4.4 -> 2.5.0
2. Have r2dbc some r2dbc setup

### Expected Behaviour

The application starts up and communicates with DB

### Actual Behaviour

```
19:09:45.819 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator] could not be loaded: Error instantiating bean of type  [io.micronaut.data.r2dbc.config.DataR2dbcConfiguration]

Message: Missing bean argument value: r2dbcOperations
Path Taken: new R2dbcSchemaGenerator([List configurations]) --> new DataR2dbcConfiguration(String name,ConnectionFactory connectionFactory,[R2dbcOperations r2dbcOperations])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator] could not be loaded: Error instantiating bean of type  [io.micronaut.data.r2dbc.config.DataR2dbcConfiguration]

Message: Missing bean argument value: r2dbcOperations
Path Taken: new R2dbcSchemaGenerator([List configurations]) --> new DataR2dbcConfiguration(String name,ConnectionFactory connectionFactory,[R2dbcOperations r2dbcOperations])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1565)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:216)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2864)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:162)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
```

### Environment Information

- **Operating System**: NixOS
- **Micronaut Version:** 2.5.0
- **JDK Version:** 11

**Comment by dstepanov** [comment]
We moved the data r2dbc project to this repository, the group has to have suffix ’data‘

**Comment by graemerocher** [comment]
See https://micronaut.io/launch/?javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&name=demo&package=com.example&type=DEFAULT&features=data-r2dbc&version=2.5.1&activity=preview&showing=/build.gradle for the correct group id to use
