### ISSUE TITLE
org.hibernate.HibernateException: No CurrentSessionContext configured in GraalVM with JPA and H2

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#1007]
Tonight GraalVM CI failed for the Micronaut Data JPA with H2 application and the latest snapshot (2.4.3). This only happens when using Micronaut 2.5.x but it works with Micronaut 3.0.x.
It fails when running as a native-image but running the app in the JVM makes it work.

This worked yesterday with the latest Micronaut Data 2.4.2-SNAPSHOT. I've also tried with 2.4.2 version and everything works so the error is probably in 2.4.3-SNAPSHOT. Or maybe it's something changed in Micronaut 2.5.x what makes this fail and those changes hasn't been merged yet into 3.0.x.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal`
- `cd micronaut-data-jpa-graal`
- `git checkout no-current-session-context-error`
- `sdk use java 21.1.0.r8-grl`
- `./build-native-image.sh`
- `./data-jpa-h2`

### Expected Behaviour

The application should start properly.

### Actual Behaviour

The application fails to start:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.1-SNAPSHOT)

12:04:04.957 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
12:04:04.959 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
12:04:04.960 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version [WORKING]
12:04:04.960 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
12:04:04.961 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Hibernate: create table owner (id bigint not null, age integer not null, name varchar(255), primary key (id))
Hibernate: create table pet (id binary not null, name varchar(255), type integer, owner_id bigint, primary key (id))
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
Hibernate: alter table pet add constraint FK7qfti9yba86tgfe9oobeqxfxg foreign key (owner_id) references owner
12:04:04.971 [main] ERROR o.h.internal.SessionFactoryImpl - HHH000302: Unable to construct current session context [io.micronaut.transaction.hibernate5.MicronautSessionContext]
org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [io.micronaut.transaction.hibernate5.MicronautSessionContext]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:133)
	at org.hibernate.internal.SessionFactoryImpl.buildCurrentSessionContext(SessionFactoryImpl.java:1017)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:323)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactory(EntityManagerFactoryBean.java:219)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:153)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1941)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2731)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2717)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2256)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1559)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:216)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2864)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:162)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at example.Application.main(Application.java:30)
Caused by: java.lang.ClassNotFoundException: io.micronaut.transaction.hibernate5.MicronautSessionContext
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
	at java.lang.Class.forName(DynamicHub.java:1308)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)
	... 19 common frames omitted
12:04:04.973 [main] INFO  example.Application - Populating data
12:04:04.974 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No CurrentSessionContext configured!
org.hibernate.HibernateException: No CurrentSessionContext configured!
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:477)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$persistAll$9(HibernateJpaOperations.java:462)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.persistAll(HibernateJpaOperations.java:460)
	at io.micronaut.data.runtime.intercept.DefaultSaveAllInterceptor.intercept(DefaultSaveAllInterceptor.java:47)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at example.repositories.OwnerRepository$Intercepted.saveAll(Unknown Source)
	at example.Application.init(Application.java:45)
	at example.$ApplicationDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3371)
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at example.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1323)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1308)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:246)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:162)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at example.Application.main(Application.java:30)

```

### More information

It seems the error is because the class `io.micronaut.transaction.hibernate5.MicronautSessionContext` is not included in the native-image but it should be because of this change made more than two years ago: https://github.com/micronaut-projects/micronaut-data/blob/4018d15d3512de3622f12178bcb05d03d8000714/data-tx-hibernate/src/main/java/io/micronaut/transaction/hibernate5/MicronautSessionContext.java#L41 

```
Caused by: java.lang.ClassNotFoundException: io.micronaut.transaction.hibernate5.MicronautSessionContext
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.5.1-SNAPSHOT and Micronaut Data 2.4.3-SNAPSHOT
- **JDK Version:** 8 & 11

**Comment by dstepanov** [comment]
Can it be related to Gradle 7? @graemerocher

**Comment by graemerocher** [comment]
hmmm, let me check

**Comment by graemerocher** [comment]
I unzipped https://search.maven.org/artifact/io.micronaut.data/micronaut-data-tx-hibernate/2.4.2/jar and it contains

```json
cat META-INF/native-image/io.micronaut.data/data-tx-hibernate/reflect-config.json
[ {
  "name" : "io.micronaut.transaction.hibernate5.MicronautSessionContext",
  "allDeclaredConstructors" : true
}, {
  "name" : "io.micronaut.transaction.hibernate5.HibernateTransactionManager",
  "allDeclaredConstructors" : true
} ]%
```

So doesn't seem to be that

**Comment by graemerocher** [comment]
Weirdly the current published snapshot does not in fact contain this file which is worrying

**Comment by graemerocher** [comment]
So the raw logs for the release:

https://pipelines.actions.githubusercontent.com/wpuQyMdalV0P1UIYEk04BEmdkP6hjNR26m7wvD1YWNSK6mUTF5/_apis/pipelines/1/runs/3153/signedlogcontent/3?urlExpires=2021-05-05T12%3A09%3A00.9975890Z&urlSigningMethod=HMACV1&urlSignature=Qpv5QXgqBs3l%2ByrVlT9XZGpypKy7L7dZEv2xy4K46YU%3D

Contain

```
Note: Writing reflect-config.json file to destination: META-INF/native-image/io.micronaut.data/data-tx-hibernate/reflect-config.json
```

However the raw logs for the snapshot:

https://pipelines.actions.githubusercontent.com/wpuQyMdalV0P1UIYEk04BEmdkP6hjNR26m7wvD1YWNSK6mUTF5/_apis/pipelines/1/runs/3154/signedlogcontent/5?urlExpires=2021-05-05T12%3A09%3A56.6141258Z&urlSigningMethod=HMACV1&urlSignature=Gg2hNnRo%2Fw4jkg%2Bh3eVcbEziIXqP2VByMLkYGj3fxfo%3D

Do not contain this line although other native image JSON files were written out 🤔

**Comment by ilopmar** [comment]
The last snapshot https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/data/micronaut-data-tx-hibernate/2.4.3-SNAPSHOT/micronaut-data-tx-hibernate-2.4.3-20210504.123211-1.jar contains the right `reflect-config.json` file, but for some reason it doesn't work.

**Comment by graemerocher** [comment]
🤷‍♂️

**Comment by dstepanov** [comment]
Maybe you have cached the old snapshot?

**Comment by ilopmar** [comment]
That happened on CI and there is no cache there. In any case I've tried again removing all my 2.4.3 and 2.5.1 snapshots and the error happens again locally.

It is definitely something with Micronaut Data 2.4.3-SNAPSHOT because I've seen that my 3.0.x app was using and old version and it worked. I'm updating to use the new snapshot and it will probably fail during tonight execution.

**Comment by ilopmar** [comment]
I run the workflow to publish a new snapshot yesterday and tonight everything is working again... I'll close this and reopen if it happens again.

**Comment by dstepanov** [comment]
@ilopmar Is it still happening?

**Comment by ilopmar** [comment]
Yes, actually this happened this morning with Micronaut 2.5.x app and latest micronaut-data snapshot: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1446175608

**Comment by dstepanov** [comment]
Can you please try to remove `MVCC=TRUE;` in properties?

**Comment by ilopmar** [comment]
I already did that 9 days ago https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/commit/a63e72d82c65a701feac24ea68c05a8949e5bb7d :-)

**Comment by radovanradic** [comment]
This appears to be fixed in Micronaut4, please try it there.
Here is attached example that I was able to test (copied classes from your sample app and adjusted): 
[mn-jpa-h2-graalvm.zip](https://github.com/micronaut-projects/micronaut-data/files/12573736/mn-jpa-h2-graalvm.zip)

One thing worth noting is that this config value needs to be set in order for native apps work with hibernate `jpa.default.compile-time-hibernate-proxies=true`, as documented here https://micronaut-projects.github.io/micronaut-sql/latest/guide/#hibernate-proxies
