### ISSUE TITLE
Micronaut Data JDBC generate "After end of result set" in certain scenarios

### ISSUE THREAD

**Issue by crejo-ishwar** [micronaut-projects/micronaut-data#1016]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create three entities with the following association
2. Entity1 -one-to-one-> Entity2 -one-to-many-> Entity3
3. Try fetching all Entity1 from db, joined with Entity2 and Entity3, you get "After end of result set" exception

### Expected Behaviour

All Entity1 should get loaded from db along with associated Entity2 and Entity3

### Actual Behaviour

You get "After end of result set" exception

18:34:29.668 [io-executor-thread-1] ERROR io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: Error reading object for name [created_at] from result set: After end of result set
io.micronaut.data.exceptions.DataAccessException: Error reading object for name [created_at] from result set: After end of result set
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.exceptionForColumn(ColumnNameResultSetReader.java:224) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readTimestamp(ColumnNameResultSetReader.java:84) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readTimestamp(ColumnNameResultSetReader.java:37) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.runtime.mapper.ResultReader.readDynamic(ResultReader.java:117) ~[micronaut-data-runtime-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readDynamic(ColumnNameResultSetReader.java:43) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readDynamic(ColumnNameResultSetReader.java:37) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:443) ~[micronaut-data-runtime-2.2.4.jar:2.2.4]
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:159) ~[micronaut-data-runtime-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$2.tryAdvance(DefaultJdbcRepositoryOperations.java:328) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$5(DefaultJdbcRepositoryOperations.java:393) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155) ~[micronaut-data-tx-2.2.4.jar:2.2.4]
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:391) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:52) ~[micronaut-data-runtime-2.2.4.jar:2.2.4]
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:36) ~[micronaut-data-runtime-2.2.4.jar:2.2.4]
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80) ~[micronaut-data-model-2.2.4.jar:2.2.4]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.validateReturnExecutableValidator(ValidatingInterceptor.java:152) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:100) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at fun.crejo.classroom.adapter.persistence.repository.BatchRepository$Intercepted.findBatches(Unknown Source) ~[main/:?]
	at fun.crejo.classroom.adapter.persistence.SQLPersistenceAdapter.findAllWithSessions(SQLPersistenceAdapter.java:117) ~[main/:?]
	at fun.crejo.classroom.domain.usecase.GetPromiseUseCase.getBatches(GetPromiseUseCase.java:68) ~[main/:?]
	at fun.crejo.classroom.domain.usecase.GetPromiseUseCase.getPromise(GetPromiseUseCase.java:41) ~[main/:?]
	at fun.crejo.classroom.domain.usecase.$GetPromiseUseCaseDefinition$Intercepted.$$access$$getPromise(Unknown Source) ~[main/:?]
	at fun.crejo.classroom.domain.usecase.$GetPromiseUseCaseDefinition$$exec1.invokeInternal(Unknown Source) ~[main/:?]
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146) ~[micronaut-inject-2.3.1.jar:2.3.1]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:87) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.validateReturnExecutableValidator(ValidatingInterceptor.java:152) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:100) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at fun.crejo.classroom.domain.usecase.$GetPromiseUseCaseDefinition$Intercepted.getPromise(Unknown Source) ~[main/:?]
	at fun.crejo.classroom.adapter.web.booking.BookingController.getTrialPromise(BookingController.java:64) ~[main/:?]
	at fun.crejo.classroom.adapter.web.booking.$BookingControllerDefinition$Intercepted.$$access$$getTrialPromise(Unknown Source) ~[main/:?]
	at fun.crejo.classroom.adapter.web.booking.$BookingControllerDefinition$$exec1.invokeInternal(Unknown Source) ~[main/:?]
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146) ~[micronaut-inject-2.3.1.jar:2.3.1]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:87) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.validateReturnExecutableValidator(ValidatingInterceptor.java:152) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:100) ~[micronaut-validation-2.3.1.jar:2.3.1]
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96) ~[micronaut-aop-2.3.1.jar:2.3.1]
	at fun.crejo.classroom.adapter.web.booking.$BookingControllerDefinition$Intercepted.getTrialPromise(Unknown Source) ~[main/:?]
	at fun.crejo.classroom.adapter.web.booking.$BookingControllerDefinition$$exec1.invokeInternal(Unknown Source) ~[main/:?]
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146) ~[micronaut-inject-2.3.1.jar:2.3.1]
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474) ~[micronaut-inject-2.3.1.jar:2.3.1]
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312) ~[micronaut-router-2.3.1.jar:2.3.1]
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118) ~[micronaut-router-2.3.1.jar:2.3.1]
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1394) ~[micronaut-http-server-netty-2.3.1.jar:2.3.1]
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.Flowable.subscribe(Flowable.java:14882) ~[rxjava-2.2.20.jar:?]
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57) ~[micronaut-runtime-2.3.1.jar:2.3.1]
	at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.Flowable.subscribe(Flowable.java:14882) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288) ~[rxjava-2.2.20.jar:?]
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253) ~[rxjava-2.2.20.jar:?]
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47) ~[micronaut-runtime-2.3.1.jar:2.3.1]
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157) ~[micrometer-core-1.6.3.jar:1.6.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLException: After end of result set
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:492) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:912) ~[mysql-connector-java-8.0.22.jar:8.0.22]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:959) ~[mysql-connector-java-8.0.22.jar:8.0.22]
Caused by: java.sql.SQLException: After end of result set

	at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java) ~[HikariCP-3.4.5.jar:?]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readTimestamp(ColumnNameResultSetReader.java:82) ~[micronaut-data-jdbc-2.2.4.jar:2.2.4]
	... 65 more

### Environment Information

- **Operating System**: MacOS Big Sur 11.2.3
- **Micronaut Version:** 2.3.1 
- **JDK Version:** openjdk 11.0.10 2021-01-19 LTS

### Example Application

@Data
@MappedSuperclass
public class BaseEntity {
    @Id
    @GeneratedValue
    private Long id;
    @DateCreated
    private Timestamp createdAt;
    @DateUpdated
    private Timestamp updatedAt;
}

@Data
@EqualsAndHashCode(callSuper = true)
@MappedEntity("batch")
public class BatchEntity extends BaseEntity {
    @NotNull
    private Long courseId;
    @NotNull
    private Long instructorId;
    @NotNull
    private BatchType type;
    @NotNull
    private BatchStatus status;
    @OneToOne(mappedBy = "batch")
    private BatchSizeEntity size;
    @OneToMany(mappedBy = "batch")
    private Set<SessionEntity> sessions;
    @OneToOne(mappedBy = "batch")
    private BatchScheduleEntity schedule;
    @OneToOne(mappedBy = "batch")
    private BatchPriceEntity price;
}

@Data
@EqualsAndHashCode(callSuper = true)
@MappedEntity("batch_schedule")
public class BatchScheduleEntity extends BaseEntity {
    @OneToOne
    @JoinColumn(name = "batch_id", nullable = false)
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    private BatchEntity batch;
    @NotNull
    private LocalDate startDate;
    @NotNull
    private LocalDate endDate;
    @OneToMany(mappedBy = "batchSchedule")
    private Set<BatchPlanEntity> plan;
}

@Data
@EqualsAndHashCode(callSuper = true)
@MappedEntity("batch_plan")
public class BatchPlanEntity extends BaseEntity {
    @ManyToOne
    @JoinColumn(name = "batch_schedule_id", nullable = false)
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    private BatchScheduleEntity batchSchedule;
    @NotNull
    private DayOfWeek day;
    @NotNull
    private LocalTime startTime;
    @NotNull
    private LocalTime endTime;
    @NotNull
    private Integer dayOrder;
}

@Query("SELECT " +
           "  b_.id, b_.course_id, b_.instructor_id, b_.type, b_.status, b_.created_at, b_.updated_at, " +
           "  bs_.id AS bs_id, bs_.batch_id AS bs_batch_id, bs_.start_date AS bs_start_date, bs_.end_date AS bs_end_date, bs_.created_at AS bs_created_at, bs_.updated_at AS bs_updated_at, " +
           "  bp_.id AS bp_id, bp_.batch_schedule_id AS bp_batch_schedule_id, bp_.day AS bp_day, bp_.start_time AS bp_start_time, bp_.end_time AS bp_end_time, bp_.created_at AS bp_created_at, bp_.updated_at AS bp_updated_at, bp_.day_order AS bp_day_order " +
           "FROM " +
           "  batch b_ LEFT JOIN" +
           "  batch_schedule bs_ ON b_.id = bs_.batch_id LEFT JOIN " +
           "  batch_plan bp_ ON bs_.id = bp_.batch_schedule_id " +
           "WHERE b_.id <= :batchId")
    @Join(value = "schedule", alias = "bs_")
    @Join(value = "schedule.plan", alias = "bp_")
    public abstract Iterable<BatchEntity> findBatches(Long batchId);

**Comment by dstepanov** [comment]
Can you check if it occurs in the latest version?

**Comment by dstepanov** [comment]
In the latest version joining should work correctly so you don't need a custom query.

**Comment by crejo-ishwar** [comment]
Hey dstepanov... Thanks you so much for such a quick response... I updated my micronaut version from 2.3.1 to 2.5.1 and the issue is resolved... I was really struggling with this issue from past two days...

Also, I am writing custom query because I have fetch Entity1 (BatchEntity) based on some condition on Entity3 (BatchPlanEntity), which can't be done by writing simple query methods where condition can only be applied to the root entity...

**Comment by dstepanov** [comment]
Great!
Looking at the query you posted this might work:
```
@Where("@.id <= :batchId")
@Join(value = "schedule", alias = "bs_")
@Join(value = "schedule.plan", alias = "bp_")
public abstract Iterable findBatches(Long batchId);
```
