### ISSUE TITLE
r2dbc @Transactional  causes Connection pool request timeout

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-data#1019]
### Environment Information
- **Operating System**: window
- **Micronaut Version:** 2.5.3
- **JDK Version:** jdk8
- **MYSQL Version** mysql8

Interface with transaction annotation, stress test causes connection pool request timeout, after closing pressure test for a few minutes, single request interface still prompts connection pool request timeout, which may be caused by connection pool leakage. There is no error because the transaction annotation is cancelled.

### Example 
````
@Get("/")
Flux<Book> all() {
  return bookService.findAll(); // With transaction;pool request timeout
  //return bookRepository.findAll(); // without,it's ok
}

````
1.  ab -n 5000 -c 300 http://127.0.0.1:8080/books
2.  curl http://127.0.0.1:8080/books
    curl: (18) transfer closed with outstanding read data remaining

***logs***

14:02:16.486 [default-nioEventLoopGroup-1-8] DEBUG i.m.d.r.o.DefaultR2dbcRepositoryOperations - Creating a new Connection for DataSource: default
14:02:28.504 [parallel-4] ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: Connection Acquisition timed out after 6000ms
io.r2dbc.spi.R2dbcTimeoutException: Connection Acquisition timed out after 6000ms
	at io.r2dbc.pool.ConnectionPool.lambda$null$6(ConnectionPool.java:123)
	at reactor.core.publisher.Mono.lambda$onErrorMap$29(Mono.java:3370)
	at reactor.core.publisher.Mono.lambda$onErrorResume$31(Mono.java:3460)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:294)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:279)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:418)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:119)
	at io.micronaut.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 6000ms in 'Connection Acquisition from [dev.miku.r2dbc.mysql.MySqlConnectionFactory@3e4fddc3]' (and no fallback has been configured)
	... 13 common frames omitted

**Comment by chenjpu** [comment]
MBean monitor
![image](https://user-images.githubusercontent.com/1785778/118229640-edb85a80-b4be-11eb-8e39-b12f0c68ada6.png)

**Comment by dstepanov** [comment]
Can you provide a sample app with your configuration?

**Comment by chenjpu** [comment]
@debuglevel 
https://github.com/chenjpu/mn-demo

**Comment by chenjpu** [comment]
I tested the latest version of 2.4.4-snapshot and found the problem was still not solved.

**Comment by chenjpu** [comment]
@dstepanov

I tested the latest version of 2.4.4 and found the problem was still not solved.

**Comment by dstepanov** [comment]
@chenjpu I will look at it probably next week

**Comment by dstepanov** [comment]
You need to use a connection pool otherwise you are using a connection per request.
```
r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol:
          postgres
      url: r2dbc:postgres://localhost:5432/micronaut
      username: micronaut
      password: micronaut
      schema-generate: CREATE_DROP
      dialect: postgres
```

and add the pool dependency:

```
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-pool</artifactId>
      <scope>runtime</scope>
    </dependency>
```

This runs without errors for me.

**Comment by chenjpu** [comment]
In the [demo](https://github.com/chenjpu/mn-demo) project I checked the dependencies and the configuration

[dependency](https://github.com/chenjpu/mn-demo/blob/main/build.gradle#L41)

runtimeOnly("io.r2dbc:r2dbc-pool")

[connection pool](https://github.com/chenjpu/mn-demo/blob/main/src/main/resources/application.yml#L15)

r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://localhost:3306/db
      username: root
      password: '123'
      #schema-generate: CREATE_DROP
      dialect: MYSQL
      options:
        driver: pool
        protocol: mysql
        maxSize: 20
        initialSize: 5
        maxLifeTime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: r2dbc
        registerJmx: true


This runs  still errors for me.

@dstepanov  Can I share your test project, and I will check it locally .

**Comment by graemerocher** [comment]
@dstepanov we need to document this

**Comment by dstepanov** [comment]
Sorry, I actually meant to close another similar issue

**Comment by chenjpu** [comment]
Thanks so much, the problem was thoroughly solved.

**Comment by dstepanov** [comment]
@chenjpu Did you try the snapshot?

**Comment by chenjpu** [comment]
@dstepanov Yes, I'll validate the release again today

**Comment by chenjpu** [comment]
Version 2.4.7 was verified and the problem was resolved.
