### ISSUE TITLE
Hibernate native image start fails due to entities with enums

### ISSUE THREAD

**Issue by Phil-Ba** [micronaut-projects/micronaut-data#1046]
This issue relates to https://github.com/micronaut-projects/micronaut-data/issues/873 .
Quarkus seems to have had the same problem and solved it: https://github.com/quarkusio/quarkus/issues/7653

### Task List

- [x ] Steps to reproduce provided
- [x ] Stacktrace (if present) provided
- [x ] Example that reproduces the problem uploaded to Github
- [x ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Have an entity with an enum field.
2. Build native image.
3. Start application.

### Expected Behaviour

Application should start.

### Actual Behaviour

Application crashes with:
Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType 

### Environment Information

- **Operating System**: Manjaro
- **Micronaut Version:** 2.5.5
- **JDK Version:** 11

### Example Application

https://github.com/Phil-Ba/enumtest
* Build native docker image by executing dockerNativeBuild gradle task.
* Start application with provided docker-compose-native.yaml
* There is a workaround which makes the application start, by uncommenting line 73 in the build.gradle.kts

### Stacktrace
20:59:23.539 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1568)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2907)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at at.bayava.ApplicationKt.main(Application.kt:11)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2008)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2294)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1562)
	... 6 common frames omitted
Caused by: org.hibernate.MappingException: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
	at org.hibernate.mapping.SimpleValue.createParameterImpl(SimpleValue.java:779)
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:481)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:466)
	at org.hibernate.mapping.Property.isValid(Property.java:227)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:624)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:354)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:465)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactory(EntityManagerFactoryBean.java:219)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:153)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	... 10 common frames omitted
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [at.bayava.entity.TestEnum]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:133)
	at org.hibernate.mapping.SimpleValue.createParameterImpl(SimpleValue.java:766)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: at.bayava.entity.TestEnum
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
	at java.lang.Class.forName(DynamicHub.java:1308)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)
	... 22 common frames omitted

**Comment by dstepanov** [comment]
The only way to make it work is to annotate the enum with `@ReflectiveAccess`. Unfortunately, there is nothing much we can do to have it automatically.
