### ISSUE TITLE
Support join table inheritance in JDBC

### ISSUE THREAD

**Issue by bruno-lopes** [micronaut-projects/micronaut-data#105]
**Micronaut Version:** 1.2.0
**Micronaut Data Version:** 1.0.0-BUILD-SNAPSHOT
**Postgres Version:** 9.5

I'm trying to use Micronaut Data JDBC, but I'm having trouble with inheritance.

I have two classes: Student and RegularStudent as following:

```java
@Entity
@Data
@Table(name = "student", schema = "student")
//@Inheritance(strategy = InheritanceType.JOINED)
@Introspected
public class Student {

    @Id
    @GeneratedValue
    @Column(name = "student_id")
    Long id;

    @NotNull
    @Column(nullable = false, name = "active")
    private Boolean active;

}
```
and:
```java
@Entity
@Data
@Table(name = "regular_student", schema = "student")
@Introspected
public class RegularStudent extends Student {
    @Temporal(TemporalType.DATE)
    @Column(name = "entrance_date")
    private
    Date entranceDate;
```
}

And the following:

```java
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface RegularStudentRepository extends CrudRepository<RegularStudent, Long> {

}
```

When I try to persist a regular student object:

```java
regularStudentRepository.save(newRegularStudent);
```

I get the following error:
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "active" of relation "regular_student" does not exist
  Position: 467
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persist$8(DefaultJdbcRepositoryOperations.java:411)
```

It occurs because I have two tables in database:

Student -> fields (student_id and active)

Regular Student ->  student_id and entrance_date

Is/Will it possible to map this situation in Micronaut and use the JDBC Repository default methods?

**Comment by graemerocher** [comment]
This would require a join on the tables, we will consider it. Thanks for the feedback.

**Comment by bruno-lopes** [comment]
I tried to create an abstract class (parent class), and create a table per entity (child class). But Micronaut does not map attributes of the parent class. Is there a way to do this?

**Comment by dstepanov** [comment]
Triage: still reproducible today. Mapping a JPA-style `@Inheritance(strategy = InheritanceType.JOINED)` hierarchy across multiple tables is only supported through the Hibernate/JPA module (since Hibernate itself handles it); the native `micronaut-data-jdbc` module has no equivalent — there's no inheritance-aware table mapping in the JDBC query builder/persistence layer. The `AuditedVehicle`/`Payment` JOINED/SINGLE_TABLE test entities in `data-tck` are only exercised by the JPA metamodel processor, not by actual JDBC repository persistence.

As noted in the thread, table-per-concrete-class (a separate `@MappedEntity` per table, no shared supertype mapping) remains the only workaround for JDBC. Keeping this open as a valid enhancement.
