### ISSUE TITLE
Error with one-to-many findById with embeddedId and empty left join fetch

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-data#1050]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. findById on entities with one-to-many mapping and EmbeddedId
or
1. Run test `"test empty one-to-many via embedded-id"`
```
    void "test empty one-to-many via embedded-id"() {
        when:
        ItemGroup itemGroup = new ItemGroup(1L)
        itemGroup.setSecondId(2L)
        groupRepository.save(itemGroup)
        ItemGroup entity = groupRepository.findById(1L).get()

        then:
        entity.getItems().size() == 0
    }
```

### Expected Behaviour

Should lookup entity and have `items` with 0 elements, seems like the EmbeddedId mapping doesn't like null values, still tries to construct the embedded object and fails because non-null constraints/constructors etc. It should just ignore null values and return as empty set?

### Actual Behaviour

A few different failures depending on the exact entities, one in the test is:
```
  io.micronaut.data.exceptions.DataAccessException: Null value read for non-null constructor argument [firstId] of type: io.micronaut.data.jdbc.h2.ItemGroupId
      at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:433)
      at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntityId(SqlResultEntityTypeMapper.java:557)
      at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:507)
      at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.access$300(SqlResultEntityTypeMapper.java:69)
      at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper$1.processRow(SqlResultEntityTypeMapper.java:238)
      at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$3(DefaultJdbcRepositoryOperations.java:370)
      at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
      at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:345)
      at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
      at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
      at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
      at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
      at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
      at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
      at io.micronaut.data.jdbc.h2.H2EmbeddedIdSpec.test empty one-to-many via embedded-id(H2EmbeddedIdSpec.groovy:48)
```

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.4.4
- **JDK Version:** 14

### Example Application

https://github.com/nhoughto/micronaut-data/tree/embeddedid-join-emptylist

**Comment by dstepanov** [comment]
Looks like there needs to be a check in ‘readEntity’ for the cases when the entity is an embedded id.

**Comment by dstepanov** [comment]
You can check from the mapping context if the association is present and is a embedded and also id, that should be enough to skip the exception and return null for readEntity.

**Comment by nhoughto** [comment]
https://github.com/micronaut-projects/micronaut-data/pull/1051

**Comment by nhoughto** [comment]
merged ,ta.
