### ISSUE TITLE
micronaut-data-jdbc returning ill-behaved `java.util.stream.Stream` 

### ISSUE THREAD

**Issue by wbprime** [micronaut-projects/micronaut-data#1068]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Setup micronaut-data-jdbc project
2. Create a `DUser` entity class
3. Create `UserRepository` extends `io.micronaut.data.repository`
4. Add an interface method `Stream<DUser> findByBirthdayNotAfter(final OffsetDateTime date);`
5. Get instance of micronaut managed `UserRepository` and invoke `findByBirthdayNotAfter` method
6. Invoke `forEach` on returned `Stream` instance

### Expected Behaviour

Each items should be feed into `forEach` method without unexpected errors.

### Actual Behaviour

Just throwing:

```
Exception in thread "main" io.micronaut.data.exceptions.DataAccessException: Error calling next on SQL result set: The object is already closed [90007-199]
        at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.next(ColumnNameResultSetReader.java:57)
        at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.next(ColumnNameResultSetReader.java:37)
        at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.hasNext(SqlResultEntityTypeMapper.java:213)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$1.tryAdvance(DefaultJdbcRepositoryOperations.java:502)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at im.wangbo.java.micronaut.Application.main(Application.java:36)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.message.DbException.get(DbException.java:170)
        at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3242)
        at org.h2.jdbc.JdbcResultSet.next(JdbcResultSet.java:132)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
        at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.next(ColumnNameResultSetReader.java:55)
        ... 6 more
```

### Environment Information

- **Operating System**: Archlinux x64 5.12.13-arch1-2
- **Micronaut Version:** 2.5.7
- **Micronaut Data Version**: 2.4.4
- **JDK Version:** OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)

### Example Application

- https://github.com/wbprime/micronaut-data-jdbc-issue-for-stream

**Comment by dstepanov** [comment]
`Stream` methods need to have a transaction present, I have corrected the use-case in the PR
