### ISSUE TITLE
Automatic ID values not generated/retrieved with latest snapshots

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#1088]
GraalVM CI has detected an issue with JDBC and JPA applications. I've reproduced it locally and it also  happens in JIT mode.

This is something introduced in the latest snapshots (not sure if in core or data) during last night because this was working yesterday.

It seems that the automatic ids values are not being generated or retrieved because when using them as a FK there is an error saying they are null.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout error-null-pk`
- `./gradlew run`

### Expected Behaviour

The application should start and load the initial data to the database.

### Actual Behaviour

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.0-SNAPSHOT)

11:47:46.095 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
11:47:46.216 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
11:47:46.230 [main] DEBUG io.micronaut.data.query - Dropping Table: 
DROP TABLE `owner`
11:47:46.236 [main] DEBUG io.micronaut.data.query - Dropping Table: 
DROP TABLE `pet`
11:47:46.239 [main] DEBUG io.micronaut.data.query - Executing CREATE statement: 
CREATE TABLE `owner` (`id` BIGINT AUTO_INCREMENT PRIMARY KEY,`age` INT NOT NULL,`name` VARCHAR(255) NOT NULL);
11:47:46.244 [main] DEBUG io.micronaut.data.query - Executing CREATE statement: 
CREATE TABLE `pet` (`id` UUID,`owner_id` BIGINT NOT NULL,`name` VARCHAR(255) NOT NULL,`type` VARCHAR(255) NOT NULL);
11:47:46.345 [main] INFO  example.Application - Populating data
11:47:46.551 [main] DEBUG io.micronaut.data.query - Executing Batch SQL Update: UPDATE `owner` SET `age`=?,`name`=? WHERE (`id` = ?)
11:47:46.568 [main] DEBUG io.micronaut.data.query - Executing Batch SQL Insert: INSERT INTO `pet` (`owner_id`,`name`,`type`,`id`) VALUES (?,?,?,?)
11:47:46.571 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: SQL error executing INSERT: NULL not allowed for column "OWNER_ID"; SQL statement:
INSERT INTO `pet` (`owner_id`,`name`,`type`,`id`) VALUES (?,?,?,?) [23502-200]
io.micronaut.data.exceptions.DataAccessException: SQL error executing INSERT: NULL not allowed for column "OWNER_ID"; SQL statement:
INSERT INTO `pet` (`owner_id`,`name`,`type`,`id`) VALUES (?,?,?,?) [23502-200]
        at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.persistInBatch(AbstractSqlRepositoryOperations.java:618)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persistAll$19(DefaultJdbcRepositoryOperations.java:751)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persistAll(DefaultJdbcRepositoryOperations.java:727)
        at io.micronaut.data.runtime.intercept.DefaultSaveAllInterceptor.intercept(DefaultSaveAllInterceptor.java:47)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at example.repositories.PetRepository$Intercepted.saveAll(Unknown Source)
        at example.Application.init(Application.java:50)
        at example.$Application$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3960)
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:83)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at example.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1669)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1654)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:259)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at example.Application.main(Application.java:30)
Caused by: org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "OWNER_ID"; SQL statement:
INSERT INTO `pet` (`owner_id`,`name`,`type`,`id`) VALUES (?,?,?,?) [23502-200]
        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1235)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntitiesOperations.executeUpdate(DefaultJdbcRepositoryOperations.java:1126)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntitiesOperations.executeUpdate(DefaultJdbcRepositoryOperations.java:1015)
        at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.lambda$persistInBatch$2(AbstractSqlRepositoryOperations.java:612)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:312)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:116)
        at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.persistInBatch(AbstractSqlRepositoryOperations.java:604)
        ... 24 common frames omitted
```

The JPA test applications also fail with a similar error:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.0-SNAPSHOT)

11:43:02.771 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
11:43:02.896 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
11:43:02.902 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.5.3.Final
11:43:03.031 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
11:43:03.120 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Hibernate: create table owner (id bigint not null, age integer not null, name varchar(255), primary key (id))
Hibernate: create table pet (id binary not null, name varchar(255), type integer, owner_id bigint, primary key (id))
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
Hibernate: alter table pet add constraint FK7qfti9yba86tgfe9oobeqxfxg foreign key (owner_id) references owner
11:43:03.688 [main] INFO  example.Application - Populating data
Hibernate: call next value for hibernate_sequence
Hibernate: call next value for hibernate_sequence
Hibernate: insert into owner (age, name, id) values (?, ?, ?)
Hibernate: insert into owner (age, name, id) values (?, ?, ?)
11:43:03.981 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: example.domain.Owner
java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: example.domain.Owner
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:151)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1395)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:482)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3274)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2409)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:448)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
        at io.micronaut.transaction.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:436)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.processCommit(AbstractSynchronousTransactionManager.java:830)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.commit(AbstractSynchronousTransactionManager.java:799)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:185)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.persistAll(HibernateJpaOperations.java:500)
        at io.micronaut.data.runtime.intercept.DefaultSaveAllInterceptor.intercept(DefaultSaveAllInterceptor.java:47)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at example.repositories.PetRepository$Intercepted.saveAll(Unknown Source)
        at example.Application.init(Application.java:58)
        at example.$Application$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3960)
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:83)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at example.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1669)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1654)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:259)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at example.Application.main(Application.java:30)
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: example.domain.Owner
        at org.hibernate.engine.internal.ForeignKeys.getEntityIdentifierIfNotUnsaved(ForeignKeys.java:347)
        at org.hibernate.type.EntityType.getIdentifier(EntityType.java:507)
        at org.hibernate.type.ManyToOneType.isDirty(ManyToOneType.java:334)
        at org.hibernate.type.ManyToOneType.isDirty(ManyToOneType.java:345)
        at org.hibernate.type.TypeHelper.findDirty(TypeHelper.java:316)
        at org.hibernate.persister.entity.AbstractEntityPersister.findDirty(AbstractEntityPersister.java:4737)
        at org.hibernate.event.internal.DefaultFlushEntityEventListener.dirtyCheck(DefaultFlushEntityEventListener.java:584)
        at org.hibernate.event.internal.DefaultFlushEntityEventListener.isUpdateNecessary(DefaultFlushEntityEventListener.java:245)
        at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:170)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:229)
        at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:93)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1391)
        ... 34 common frames omitted
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 3.0.0-SNAPSHOT and Micronaut Data 2.4.8-SNAPSHOT
- **JDK Version:** 8 & 11

**Comment by dstepanov** [comment]
Fixed in core by https://github.com/micronaut-projects/micronaut-core/pull/5789
