### ISSUE TITLE
ArrayIndexOutOfBoundsException when using IN() in combination with Pageable and an additional clause

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-data#1118]
### Expected Behavior

Let's say we have a log event table with a log event date (Timestamp), a log ciritcality (INFO, WARNING, ERROR) and some event text:

```sql
CREATE TABLE log_event(
    id UUID NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    criticality TEXT NOT NULL,
    message TEXT NOT NULL,
    CONSTRAINT log_event_primarykey PRIMARY KEY(id)
)
```

Now we want to a.) filter by `date` and `criticality` and b.) use the `Pageable` mechanism so we don't fetch too much data. Keep in mind, that log levels are inclusive:

* INFO contains INFO, WARNING and ERROR
* WARNING contains WARNING and ERROR
* ERROR contains ERROR

Selecting all queries would look like this:

```sql
logevent=> SELECT * FROM log_event;
                  id                  |             date              | criticality |     message
--------------------------------------+-------------------------------+-------------+------------------
 0e96343c-b301-4557-bb1b-2c1877ce8e0d | 2021-08-11 16:37:03.225552+02 | INFO        | Event 1628692623
 58ba01c3-c4c7-4a89-9f7a-17912366001c | 2021-08-11 16:36:03.225552+02 | ERROR       | Event 1628692563
 0494ea50-47e1-49ff-906b-977e90059b1c | 2021-08-11 16:35:03.225552+02 | ERROR       | Event 1628692503
 4a661b83-ac9d-4f29-8a05-467ff770fd3f | 2021-08-11 16:34:03.225552+02 | ERROR       | Event 1628692443
 6c5fec43-6c73-46e8-9f3b-91cb80a7f183 | 2021-08-11 16:33:03.225552+02 | ERROR       | Event 1628692383
 ff98cc09-0442-4372-9888-328357ffdf9d | 2021-08-11 16:32:03.225552+02 | INFO        | Event 1628692323
 916cc7d8-760d-4dbc-ae5b-74d51bbab9dd | 2021-08-11 16:31:03.225552+02 | ERROR       | Event 1628692263
 0ad1d465-ecec-4f43-a31a-952301dbaa6e | 2021-08-11 16:30:03.225552+02 | ERROR       | Event 1628692203
 501c82a0-79dc-455a-83fc-7bb1a06b2c17 | 2021-08-11 16:29:03.225552+02 | ERROR       | Event 1628692143
 1916d8c5-c251-4cde-b413-4fb12f4fc1e4 | 2021-08-11 16:28:03.225552+02 | ERROR       | Event 1628692083
 16e4f395-17db-4a73-8cfb-b510741c4b3d | 2021-08-11 16:27:03.225552+02 | INFO        | Event 1628692023
 a8f396d7-c38b-4026-958b-d85879df6572 | 2021-08-11 16:26:03.225552+02 | ERROR       | Event 1628691963
 e7be0219-5417-43e3-9edd-5f27705f09af | 2021-08-11 16:25:03.225552+02 | ERROR       | Event 1628691903
 7ad33ecf-eae1-4915-acd9-beda9611560f | 2021-08-11 16:24:03.225552+02 | ERROR       | Event 1628691843
 7bdbee38-99bb-43a5-8e59-979b0c0afc35 | 2021-08-11 16:23:03.225552+02 | ERROR       | Event 1628691783
 6832a573-90cd-43da-960d-8c9447186d9a | 2021-08-11 16:22:03.225552+02 | INFO        | Event 1628691723
 85934485-fff2-4040-9146-c6975fd05350 | 2021-08-11 16:21:03.225552+02 | ERROR       | Event 1628691663
 90ea9895-887b-4a8e-b881-8e63cf8734c8 | 2021-08-11 16:20:03.225552+02 | ERROR       | Event 1628691603
 fa29df26-bc4a-4339-97f4-7955fef974aa | 2021-08-11 16:19:03.225552+02 | ERROR       | Event 1628691543
 3c6ac876-5c02-4117-ad12-8e6a22b70fe7 | 2021-08-11 16:18:03.225552+02 | ERROR       | Event 1628691483
(20 rows)
```

Thus we need to use the SQL `IN()` clause and an example query would look like this (Filter for INFO and today/tomorrow+ last few day) + hit the second page (Offset 5) with a page size of 5:

```sql
logevent=> SELECT * FROM log_event le WHERE le.criticality IN('INFO', 'WARNING', 'ERROR') AND le.date BETWEEN '2021-08-09T12:00:18.912Z' AND '2021-08-12T12:53:18.912Z' OFFSET 5 LIMIT 5;
                  id                  |             date              | criticality |     message
--------------------------------------+-------------------------------+-------------+------------------
 ff98cc09-0442-4372-9888-328357ffdf9d | 2021-08-11 16:32:03.225552+02 | INFO        | Event 1628692323
 916cc7d8-760d-4dbc-ae5b-74d51bbab9dd | 2021-08-11 16:31:03.225552+02 | ERROR       | Event 1628692263
 0ad1d465-ecec-4f43-a31a-952301dbaa6e | 2021-08-11 16:30:03.225552+02 | ERROR       | Event 1628692203
 501c82a0-79dc-455a-83fc-7bb1a06b2c17 | 2021-08-11 16:29:03.225552+02 | ERROR       | Event 1628692143
 1916d8c5-c251-4cde-b413-4fb12f4fc1e4 | 2021-08-11 16:28:03.225552+02 | ERROR       | Event 1628692083
(5 rows)
```

1.) One would write a method like this to find out, that this won't work:

```java
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface LogEventRepository extends CrudRepository<LogEvent, UUID> {

    Page<LogEvent> findByCriticalityAndDateBetweenOrderByDateDesc(List<LogCriticalityDto> criticality, Instant startDate, Instant endDate, Pageable pageable);
}
````

2.) After Googling and reading GitHub code, one would switch to a native query that also provides a count value:

```java
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface LogEventRepository extends CrudRepository<LogEvent, UUID> {

    @Query(
            nativeQuery = true,
            value = "SELECT * FROM log_event le WHERE le.criticality IN(:criticality) AND le.date BETWEEN :startDate AND :endDate",
            countQuery = "SELECT COUNT(*) FROM log_event le WHERE le.criticality IN(:criticality) AND le.date BETWEEN :startDate AND :endDate"
    )
    Page<LogEvent> findByCriticalityAndDateBetweenOrderByDateDesc(List<LogCriticalityDto> criticality, Instant startDate, Instant endDate, Pageable pageable);
}
```

Which generates the following stacktrace:

```
16:44:03.456 [default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: SQL Error preparing Query: Index 3 out of bounds for length 3
io.micronaut.data.exceptions.DataAccessException: SQL Error preparing Query: Index 3 out of bounds for length 3
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:441)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$8(DefaultJdbcRepositoryOperations.java:577)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:575)
	at io.micronaut.data.runtime.intercept.DefaultFindPageInterceptor.intercept(DefaultFindPageInterceptor.java:56)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at ch.swaechter.LogEventRepository$Intercepted.findByCriticalityAndDateBetweenOrderByDateDesc(Unknown Source)
	at ch.swaechter.LogController.getLogEvents(LogController.java:61)
	at ch.swaechter.$LogController$Definition$Intercepted.$$access$$getLogEvents(Unknown Source)
	at ch.swaechter.$LogController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at ch.swaechter.$LogController$Definition$Intercepted.getLogEvents(Unknown Source)
	at ch.swaechter.$LogController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:338)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:502)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1359)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$createExecuteRoutePublisher$19(RoutingInBoundHandler.java:1330)
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$3.doOnComplete(RoutingInBoundHandler.java:1087)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor$1.doOnComplete(JsonContentProcessor.java:140)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)
	at io.micronaut.jackson.parser.JacksonProcessor.doOnComplete(JacksonProcessor.java:139)
	at io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:70)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor.doOnComplete(JsonContentProcessor.java:165)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:416)
	at io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:403)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:452)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:306)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:269)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:123)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:163)
	at io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:260)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:547)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.expandMultipleValues(AbstractSqlRepositoryOperations.java:409)
	at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.prepareStatement(AbstractSqlRepositoryOperations.java:280)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:439)
	... 81 common frames omitted
```

All older issues like #496 or #835 were solved and/or don't use the pagable mechanism/not an additional AND statement for the `criticality` and `date`.

### Actual Behaviour

Let's debug what's happening: Micronaut will call `AbstractSqlRepositoryOperations.expandMultipleValues` to expand all 3 parameters (multiple criticalities, the start date and the end date), but after iterating for the third & last time, a call to `sb.append(queryParametersSplit[inx++]);` (https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractSqlRepositoryOperations.java#L409) will trigger an `ArrayIndexOutOfBoundsException` (Access to index 3/the fourth non existing item). The query generation - nearly finished, will fail:

![Logevent](https://user-images.githubusercontent.com/5626755/129050215-dc649f34-eebf-40ac-b6c9-dbfa9ac18b17.PNG)

A fix would need to rear-end check the index, so we don't index an invalid array value....or is my query wrong/do I misunderstand the paging mechanism and need to add a value to the query?

### Steps To Reproduce

1. Create a Postgresql database with the name `logevent` and the username `logevent` with password `123456aA` (You can change these settings latter in the application.yml
2. Clone the repository https://github.com/swaechter/logeventproblem and build it
3. Start the application. After startup, an event handler will create 20 events (0 - 20 minutes in the past, an event for each past minute)
4. Go to http://localhost:8080/swagger-ui/index.html
5. Call the endpoint with the following request (Please change the time!):

```
{
  "number": 0,
  "size": 5,
  "startDate": "2021-08-10T14:03:40.809Z",
  "endDate": "2021-08-11T14:03:40.809Z",
  "criticality": "INFO"
}
````

`LogEventController` will first fetch the events filtered by date (`LogEventRepository.findByDateBetweenOrderByDateAsc`), which works, and then also filter them by criticality (`LogEventRepository.findByCriticalityAndDateBetweenOrderByDateDesc`), which fails

So calling the simpler method `LogEventRepository.findByDateBetweenOrderByDateAsc` will generate the proper query `SELECT * FROM log_event le WHERE le.date BETWEEN ? AND ? LIMIT 5 OFFSET 25`

### Environment Information

- Windows 10 x64 with AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
- Postgresql 13
- Micronaut 3.0.0 M5

### Example Application

https://github.com/swaechter/logeventproblem

### Version

3.0.0 M5

**Comment by dstepanov** [comment]
I would recommend to use`@Type(STRING_ARRAY) List<String> criticality` and "in-array" query which Postgres supports, that only generates one query but the `IN` syntax needs to expand the query.

**Comment by dstepanov** [comment]
Great, you can also use an interface with the default method do the transformation there.
