### ISSUE TITLE
H2 dialect generates "full outer join" in query when its not (apparently) supported in H2 

### ISSUE THREAD

**Issue by craighewetson** [micronaut-projects/micronaut-data#1178]
### Expected Behavior

when I have the following entities:

```
@MappedEntity
public record Dog(@Id @GeneratedValue Long id,
                  String name,
                  @Nullable @Relation(Kind.MANY_TO_ONE) Collar collar) {
}

```
```
@MappedEntity
public record Collar(@Id @GeneratedValue Long id,
                     String description) {
}

```
and create a repository for the `Dog`

```
@JdbcRepository(dialect = Dialect.H2)
public interface DogRepository extends CrudRepository<Dog, Long> {

    @Join(value = "collar", type = Type.OUTER)
    Optional<Dog> findById(Long id);
}
```
and execute the following:
`dogRepository.findById(1L)`

I expect the query not to throw a sql exception. 

### Actual Behaviour

This query is generated:
`SELECT dog_.`id`,dog_.`name`,dog_.`collar_id` FROM `dog` dog_ FULL OUTER JOIN `collar` dog_collar_ ON dog_.`collar_id`=dog_collar_.`id` WHERE (dog_.`id` = ?)`

and the framework throws the following exception:

```
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT DOG_.`ID`,DOG_.`NAME`,DOG_.`COLLAR_ID` FROM `DOG` DOG_ FULL OUTER[*] JOIN `COLLAR` DOG_COLLAR_ ON DOG_.`COLLAR_ID`=DOG_COLLAR_.`ID` WHERE (DOG_.`ID` = ?)"; SQL statement:
SELECT dog_.`id`,dog_.`name`,dog_.`collar_id` FROM `dog` dog_ FULL OUTER JOIN `collar` dog_collar_ ON dog_.`collar_id`=dog_collar_.`id` WHERE (dog_.`id` = ?) [42000-200]
	at app//org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at app//org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at app//org.h2.message.DbException.get(DbException.java:205)
	at app//org.h2.message.DbException.get(DbException.java:181)
	at app//org.h2.message.DbException.getSyntaxError(DbException.java:229)
	at app//org.h2.command.Parser.getSyntaxError(Parser.java:1051)
	at app//org.h2.command.Parser.readJoin(Parser.java:2408)
	at app//org.h2.command.Parser.parseJoinTableFilter(Parser.java:2839)
	at app//org.h2.command.Parser.parseSelectFromPart(Parser.java:2828)
	at app//org.h2.command.Parser.parseSelect(Parser.java:2959)
	at app//org.h2.command.Parser.parseQuerySub(Parser.java:2817)
	at app//org.h2.command.Parser.parseSelectUnion(Parser.java:2649)
	at app//org.h2.command.Parser.parseQuery(Parser.java:2620)
	at app//org.h2.command.Parser.parsePrepared(Parser.java:868)
	at app//org.h2.command.Parser.parse(Parser.java:843)
	at app//org.h2.command.Parser.parse(Parser.java:819)
	at app//org.h2.command.Parser.prepareCommand(Parser.java:738)
	at app//org.h2.engine.Session.prepareLocal(Session.java:657)
	at app//org.h2.engine.Session.prepareCommand(Session.java:595)
	at app//org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at app//org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
```

I see that there is an outstanding feature request for H2 to support `full outer join`
https://github.com/h2database/h2database/issues/457
So it appears the from sql is generated when the Join type is OUTER

### Steps To Reproduce

Check the project in the linked github repo and execute the test.

### Environment Information

MacOS
Java 16
Micronaut: 3.0.1

### Example Application

https://github.com/craighewetson/bug-micronaut-data-h2-full-outer-join

### Version

3.0.1

**Comment by craighewetson** [comment]
The other issue with the query is that it does not include the `Collar` projection. (eg: dog_collar.*)
If I change the query to a join of default type then the query looks correct:

```
SELECT dog_.`id`,dog_.`name`,dog_.`collar_id`,dog_collar_.`description` AS collar_description FROM `dog` dog_ INNER JOIN `collar` dog_collar_ ON dog_.`collar_id`=dog_collar_.`id` WHERE (dog_.`id` = ?)
```

**Comment by craighewetson** [comment]
I have the same issue (no result but without the error) when using postgres:

https://github.com/craighewetson/bug-micronaut-data-postgres-outer-join

if this is a different issue, let me know if I should log a separate issue.

**Comment by dstepanov** [comment]
It looks like h2 doesn't support full outer join https://github.com/h2database/h2database/issues/457
We only fetch the projected type for "*FETCH" joins. We might need to add `Type.OUTER_FETCH`

**Comment by selakavon** [comment]
Hi @dstepanov , 
   I am looking into the code and adding Type.OUTER_FETCH seems like a trivial task:

* New enum value in io.micronaut.data.annotation.Join
* Add one switch case in io.micronaut.data.model.query.builder.sql.SqlQueryBuilder.resolveJoinType
* Tests in:
** io.micronaut.data.model.annotation.JoinTypeSpec
** io.micronaut.data.model.query.builder.SqlQueryBuilderSpec

Would you like me to create the PR, is this Issue/requirement still valid?

**Comment by dstepanov** [comment]
PRs are welcome. We might need to fail for other DB dialects that don't support it.
