### ISSUE TITLE
Support for MySQL driver when building native image with GraalVM

### ISSUE THREAD

**Issue by kangzq0530** [micronaut-projects/micronaut-data#123]
When I try to build a project with micronaut-data-jdbc, dbcp2 and mysql as a native image, it was failed:

Error: No instances of com.mysql.fabric.jdbc.FabricMySQLDriver are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the java.sql.DriverManager class initializer with a trace:
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at java.sql.DriverManager$2.run(DriverManager.java:603)
        at java.sql.DriverManager$2.run(DriverManager.java:583)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
        at java.sql.DriverManager.<clinit>(DriverManager.java:101)
.  To fix the issue mark com.mysql.fabric.jdbc.FabricMySQLDriver for build-time initialization with --initialize-at-build-time=com.mysql.fabric.jdbc.FabricMySQLDriver or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation.

Detailed message:
Trace:  object java.sql.DriverInfo
        object java.lang.Object[]
        object java.util.concurrent.CopyOnWriteArrayList
        method java.sql.DriverManager.getDriver(String)
Call path from entry point to java.sql.DriverManager.getDriver(String):
        at java.sql.DriverManager.getDriver(DriverManager.java:288)
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:495)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:599)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:809)
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
        at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:221)
        at com.sun.proxy.$Proxy225.equals(Unknown Source)
        at java.util.Hashtable.get(Hashtable.java:367)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:141)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:346)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

It seems micronaut initialize datasources at the build time of native image, which is unsupported.

**Comment by graemerocher** [comment]
Have you tried adding `--initialize-at-build-time=com.mysql.fabric.jdbc.FabricMySQLDriver ` as per the error description?

**Comment by kangzq0530** [comment]
> Have you tried adding `--initialize-at-build-time=com.mysql.fabric.jdbc.FabricMySQLDriver ` as per the error description?

yes I tried, but mysql initialize it's threadpool in class initialization, this is unsupported to initialize at native-image build time

**Comment by graemerocher** [comment]
the following allows the image to build

```
native-image --initialize-at-run-time=java.sql.DriverManager -H:IncludeResourceBundles=com.mysql.cj.LocalizedErrorMessages --no-fallback --no-server -cp build/libs/example-jdbc-0.1-all.jar
```

However fails at runtime with:

```
Caused by: java.lang.ClassCastException: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.WrongArgumentException
	at com.mysql.cj.util.Util.getInstance(Util.java:169)
	at com.mysql.cj.util.Util.getInstance(Util.java:174)
	at com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:200)

```

**Comment by graemerocher** [comment]
Related issue https://bugs.mysql.com/bug.php?id=91968

**Comment by kangzq0530** [comment]
Now I use mariadb instead.

**Comment by graemerocher** [comment]
oke

**Comment by graemerocher** [comment]
@kangzq0530 what were the flags you passed to Graal to support mariadb?

**Comment by kangzq0530** [comment]
A substitude class:
```
@Delete
@TargetClass(className = "org.mariadb.jdbc.internal.com.send.authentication.SendPamAuthPacket")
final class Target_org_mariadb_jdbc_internal_com_send_authentication_SendPamAuthPacket {
}
```
native-image.properties:
```
Args = -H:DynamicProxyConfigurationResources=${.}/proxy-config.json \
  -H:ReflectionConfigurationResources=${.}/reflection-config.json \
  -H:+ReportUnsupportedElementsAtRuntime \
  --initialize-at-build-time=org.mariadb \
  --initialize-at-run-time=org.mariadb.jdbc.credential.aws \
  --initialize-at-run-time=org.mariadb.jdbc.internal.failover.impl.MastersSlavesListener \
  --initialize-at-run-time=org.mariadb.jdbc.internal.com.send.authentication.SendPamAuthPacket
```
reflection-config.properties:
```
[
  {
    "name": "org.mariadb.jdbc.Driver",
    "allDeclaredConstructors": true
  }
]
```
proxy-config.properties:
```
[
  ["java.sql.Connection"],
  ["java.sql.Statement"],
  ["java.sql.ResultSet"]
]
```
These are all my work to support mariadb.Maybe some are unnecessary.

**Comment by graemerocher** [comment]
@kangzq0530 Thanks for the info

**Comment by kangzq0530** [comment]
@graemerocher One more necessary reflection config:
```
{
    "name": "org.mariadb.jdbc.util.Options",
    "allDeclaredFields": true
  }
```
without this will fail on run time when initialize database with DriverManager

**Comment by athkalia** [comment]
Hello, I was using Mysql with native images successfully, and all of a sudden I started getting errors similar to the above. Is MySQL supported these days for native images or not? Could it be that I (or Micronaut) started using some feature of MySql that wasn't being used before that triggered the errors?

My exception looks like this:

```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server.
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1009)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0Definition.build(Unknown Source)
at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:153)
at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2768)
at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2754)
at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2292)
at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1562)
at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)
at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2905)
at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:180)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:248)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:162)
at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:115)
at io.micronaut.function.aws.proxy.MicronautLambdaHandler.<init>(MicronautLambdaHandler.java:54)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.createRequestHandler(MicronautLambdaRuntime.java:38)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.createHandler(AbstractMicronautLambdaRuntime.java:192)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:313)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:50)
Caused by: java.lang.ClassCastException: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.WrongArgumentException
at com.mysql.cj.util.StringUtils.toString(StringUtils.java:1708)
at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:619)
at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:584)
at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:736)
at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:717)
at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:685)
at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:134)
at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:469)
at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:174)
at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348)
at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
... 33 common frames omitted
io.micronaut.context.exceptions.ConfigurationException: Exception thrown instantiating MicronautLambdaRuntimeHandler
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.createRequestHandler(MicronautLambdaRuntime.java:40)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.createHandler(AbstractMicronautLambdaRuntime.java:192)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:313)
at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:50)
...
```

**Comment by graemerocher** [comment]
@athkalia provide an example that reproduces the issue in another report

**Comment by athkalia** [comment]
Hi @graemerocher sure thing, will do. In the meantime, is MySql supported overall or not with native images?

**Comment by graemerocher** [comment]
@athkalia We have functional tests that test MySQL integration with native image https://github.com/micronaut-projects/micronaut-sql/runs/3181493697?check_suite_focus=true#step:7:3328

Having said that the native image driver doesn't come with native image config so we had to roll our own which may not cover every case https://github.com/micronaut-projects/micronaut-sql/blob/06019b28a468a0c2206cd402be59cd3a24af9dda/jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java#L260

Make sure you are using the correct driver version since the tests run against this version:

https://github.com/micronaut-projects/micronaut-core/blob/a949a27c69ff00fe50fa751adf0501540aee79b2/gradle.properties#L159
