### ISSUE TITLE
Error encoding JSON column for update queries when using @DateUpdated

### ISSUE THREAD

**Issue by safarmer** [micronaut-projects/micronaut-data#1256]
### Expected Behavior

It should be possible to update a JSON column using micronaut-data-jdbc in an entity that uses `@DateCreated`/`@DateUpdated`.  The code in question works when rolling back to Micronaut 3.1.3.

### Actual Behaviour

The test fails with the query being considered expandable in `StoredSqlOperation` (and related classes). The failure was first noticed when updating an entity with a JSON column containing a string array. Each item in the array was being saved as a single string parameter rather than being converted to a JSON string. This seems to be because the query params are expanded so the array of strings looks like individual strings in the call to `setStatementParameter` at `io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.java:185`

This causes the following check to fail:
```java
            case JSON:
                if (value != null && jsonCodec != null && !value.getClass().equals(String.class)) {
                    value = new String(jsonCodec.encode(value), StandardCharsets.UTF_8);
                }
                break;
```

Logs:

```
23:15:49.156 [Test worker] DEBUG io.micronaut.data.query - Executing CREATE statement: 
CREATE TABLE `demo` (`id` INT PRIMARY KEY AUTO_INCREMENT,`data` JSON NOT NULL,`created` TIMESTAMP(6) DEFAULT NOW(6),`updated` TIMESTAMP(6) DEFAULT NOW(6));

23:15:49.389 [Test worker] DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO `demo` (`data`,`created`,`updated`) VALUES (CONVERT(? USING UTF8MB4),?,?)
23:15:49.462 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 1 to value ["data-1","data-2"] with data type: JSON
23:15:49.463 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 2 to value 2022-01-04T12:15:49.392079708Z with data type: TIMESTAMP
23:15:49.464 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 3 to value 2022-01-04T12:15:49.392079708Z with data type: TIMESTAMP
23:15:49.474 [Test worker] DEBUG io.micronaut.data.query - Executing SQL UPDATE: UPDATE `demo` SET `data`=CONVERT(? USING UTF8MB4),`updated`=? WHERE (`id` = ?)
23:15:49.474 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 1 to value data-1 with data type: JSON
23:15:49.474 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 2 to value data-2 with data type: JSON
23:15:49.474 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 3 to value updated-1 with data type: JSON
23:15:49.474 [Test worker] TRACE io.micronaut.data.query - Binding parameter at position 4 to value 2022-01-04T12:15:49.473949932Z with data type: TIMESTAMP
  
io.micronaut.data.exceptions.DataAccessException: Error executing SQL UPDATE: Unable to set PreparedStatement value: Parameter index out of range (4 > number of parameters, which is 3).
    at app//io.micronaut.data.runtime.operations.internal.AbstractRepositoryOperations.updateOne(AbstractRepositoryOperations.java:484)
    at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$update$13(DefaultJdbcRepositoryOperations.java:711)
    at app//io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
    at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.update(DefaultJdbcRepositoryOperations.java:709)
    at app//io.micronaut.data.runtime.intercept.DefaultUpdateEntityInterceptor.intercept(DefaultUpdateEntityInterceptor.java:45)
    at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:114)
    at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:88)
    at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    at app//io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
    at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    at app//com.example.DemoEntityRepository$Intercepted.update(Unknown Source)
    at app//com.example.DemoEntityRepositoryTest.updateEntity(DemoEntityRepositoryTest.java:28)
Caused by:
io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: Parameter index out of range (4 > number of parameters, which is 3).
    at app//io.micronaut.data.jdbc.mapper.JdbcQueryStatement.newDataAccessException(JdbcQueryStatement.java:322)
    at app//io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setTimestamp(JdbcQueryStatement.java:138)
    at app//io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setTimestamp(JdbcQueryStatement.java:35)
    at app//io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:106)
    at app//io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:122)
    at app//io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:35)
    at app//io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.setStatementParameter(AbstractSqlRepositoryOperations.java:215)
    at app//io.micronaut.data.runtime.operations.internal.StoredSqlOperation.setStatementParameter(StoredSqlOperation.java:235)
    at app//io.micronaut.data.runtime.operations.internal.StoredSqlOperation.setParameters(StoredSqlOperation.java:223)
    at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.setParameters(DefaultJdbcRepositoryOperations.java:1020)
    at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.setParameters(DefaultJdbcRepositoryOperations.java:979)
    at app//io.micronaut.data.runtime.operations.internal.AbstractRepositoryOperations.updateOne(AbstractRepositoryOperations.java:469)
    ... 11 more
Caused by:
java.sql.SQLException: Parameter index out of range (4 > number of parameters, which is 3).
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
    at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1373)
    at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1386)
    at com.mysql.cj.jdbc.ClientPreparedStatement.setTimestamp(ClientPreparedStatement.java:1774)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setTimestamp(HikariProxyPreparedStatement.java)
    at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setTimestamp(JdbcQueryStatement.java:133)
    ... 21 more

```

### Steps To Reproduce

1. Check-out demo project
2. run `./gradlew check`

To get the tests to pass, either:
1. Downgrade to Micronaut 3.1.4, or
2. Remove the `@DateUpdated` annotation from the `updated` field in `DemoEntity`

### Environment Information

- Fedora 35
- Java 17.0.1
- Gradle 7.3.1

### Example Application

[safarmer/micronaut-data-update-issue](https://github.com/safarmer/micronaut-data-update-issue)
### Version

3.2.4

**Comment by mayankj512** [comment]
Hi @dstepanov , We are seeing the same issue on micronaut 3.3.4 (which uses micronaut-data 3.2.2 in bom). 
In which micronaut release this change is planned to ship?
