### ISSUE TITLE
Oracle Invalid column type: 16 when Binding null Boolean values at insert

### ISSUE THREAD

**Issue by ugurbor** [micronaut-projects/micronaut-data#1259]
### Expected Behavior

Binding null NUMBER columns to Boolean type works as expected. Same expected at insert.

### Actual Behaviour

"Invalid column type: 16" exception is thrown as below

I have found the issue is this line: https://github.com/micronaut-projects/micronaut-data/blob/a699b42051770e326a742fda5e443c4b47de71d6/data-jdbc/src/main/java/io/micronaut/data/jdbc/mapper/JdbcQueryStatement.java#L77

If I change Types.BOOLEAN to Types.NUMBERIC or Types.INTEGER it works.

```
io.micronaut.data.exceptions.DataAccessException: SQL Error executing INSERT: Error setting JDBC null value: Invalid column type: 16
	at io.micronaut.data.runtime.operations.internal.AbstractRepositoryOperations.persistOne(AbstractRepositoryOperations.java:289)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persist$16(DefaultJdbcRepositoryOperations.java:750)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persist(DefaultJdbcRepositoryOperations.java:748)
	at io.micronaut.data.runtime.intercept.DefaultSaveEntityInterceptor.intercept(DefaultSaveEntityInterceptor.java:45)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:114)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:88)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.dao.SampleRepository$Intercepted.save(Unknown Source)
	at com.example.controller.SampleController.createSample(SampleController.java:25)
	at com.example.controller.$SampleController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:584)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:649)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$4.doOnComplete(RoutingInBoundHandler.java:880)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor$1.doOnComplete(JsonContentProcessor.java:136)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)
	at io.micronaut.jackson.core.parser.JacksonCoreProcessor.doOnComplete(JacksonCoreProcessor.java:94)
	at io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:71)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor.doOnComplete(JsonContentProcessor.java:161)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:416)
	at io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:403)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:465)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:312)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:275)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:123)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:163)
	at io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:266)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:547)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.micronaut.data.exceptions.DataAccessException: Error setting JDBC null value: Invalid column type: 16
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:119)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:35)
	at io.micronaut.data.runtime.operations.internal.AbstractSqlRepositoryOperations.setStatementParameter(AbstractSqlRepositoryOperations.java:215)
	at io.micronaut.data.runtime.operations.internal.StoredSqlOperation.setStatementParameter(StoredSqlOperation.java:244)
	at io.micronaut.data.runtime.operations.internal.StoredSqlOperation.setParameters(StoredSqlOperation.java:223)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.setParameters(DefaultJdbcRepositoryOperations.java:1019)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.setParameters(DefaultJdbcRepositoryOperations.java:978)
	at io.micronaut.data.runtime.operations.internal.AbstractRepositoryOperations.lambda$persistOne$1(AbstractRepositoryOperations.java:279)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:368)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:129)
	at io.micronaut.data.runtime.operations.internal.AbstractRepositoryOperations.persistOne(AbstractRepositoryOperations.java:278)
	... 81 common frames omitted
Caused by: java.sql.SQLException: Invalid column type: 16
	at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:4469)
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4382)
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4366)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setNull(OraclePreparedStatementWrapper.java:937)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setNull(HikariProxyPreparedStatement.java)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:77)
	... 91 common frames omitted
```

### Steps To Reproduce

CrudRepository.save with a null Boolean entity is enough to reproduce.

### Environment Information

- Arch Linux
- Java 11
- Tested both the Git version and the maven (3.2.0) version

### Version

3.2.3-SNAPSHOT

**Comment by dstepanov** [comment]
What version of Oracle DB and driver do you use?

**Comment by ugurbor** [comment]
Driver is com.oracle.database.jdbc:ojdbc8:jar:21.1.0.0
Database version is 11.2.0.4.0 - 11g

**Comment by dstepanov** [comment]
Unfortunately, this version of OracleDB doesn't support boolean types, you need to use custom `AttributeConverter` to map the boolean to something else.

**Comment by ugurbor** [comment]
I don't think any version of Oracle DB supports Boolean data type and most tooling has to implement a workaround for this. Only problem is, again, this line: 
https://github.com/micronaut-projects/micronaut-data/blob/a699b42051770e326a742fda5e443c4b47de71d6/data-jdbc/src/main/java/io/micronaut/data/jdbc/mapper/JdbcQueryStatement.java#L77

**Comment by graemerocher** [comment]
Yes there is no Boolean type in Oracle. We will have to implement another solution since  changing that line will break other databases

**Comment by dstepanov** [comment]
I don't really think anything else much can be done on our side.

It looks like the Oracle DB driver will allow setting the boolean value for some cases but doesn't support null as in three-state boolean representation, it might be an issue for the driver.

There are multiple ways how to represent a boolean type in the DB https://stackoverflow.com/questions/3726758/is-there-any-boolean-type-in-oracle-databases so we cannot easily decide which type should be set.

The workaround is pretty simple to create a custom `AttributeConverter`:

```java
class BooleanToIntegerAttributeConverter implements AttributeConverter<Boolean, Integer> {
    @Override
    public Integer convertToDatabaseColumn(Boolean bool) {
        if (bool == null) {
            return null;
        }
        return bool ? 1 : 0;
    }

    @Override
    public Boolean convertToEntityAttribute(Integer integer) {
        if (integer == null) {
            return null;
        }
        return integer != 0;
    }
}
```
and:
```java
@MappedProperty(converter = BooleanToIntegerAttributeConverter.class)
private Boolean myBool
```
You can also create a custom annotation for that case:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
@Documented
@Inherited
@MappedProperty(converter = BooleanToIntegerAttributeConverter.class)
public @interface BooleanAsInteger {
}
```
and use:
```java
@BooleanAsInteger
private Boolean myBool

```

**Comment by dstepanov** [comment]
Another solution is probably just to define the actual type:
```java
@MappedProperty(type = DataType.INTEGER)
private Boolean myBool
```

but that would rely on some internal convertor.

**Comment by ugurbor** [comment]
I have already tested with an AttributeConverter I wrote and it works with this definition:

```java
@Singleton
public class OracleBooleanConverter implements AttributeConverter<Boolean, Integer> {
    @Override
    public Integer convertToPersistedValue(Boolean entityValue, @NonNull ConversionContext context) {
        return entityValue == null || !entityValue ? 0 : 1;
    }

    @Override
    public Boolean convertToEntityValue(Integer persistedValue, @NonNull ConversionContext context) {
        return persistedValue != null && persistedValue != 0;
    }
}
```
And I use it as:

```java
    @TypeDef(type = DataType.INTEGER, converter = OracleBooleanConverter.class)
    private Boolean boolField;
```

If there was an internal converter 'type = DataType.INTEGER' would be much easier. Still, these are all extensions but in my opinion should be baked into micronaut-data like other tooling. I think other tools mostly assume Oracle Boolean to be NUMBER(0,1).
