### ISSUE TITLE
Multiple possible bean candidates when datasource is set using R2DBC 

### ISSUE THREAD

**Issue by zsiegel** [micronaut-projects/micronaut-data#1285]
### Expected Behavior

When multiple datasources have been created using R2DBC with the following.

```yml
r2dbc:
  datasources:
    app:
      url: r2dbc:tc:postgresql:///postgres?currentSchema=app
      dialect: postgres
      driver: postgres
      host: test
      username: test
    market:
      url: r2dbc:tc:postgresql:///postgres?currentSchema=market
      dialect: postgres
      driver: postgres
      host: test
      username: test
```

With a repo defined as the following.
```kt
@R2dbcRepository(dialect = Dialect.POSTGRES, value = "market")
interface StatsRepo : CoroutineCrudRepository<Statistics, UUID> { }

```

And a Micronaut test that looks like.

```kt
@MicronautTest
class StatsRepoTests {

    @Inject
    lateinit var context: ApplicationContext

    @Inject
    lateinit var statsRepo: StatsRepo

}
```

The tests should pass. 

### Actual Behaviour

When the above test runs the following error is thrown. I would expect that since "value" is set the R2DBC repo with the proper datasource should be used.

```

Multiple possible bean candidates found: [io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations, io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations]
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations, io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations]
	at app//io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2430)
	at app//io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:454)
	at app//io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3254)
	at app//io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3141)
	at app//io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3055)
	at app//io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2751)
	at app//io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1705)
	at app//io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1679)
	at app//io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:906)
	at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.lambda$intercept$0(TransactionalInterceptor.java:105)
	at java.base@11.0.13/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:100)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//com.exdividend.postgres.StatsRepo$Intercepted.upsert(Unknown Source)
	at app//com.centerboard.exdividend.test.StatsRepoTests$upsert$1.invokeSuspend(StatsRepoTests.kt:72)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//com.centerboard.exdividend.test.StatsRepoTests.upsert(StatsRepoTests.kt:67)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:117)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base@11.0.13/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base@11.0.13/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

```

### Steps To Reproduce

1. Run the tests or start an app with multiple datasources.

### Environment Information

openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

Micronaut 3.1.4

### Version

3.1.4

**Comment by zsiegel** [comment]
I have tried without luck to define a Qualifier to make this work. I was sort of expecting this to work regardless given the datasource is defined.

**Comment by dstepanov** [comment]
From:
```
app//io.micronaut.transaction.interceptor.TransactionalInterceptor.lambda$intercept$0(TransactionalInterceptor.java:105)
	at java.base@11.0.13/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:100)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//com.exdividend.postgres.StatsRepo$Intercepted.upsert(Unknown Source)
	at app//com.centerboard.exdividend.test.StatsRepoTests$upsert$1.invokeSuspend(StatsRepoTests.kt:72)
```
I see `TransactionalInterceptor` call probably doesn't know which instance needs to be used. I think you need to use `@TransactionalAdvice("market")`

**Comment by zsiegel** [comment]
That does indeed do the trick! Is there a place I can document this for other folks? 

Might be helpful in the documentation to know you need to use this when using multiple datasources. 

Also I ran into another related problem using Flyway with R2DBC and TestContainers and realized they are not synced up yet. Is this something relevant to add to the documentation?

**Comment by dstepanov** [comment]
It would be great to add more documentation. Regarding Flyway, I think you need to include JDBC driver for that.

**Comment by zsiegel** [comment]
I will work on a documentation PR this week.

Regarding Flyway, TestContainers, JDBC, and R2DBC there is a bit of a gap I think but below is how I solved it. To be clear I do NOT think this is a Micronaut issue.

Lets us say you want to use the TestContainers for testing with Flyway. And you have the following declaration because Flyway does not work with R2DBC.

```yml
datasources:
  app:
    url: jdbc:tc:postgresql:12:///postgres?TC_IMAGE_TAG=13.5
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    options:
      currentSchema: market

  market:
    url: jdbc:tc:postgresql:12:///postgres?TC_IMAGE_TAG=13.5
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    options:
      currentSchema: market

flyway:
  datasources:
    default:
      enabled: true
      schemas:
        - app
        - market
      create-schemas: true

r2dbc:
  datasources:
    app:
      url: r2dbc:tc:postgresql:///postgres?TC_IMAGE_TAG=13.5-alpine3.15
      dialect: postgres
      options:
        currentSchema: app
    market:
      url: r2dbc:tc:postgresql:///postgres?TC_IMAGE_TAG=13.5-alpine3.15
      dialect: postgres
      options:
        currentSchema: market
```

I have not found a way to make both the JDBC declaration and the R2DBC declaration use the same TestContainers DB and driver. So in the case above JDBC will migrate the JDBC declared DB but not the other declaration - at least that's my experience maybe I am wrong somehow?

I have hacked around this by creating a base class manually and exposing migrating the R2DBC connections manually. 

```kt
class PostgresContainer(image: String = "postgres:13.5-alpine3.15") : PostgreSQLContainer<PostgresContainer>(image)

fun postgresContainer(): PostgresContainer {
    return PostgresContainer()
        .withExposedPorts(5432)
}

fun PostgresContainer.jdbi(): Jdbi {
    val jdbi = Jdbi.create(this.jdbcUrl, this.username, this.password)
    jdbi.installPlugins()
    return jdbi
}

@Testcontainers
class PostgreSqlTest : PostgreSqlTestWithMigrations() {

    @Test
    fun sanityTest() {

        val jdbi = postgres.jdbi()

        jdbi.useHandle<Nothing> { handle ->
            val result = handle.createQuery("SELECT pid from pg_stat_activity").mapTo(Int::class.java)
            assertNotNull(result)
        }
    }
}

open class PostgreSqlTestWithMigrations {

    @Container
    val postgres = postgresContainer()

    private val config = ClassicConfiguration()

    @BeforeEach
    fun migrate() {
        postgres.start()

        config.setDataSource(postgres.jdbcUrl, postgres.username, postgres.password)
        config.schemas = arrayOf("market", "app")

        Flyway(config).migrate()
    }

    @AfterEach
    fun clean() {
        postgres.start()
        Flyway(config).clean()
    }

    fun r2dbcProps(): Map<String, Any> {
        return r2dbcMarketProps().plus(rd2bcUserProps())
    }

    private fun r2dbcMarketProps(): Map<String, Any> {
        return mapOf(
            "r2dbc.datasources.market.url" to "r2dbc:postgresql://${postgres.host}:${postgres.firstMappedPort}/?currentSchema=market",
            "r2dbc.datasources.market.username" to postgres.username,
            "r2dbc.datasources.market.password" to postgres.password,
            "r2dbc.datasources.market.dialect" to Dialect.POSTGRES,
        )
    }

    private fun rd2bcUserProps(): Map<String, Any> {
        return mapOf(
            "r2dbc.datasources.app.url" to "r2dbc:postgresql://${postgres.host}:${postgres.firstMappedPort}/?currentSchema=app",
            "r2dbc.datasources.app.username" to postgres.username,
            "r2dbc.datasources.app.password" to postgres.password,
            "r2dbc.datasources.app.dialect" to Dialect.POSTGRES,
        )
    }
}
```

So for testing I utilize this base class rather than the `application-test.properties` to manage the databases. I have a mixture of JDBI (with JDBC driver) and R2DBC repos as I am transitioning.

Then the test looks something like this.

```kt
class StatsRepoTests : PostgreSqlTestWithMigrations() {

    @Inject
    lateinit var context: ApplicationContext

    @BeforeEach
    fun getProperties() {
        context = ApplicationContext.run(r2dbcProps())
    }

    private fun getRepo(): StatsRepo {
        return context.getBean(StatsRepo::class.java)
    }

    //Tests go here
```
