### ISSUE TITLE
Jdbc CoroutineCrudRepository does not handle nullable return types

### ISSUE THREAD

**Issue by marcmarcet** [micronaut-projects/micronaut-data#1297]
### Expected Behavior

Given the following repository, I'd expect that if no record is found, it returns `null`

```
@JdbcRepository(dialect = Dialect.MYSQL)
interface UserRepository : CoroutineCrudRepository<User, Long>, {
    suspend fun findByEmail(email: String): User?
}
```

### Actual Behaviour

What I actually get is a `EmptyResultException`

```
io.micronaut.data.exceptions.EmptyResultException: Query produced no result
	at io.micronaut.data.runtime.operations.ExecutorAsyncOperations.lambda$findOne$2(ExecutorAsyncOperations.java:89)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

Any similar CoroutineCrudRepository should be able to reproduce the issue

### Environment Information

macOS Monterrey
Kotlin 1.6.10
JDK 17

### Version

3.2.7

**Comment by marcmarcet** [comment]
I'm currently using the following work around, which seems to be good enough as a temporary solution.

```
@JdbcRepository(dialect = Dialect.MYSQL)
interface UserRepository : CoroutineCrudRepository<User, Long> {
    suspend fun findByEmail(email: String): User
}

suspend fun UserRepository.findByEmailAsNullable(email: String): User? {
    return try {
        this.findByEmail(email)
    } catch (_: EmptyResultException) {
        null
    }
}

```
