### ISSUE TITLE
Order By clause printed twice

### ISSUE THREAD

**Issue by seprokof** [micronaut-projects/micronaut-data#1377]
### Expected Behavior

My stack consist from Micronaut Data, R2DBC, PostgreSQL. I'm trying to select data from the database and apply sort on it. 
For that purpose I'm using `ReactorJpaSpecificationExecutor#findAll(QuerySpecification, Sort)` method specifying `Pageable` as second argument which looks like 

```java
Pageable pageable = Pageable.from(Sort.of(Order.desc("creationTimestamp")));
```

I expect that query will be executed successfully respecting specified `Sort` argument.

### Actual Behaviour

Actual behaviour is that request ends up with exception `io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: syntax error at or near "ORDER"`. After enabling trace logs I see that generated query is incorrect as it has two "ORDER BY" clauses instead of one.

`2022-03-10 02:43:33.345 DEBUG [reactor-tcp-nio-1] io.micronaut.data.query                  : Executing Query: SELECT sample."id",sample."creation_timestamp",sample."name" FROM "sample" sample ORDER BY sample."creation_timestamp" DESC ORDER BY sample.creation_timestamp DESC`

After debugging I see that at this point https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/reactive/FindAllReactiveSpecificationInterceptor.java#L47 SQL query inside `preparedQuery` is correct and looks like `SELECT sample."id",sample."creation_timestamp",sample."name" FROM "sample" sample ORDER BY sample."creation_timestamp" DESC`. When the code continues I see that while preparing statement it adds `ORDER BY` clause second time (code path starts from here https://github.com/micronaut-projects/micronaut-data/blob/master/data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractSqlRepositoryOperations.java#L159).

### Environment Information

Not related to enviroment, however:
- OS - Windows 10 Enterprice
- Java - OpenJDK 11

Versions: 
- Micronaut Data - 3.2.0
- Micronaut Core - 3.2.1
- r2dbc-postgresql - 0.8.10.RELEASE

### Version

3.2.1

**Comment by dstepanov** [comment]
Do you also have a sorting inside `QuerySpecification`?

I have tried to reproduce it:
```
personRepository.findAll(nameEquals("Jeff"), Pageable.from(Sort.of(Sort.Order.desc("name")))).size() == 1
```
https://github.com/micronaut-projects/micronaut-data/blob/0bd92dece5d3da1bf46b16e1562dcc6b4bd6cfa5/data-tck/src/main/groovy/io/micronaut/data/tck/tests/AbstractRepositorySpec.groovy#L1754

And it worked.

**Comment by seprokof** [comment]
Denis, thanks for you comment and attempt to repoduce issue. I don't have any sorting into `QuerySpecification` itself. Let me try to prepare some minimal example, so you can hit this problem.

**Comment by dstepanov** [comment]
Thanks, please try to reproduce it with the latest version

**Comment by seprokof** [comment]
Denis, apologize for delay on this. [Here is a sample application](https://github.com/seprokof/orderby-error) which can be used to observe the issue. As you asked I used fresh version of Micronaut.

**Steps:**
1. Get code
2. Create database `sampledb` managed by `postgres` user with `postgres` password or [update credentials](https://github.com/seprokof/orderby-error/blob/master/src/main/resources/application.yml#L22-L24) in `application.yml` 
3. Run with `gradle run`
4. Open `http://localhost:8080/swagger-ui#` in favourite browser
5. Add two Samples using Swagger UI with different values in `data` field
6. Invoke GET endpoint in Swagger UI without setting any query parameters
7. Invoke GET endpoint in Swagger UI when `sort` parameter is `-data`

**Expected result:**
step (6): Both Samples added on step 5 appears
step (7): Both Samples added on step 5 appears and sorted descending by `data`.

**Actual result:**
step (7): HTTP 500 Internal Server Error returned.

**Log**
Here is a log which I get for invoking those steps
```
> Task :run
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.4.1)

2022-04-11 20:27:11.772  INFO [main] i.m.l.PropertiesLoggingLevelsConfigurer  : Setting log level 'DEBUG' for logger: 'io.micronaut.data.query'
2022-04-11 20:27:12.571  INFO [main] io.micronaut.runtime.Micronaut           : Startup completed in 4583ms. Server Running: http://localhost:8080
2022-04-11 20:27:54.911  INFO [reactor-tcp-nio-1] com.seprokof.sample.SampleController     : SampleEntity(id=1, data=string1) successfully created
2022-04-11 20:28:04.098  INFO [reactor-tcp-nio-1] com.seprokof.sample.SampleController     : SampleEntity(id=2, data=string2) successfully created
2022-04-11 20:28:09.677 DEBUG [reactor-tcp-nio-1] io.micronaut.data.query                  : Executing Query: SELECT sample."id",sample."data" FROM "sample" sample
2022-04-11 20:28:09.765  INFO [reactor-tcp-nio-1] com.seprokof.sample.SampleController     : 2 sample(s) returned
2022-04-11 20:28:15.532 DEBUG [reactor-tcp-nio-1] io.micronaut.data.query                  : Executing Query: SELECT sample."id",sample."data" FROM "sample" sample ORDER BY sample."data" DESC ORDER BY sample.data DESC
2022-04-11 20:28:15.538  WARN [reactor-tcp-nio-1] i.r.p.client.ReactorNettyClient          : Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=42601, MESSAGE=syntax error at or near "ORDER", POSITION=83, FILE=scan.l, LINE=1180, ROUTINE=scanner_yyerror
2022-04-11 20:28:15.544  WARN [reactor-tcp-nio-1] m.d.r.o.DefaultR2dbcRepositoryOperations : Rolling back transaction on error: syntax error at or near "ORDER"
io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: syntax error at or near "ORDER"
        at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:86)
        at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:111)
        at io.r2dbc.postgresql.PostgresqlResult.lambda$map$2(PostgresqlResult.java:111)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:169)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:668)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:746)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:788)
        at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:239)
        at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:86)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
        at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:636)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:887)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:761)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:668)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
2022-04-11 20:28:15.550 ERROR [reactor-tcp-nio-1] i.m.h.netty.stream.HttpStreamsHandler    : Error occurred writing stream response: syntax error at or near "ORDER"
io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: syntax error at or near "ORDER"
        at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:86)
        at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:111)
        at io.r2dbc.postgresql.PostgresqlResult.lambda$map$2(PostgresqlResult.java:111)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:169)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:668)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:746)
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:788)
        at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:239)
        at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:86)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
        at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:636)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:887)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:761)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:668)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dstepanov** [comment]
Please create a test with testcontainer integration.

**Comment by seprokof** [comment]
Integration test added ([this commit](https://github.com/seprokof/orderby-error/commit/76f436b7832d4fa59ecc89592a67f62d4fc3ebdd)).

Mentioned steps now automated, so I add several rows in table (success), retrieving all rows (success), retrieveing all rows sorted (failure).
