### ISSUE TITLE
SQL Exception when using Collection<String> as parameter with custom Query

### ISSUE THREAD

**Issue by Goldmensch** [micronaut-projects/micronaut-data#1398]
### Actual Behaviour

It throws an SQL Exception instead of deleting the entries.
```java
22:21:25.754 [main] DEBUG i.m.t.j.DataSourceTransactionManager -
        Initiating transaction rollback on application exception
io.micronaut.data.exceptions.DataAccessException: Error executing SQL Query: ERROR: syntax error at or near "$3"
  Position: 156
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$3(DefaultJdbcRepositoryOperations.java:463)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:406)
	at io.micronaut.data.runtime.intercept.DefaultFindOneInterceptor.intercept(DefaultFindOneInterceptor.java:45)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:114)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:88)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at club.devcord.devmarkt.repositories.RoleRepo$Intercepted.deletePermissions(Unknown Source)
	at club.devcord.devmarkt.auth.TestFactory.testLol(TestFactory.java:39)
	at club.devcord.devmarkt.auth.$TestFactory$TestLol0$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2664)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at club.devcord.devmarkt.Application.main(Application.java:24)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$3"
  Position: 156
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "$3"
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$3(DefaultJdbcRepositoryOperations.java:410)
	... 24 common frames omitted
	```

### Steps To Reproduce

I have following repository:
```java
@JdbcRepository
public interface RoleRepo extends CrudRepository<Role, Integer> {


  @io.micronaut.data.annotation.Query(value = """
WITH to_delete_role AS (
    SELECT id FROM roles WHERE name = :roleName
),
to_delete_perm AS (
     SELECT id FROM permissions WHERE operation = :operation AND query IN :queries
 )
DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM to_delete_role) AND permission_id IN (SELECT id FROM to_delete_perm);
""")
  void deletePermissions(String roleName, Operation operation, Collection<String> queries);
  }
  ```
  
  The method call: 
  ```java
      repo.deletePermissions("test", Operation.MUTATION, Set.of("testMutation1", "testQuery2"));
  ```
  
As info the query runs without problems without micronaut.

### Environment Information

- Manjaro
- Java 17

### Version

3.3.4

**Comment by dstepanov** [comment]
Please try it with the latest version

**Comment by Goldmensch** [comment]
> 

same problem with version 3.4.0

**Comment by dstepanov** [comment]
It hard to tell without a sample app.

Maybe if you enable query log to see what’s generated

**Comment by Goldmensch** [comment]
I will create a sample project, give me a few minutes

**Comment by Goldmensch** [comment]
https://github.com/Goldmensch/sample-project-issue-1398 here the sample project

**Comment by Goldmensch** [comment]
```sql
postgres-db-1  | 2022-03-23 11:56:44.251 UTC [48] STATEMENT:  WITH to_delete_role AS (
postgres-db-1  |            SELECT id FROM roles WHERE name = $1
postgres-db-1  |        ),
postgres-db-1  |        to_delete_perm AS (
postgres-db-1  |             SELECT id FROM permissions WHERE operation = $2 AND query IN $3,$4
postgres-db-1  |         )
postgres-db-1  |        DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM to_delete_role) AND permission_id IN (SELECT id FROM to_delete_perm)
```
database log, seems that micronaut doesn't generate a list here

**Comment by dstepanov** [comment]
On the first look you are missing Dialect set on JdbcRepository

**Comment by Goldmensch** [comment]
I thought Micronaut resolves this in the application.yml? Anyway, this nothing changes here.

**Comment by dstepanov** [comment]
No, sql queries are generated during the compile time that's why we need to know it before.

Can you please add a test with testcontainers integration? I don't have any db running locally

**Comment by Goldmensch** [comment]
Queries are not enums, the only operation is an enum, which is not a list.

**Comment by Goldmensch** [comment]
> Looks like you are missing braces: `(:queries)` but then you are hitting an enum issue with Postgres. You might need to add the implicit conversion.

I looked into this, but the Micronaut Data Docs say that Micronaut natively supports Enums and I'm not sure what to do to make that work here, would be nice if you could help me.

**Comment by dstepanov** [comment]
I think the docs mean Java enums.

Actually, the correct query that works is `CAST(:operation AS operation) AND query = ANY (:queries)`.
There are a few problems, the query is not recognized as a delete operation because it doesn't start with `DELETE` so it fails...

Also according to the internet, instead of the cast, it should be enough to set it as an object: `@TypeDef(type = DataType.OBJECT) Operation operation` but internally we set the string for enums breaking it.

**Comment by Goldmensch** [comment]
That's quite annoying, i think i need to implement this with the JdbcOperations by hand. But there's 2 suggestions here:
I tested the enum thing with some standard methods of CrudRepository and unfortunately all fail, because Micronaut can't handle the type cast postgres requires. So would be nice if support can added here. The second thing is, to add a @Query parameter that let you define the explict "role" of this query, for example DELETE, SELECT and so one. So that you could run queries like mine here.
