### ISSUE TITLE
JDBC Coroutines Transactions Rollback not working

### ISSUE THREAD

**Issue by ondrej-hrstka** [micronaut-projects/micronaut-data#1402]
### Expected Behavior

When use `@Transactional` annotation on suspended method, which throws an exception, the transaction should rollback.

### Actual Behaviour

The `Application exception overridden by rollback exception` is reported. The `java.lang.IllegalStateException: No value for key [HikariDataSource (HikariPool-1)] bound to thread [io-executor-thread-1]` is reported for the Hikari CP, similar for other CPs. Happens in `TransactionalInterceptor#completeTransactionAfterThrowing`.

In the attached project, this also breaks working tests for non-coroutine approach. It might mess up some internal state.

### Steps To Reproduce

1. In example application run `./gradlew test --tests '*normal*'` which works.
2. Run `./gradlew test --tests '*coroutines*'` which fails
3. Run `./gradlew test`. First 2 tests passes, last 3 not. However, the last one should pass as well.

### Environment Information

- OS: MacOS 12.3
- JDK: 17.0.2 Temurin
- Kotlin: 1.6.10
- Micronaut: 3.4.0, Micronaut Data: 3.3.0 (from BOM)
- DB: H2, Postgres in Testcontantainers behaves the same though

### Example Application

https://github.com/ondrej-hrstka/micronaut-data-coroutines-transactions-error

### Version

3.4.0

**Comment by charlie-harvey** [comment]
I have multiple databases in my application and this problem shows up quite quickly. I don't even need to throw an exception to have `@Transactional` things fail. It can't even find the `Connection` for the transaction.

```kotlin
@Repository(value = "customer-datasource")
@JdbcRepository(dialect = Dialect.MYSQL)
interface CustomerRepository : CoroutineCrudRepository<Customer, UUID>, CoroutineJpaSpecificationExecutor<Customer> {
}

@Repository(value = "customer-datasource")
@JdbcRepository(dialect = Dialect.MYSQL)
interface CustomerProductRepository : CoroutineCrudRepository<CustomerProduct, UUID>, CoroutineJpaSpecificationExecutor<CustomerProduct> {
}

class CustomerService(
    private val customerRepository: CustomerRepository,
    private val customerProductRepository: CustomerProductRepository
) {
    @TransactionalAdvice("customer-datasource")
    @Transactional
    open suspend fun createCustomer(customer: Customer, customerProducts: List<CustomerProduct>): Customer {
        val savedCustomer = customerRepository.save(customer)
        customerProductRepository.saveAll(customerProducts)
        return savedContest
    }
}
```
Nothing! Nothing happens. Just sits there and never returns. I see the query printed out but it never transacts.


#### Force a transaction ####
```kotlin
class CustomerService(
    private val customerRepository: CustomerRepository,
    private val customerProductRepository: CustomerProductRepository
) {
    @TransactionalAdvice("customer-datasource")
    @Transactional
    open suspend fun createCustomer(customer: Customer, customerProducts: List<CustomerProduct>): Customer {
        val savedCustomer = customerRepository.save(customer)
        customerProductRepository.saveAll(customerProducts).toList()  // <<-- Added .toList() to force it to transact
        return savedContest
    }
}
```
Throws this exception:
```
        Caused by:
        io.micronaut.transaction.exceptions.CannotCreateTransactionException: Could not open JDBC Connection for transaction
            at app//io.micronaut.transaction.jdbc.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:238)
            at app//io.micronaut.transaction.support.AbstractSynchronousTransactionManager.getTransaction(AbstractSynchronousTransactionManager.java:440)
            at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.createTransactionIfNecessary(TransactionalInterceptor.java:258)
            at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:157)
            at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
            at app//com.beable.services.$CustomerService$Definition$Intercepted.createCustomer(Unknown Source)
            at app//com.beable.services.CustomerServiceTest$beforeEach$1.invokeSuspend(CustomerServiceTest.kt:55)
            at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
            at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
            at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
            at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
            at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
            at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
            at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
            at app//com.beable.services.CustomerServiceTest.beforeEach(CustomerServiceTest.kt:39)
```


#### Comment out the @Transactional ####
```kotlin
class CustomerService(
    private val customerRepository: CustomerRepository,
    private val customerProductRepository: CustomerProductRepository
) {
    // @TransactionalAdvice("customer-datasource")
    // @Transactional
    open suspend fun createCustomer(customer: Customer, customerProducts: List<CustomerProduct>): Customer {
        val savedCustomer = customerRepository.save(customer)
        customerProductRepository.saveAll(customerProducts)
        return savedContest
    }
}
```
Huzzah! Everything is great now.

Well, unless there is a failure somewhere, then I have no idea what will happen to this transaction. Probably produce the error from @ondrej-hrstka 

Hope this helps a bit in diagnosing. Thanks!

**Comment by dstepanov** [comment]
I will take a look next week.

**Comment by ondrej-hrstka** [comment]
The issue described by @charlie-harvey can be reproduced by following piece of code in my Example Application:
```kotlin
    @Transactional
    open suspend fun storeAndRead(): Record? {
        val id = UUID.randomUUID()
        coroutinesRepository.save(Record(id))
        return coroutinesRepository.findById(id)
    }
```

@dstepanov : Do you want me to add it to the tests in the example app?

**Comment by dstepanov** [comment]
Yes, and please include testcontainers so there is no need to run local db. Thanks!
