### ISSUE TITLE
@Transactional not working when using CoroutineCrudRepository + JDBC

### ISSUE THREAD

**Issue by joshchoo** [micronaut-projects/micronaut-data#1407]
### Expected Behavior

@Transactional should **perform rollbacks** when an Exception is thrown within Coroutines. For example, no database rows should be saved when an exception is thrown in a method wrapped with @Transactional.

**Note**: I've previously reported this issue in #1271, and the issue was thought to be fixed in Pull Request https://github.com/micronaut-projects/micronaut-data/pull/1274. However, I've updated to Micronaut 3.4.0 to test the new changes but they still don't seem to be working as expected.

### Actual Behaviour

When using @Transactional on a suspending function, database rows are still being saved even when an exception is thrown.

# Example based on [linked repo](https://github.com/joshchoo/micronaut-coroutines-transactional-issue)

![image](https://user-images.githubusercontent.com/16533168/160144749-6ac954f1-88c3-4f9b-ba85-9342d4aea576.png)

Transactions are being committed immediately after calling `coroutineRepository.save(...)` although the expected behavior is for the commit to happen only when the function finishes.

https://user-images.githubusercontent.com/16533168/160147162-62d82f98-0d24-4b99-bfd5-372e723a7a27.mov

Logs:

```
22:39:51.031 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Creating new transaction with name [null]: 0,-1,timeout_null
22:39:51.037 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Acquired Connection [HikariProxyConnection@1014650715 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] for JDBC transaction
22:39:51.038 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Switching JDBC Connection [HikariProxyConnection@1014650715 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] to manual commit
22:39:51.038 [io-executor-thread-2] TRACE i.m.t.s.TransactionSynchronizationManager - Bound value [io.micronaut.transaction.jdbc.ConnectionHolder@3afff7ff] for key [HikariDataSource (HikariPool-1)] to thread [io-executor-thread-2]
22:39:51.038 [io-executor-thread-2] TRACE i.m.t.s.TransactionSynchronizationManager - Initializing transaction synchronization
22:39:51.045 [io-executor-thread-2] DEBUG io.micronaut.data.query - Executing SQL query: INSERT INTO "data" ("id") VALUES (?)
22:39:51.045 [io-executor-thread-2] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 41624a94-445a-4264-b16e-da864dcef701 with data type: UUID
22:39:51.053 [io-executor-thread-2] TRACE i.m.t.j.DataSourceTransactionManager - Triggering beforeCommit synchronization
22:39:51.053 [io-executor-thread-2] TRACE i.m.t.j.DataSourceTransactionManager - Triggering beforeCompletion synchronization
22:39:51.053 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Initiating transaction commit
22:39:51.053 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Committing JDBC transaction on Connection [HikariProxyConnection@1014650715 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0]
22:39:51.058 [io-executor-thread-2] TRACE i.m.t.j.DataSourceTransactionManager - Triggering afterCommit synchronization
22:39:51.058 [io-executor-thread-2] TRACE i.m.t.s.TransactionSynchronizationManager - Clearing transaction synchronization
22:39:51.058 [io-executor-thread-2] TRACE i.m.t.j.DataSourceTransactionManager - Triggering afterCompletion synchronization
22:39:51.058 [io-executor-thread-2] TRACE i.m.t.s.TransactionSynchronizationManager - Removed value [io.micronaut.transaction.jdbc.ConnectionHolder@3afff7ff] for key [HikariDataSource (HikariPool-1)] from thread [io-executor-thread-2]
22:39:51.058 [io-executor-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Releasing JDBC Connection [HikariProxyConnection@1014650715 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] after transaction
22:39:51.059 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Creating new transaction with name [null]: 0,-1,timeout_null
22:39:51.059 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Acquired Connection [HikariProxyConnection@1041474523 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] for JDBC transaction
22:39:51.059 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Switching JDBC Connection [HikariProxyConnection@1041474523 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] to manual commit
22:39:51.059 [io-executor-thread-3] TRACE i.m.t.s.TransactionSynchronizationManager - Bound value [io.micronaut.transaction.jdbc.ConnectionHolder@30d45a69] for key [HikariDataSource (HikariPool-1)] to thread [io-executor-thread-3]
22:39:51.059 [io-executor-thread-3] TRACE i.m.t.s.TransactionSynchronizationManager - Initializing transaction synchronization
22:39:51.059 [io-executor-thread-3] DEBUG io.micronaut.data.query - Executing SQL query: INSERT INTO "data" ("id") VALUES (?)
22:39:51.059 [io-executor-thread-3] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 41624a94-445a-4264-b16e-da864dcef701 with data type: UUID
22:39:51.065 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Initiating transaction rollback on application exception
io.micronaut.data.exceptions.DataAccessException: Error executing PERSIST: ERROR: duplicate key value violates unique constraint "data_pkey"
  Detail: Key (id)=(41624a94-445a-4264-b16e-da864dcef701) already exists.
        at io.micronaut.data.runtime.operations.internal.BaseOperations.failed(BaseOperations.java:131)
        at io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:85)
        at io.micronaut.data.runtime.operations.internal.EntityOperations.persist(EntityOperations.java:31)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persist$15(DefaultJdbcRepositoryOperations.java:644)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeWrite$19(DefaultJdbcRepositoryOperations.java:719)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:182)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeWrite(DefaultJdbcRepositoryOperations.java:719)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persist(DefaultJdbcRepositoryOperations.java:641)
        at io.micronaut.data.runtime.operations.ExecutorAsyncOperations.lambda$persist$8(ExecutorAsyncOperations.java:145)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "data_pkey"
  Detail: Key (id)=(41624a94-445a-4264-b16e-da864dcef701) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.execute(DefaultJdbcRepositoryOperations.java:949)
        at io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:81)
        ... 12 common frames omitted
22:39:51.065 [io-executor-thread-3] TRACE i.m.t.j.DataSourceTransactionManager - Triggering beforeCompletion synchronization
22:39:51.065 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Initiating transaction rollback
22:39:51.065 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Rolling back JDBC transaction on Connection [HikariProxyConnection@1041474523 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0]
22:39:51.070 [io-executor-thread-3] TRACE i.m.t.s.TransactionSynchronizationManager - Clearing transaction synchronization
22:39:51.070 [io-executor-thread-3] TRACE i.m.t.j.DataSourceTransactionManager - Triggering afterCompletion synchronization
22:39:51.070 [io-executor-thread-3] TRACE i.m.t.s.TransactionSynchronizationManager - Removed value [io.micronaut.transaction.jdbc.ConnectionHolder@30d45a69] for key [HikariDataSource (HikariPool-1)] from thread [io-executor-thread-3]
22:39:51.070 [io-executor-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Releasing JDBC Connection [HikariProxyConnection@1041474523 wrapping org.postgresql.jdbc.PgConnection@1b6ef4c0] after transaction

```

### Steps To Reproduce

I've reproduced the issue in this repo, and included instructions: https://github.com/joshchoo/micronaut-coroutines-transactional-issue

The example application saves a database entity twice in a @Transactional, which throws a duplicate key value exception.

### Environment Information

- Operating System: MacOS 12.3
- JDK details:
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode)
```

### Version

3.4.0

**Comment by ondrej-hrstka** [comment]
Seems like duplicate to #1402

**Comment by dstepanov** [comment]
Can you please include a test and testcontainers in your sample example? I don't run any DB locally

**Comment by ondrej-hrstka** [comment]
@dstepanov : Thank you very much. Also this piece of code results into freeze. Should I create a new bug or add it to this one?
```kotlin
    @Transactional
    open suspend fun storeAndRead(): Record? {
        val id = UUID.randomUUID()
        coroutinesRepository.save(Record(id))
        return coroutinesRepository.findById(id)
    }
```
