### ISSUE TITLE
repository SAVE method with different entity in argument

### ISSUE THREAD

**Issue by donarus** [micronaut-projects/micronaut-data#1428]
### Expected Behavior

When defined a save method with an argument with type of another mapped entity, it should work.

### Actual Behaviour

```
Error executing PERSIST: Unrecognized path: tenant.id
io.micronaut.data.exceptions.DataAccessException: Error executing PERSIST: Unrecognized path: tenant.id
	at app//io.micronaut.data.runtime.operations.internal.BaseOperations.failed(BaseOperations.java:131)
	at app//io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:85)
	at app//io.micronaut.data.runtime.operations.internal.EntityOperations.persist(EntityOperations.java:31)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persist$15(DefaultJdbcRepositoryOperations.java:644)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeWrite$19(DefaultJdbcRepositoryOperations.java:719)
	at app//io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:182)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeWrite(DefaultJdbcRepositoryOperations.java:719)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persist(DefaultJdbcRepositoryOperations.java:641)
	at app//io.micronaut.data.runtime.intercept.DefaultSaveEntityInterceptor.intercept(DefaultSaveEntityInterceptor.java:45)
	at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:115)
	at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:89)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at cz.ydealcloud.app.api.db.repository.TemplateCategoryRepositoryTest.find by id and tenant(TemplateCategoryRepositoryTest.groovy:49)
Caused by: java.lang.IllegalStateException: Unrecognized path: tenant.id
	at io.micronaut.data.runtime.operations.internal.StoredSqlOperation.setParameters(StoredSqlOperation.java:170)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntityOperations.execute(DefaultJdbcRepositoryOperations.java:948)
	at io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:81)
	... 11 more
```

### Steps To Reproduce

Having two entities

```kotlin
@MappedEntity
data class Tenant(
    @field:Id @GeneratedValue val id: Long?,
    val name: String
)

@MappedEntity
data class TemplateCategory(
    @field:Id @GeneratedValue val id: Long?,
    @Relation(value = Relation.Kind.MANY_TO_ONE) val tenant: Tenant,
    val name: String
)
```

and two repositories

```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
interface TenantRepository : GenericRepository<Tenant, Long> {
    fun save(name: String) : Tenant
}

@JdbcRepository(dialect = Dialect.POSTGRES)
@JoinSpecifications(Join(value = "tenant"))
interface TemplateCategoryRepository : GenericRepository<TemplateCategory, Long> {
    fun save(tenant: Tenant, name: String) : TemplateCategory
}
```

and call

```kotlin
# the following invocation succeeds and tenant is persisted and entity returned
val tenant = tenantRepository.save("sample tenant")

# the following invocation fails 
val category = templateCategoryRepository.save(tenant, "category name")
```

### Version

3.3.0

**Comment by donarus** [comment]
Maybe this is not a bug but and there is a possibility to solve it by somehow annotation. But I was not able to find any valid example. Even more, I was not able to find any example or documentation of different than <T>save(entity: T): T

**Comment by donarus** [comment]
I've just solved it out by using abstract class instead of interface

```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
@JoinSpecifications(Join(value = "tenant"))
abstract class TemplateCategoryRepository : GenericRepository<TemplateCategory, Long> {
    abstract fun save(templateCategory: TemplateCategory) : TemplateCategory
    fun save(tenant: Tenant, name: String, note: String? = null) = save(TemplateCategory(null, null, tenant, name, note))
 }
```

But I'm still unsure it this is the right approach. I still think that my initial approach should work and consider it as a bug

**Comment by dstepanov** [comment]
You can also use a default interface method but you would need to enable some option for Kotlin compiler

**Comment by donarus** [comment]
> You can also use a default interface method but you would need to enable some option for Kotlin compiler

Hi Denis, but is is documented somewhere? If so, I'd suggest to somehow highlight that in the documentation. If not (or if there are any caveats due to which this approach should not be used, I'd also mention this in the documentation).

Now I'm unsure if lack of documentation for this particular case can be considered as a bug or not.

Anyway, could you point me out to some material about the option you mentioned, if such a material exists? 

Thanks

**Comment by dstepanov** [comment]
Yes, Micronaut Core has a mention about it:

> If you use interfaces with default methods add freeCompilerArgs = ["-Xjvm-default=all"] for Micronaut to recognize them.

I will take a look on the issue your reported next week, thanks!

**Comment by donarus** [comment]
Hi Denis.  Oh, thank you for the compiler flag hint. For now, I'm ok with abstract methods for now, but if you'd be able to fix the original issue, I'd be grateful (because of tons of boilerplate code around) :)

**Comment by dstepanov** [comment]
Can you please create a sample project that reproduces the issue?

**Comment by donarus** [comment]
here it is: https://github.com/micronaut-projects/micronaut-data/pull/1432
