### ISSUE TITLE
Repository - delete by mapped entity not working

### ISSUE THREAD

**Issue by donarus** [micronaut-projects/micronaut-data#1429]
### Expected Behavior

The entity fulfilling the given criteria is deleted

### Actual Behaviour

Entity is not deleted and eexception is thrown

```
Entity argument must be an instance of cz.ydealcloud.app.api.db.model.TemplateCategory
java.lang.IllegalArgumentException: Entity argument must be an instance of cz.ydealcloud.app.api.db.model.TemplateCategory
	at io.micronaut.data.runtime.intercept.DefaultDeleteOneInterceptor.intercept(DefaultDeleteOneInterceptor.java:52)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:115)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:89)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at cz.ydealcloud.app.api.db.repository.TemplateCategoryRepositoryTest.deleting category(TemplateCategoryRepositoryTest.groovy:76)
```

### Steps To Reproduce

Having two entities

```kotlin
@MappedEntity
data class Tenant(
    @field:Id @GeneratedValue val id: Long?,
    val name: String
)

@MappedEntity
data class TemplateCategory(
    @field:Id @GeneratedValue val id: Long?,
    @Relation(value = Relation.Kind.MANY_TO_ONE) val tenant: Tenant,
    val name: String
)
```

and a repository

```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
@JoinSpecifications(Join(value = "tenant"))
interface TemplateCategoryRepository : GenericRepository<TemplateCategory, Long> {
    fun delete(category: TemplateCategory)  // works like a charm
    fun deleteByName(name: String)  // works like a charm
    fun deleteById(id: Long)  // works like a charm
    fun deleteByIdAndTenant(name: String)  // throws exception
}

```

### Version

3.3.0

**Comment by donarus** [comment]
Hi @dstepanov I'm not sure if this could be somehow related to https://github.com/micronaut-projects/micronaut-data/issues/1428

Also referred to micronaut-data documentation this should work. The method is also properly generated. It works for other than non-entity parameters. But if one of the parameters is an entity, different than repository base entity, it ends up in the exception mentioned above.

**Comment by donarus** [comment]
@dstepanov simple test provided. I'm not familiar with the micronaut-data project structure, so I've added a test just for a simple scenaruon on top of PostgreSQL
