### ISSUE TITLE
Cannot update documents with Strings as IDs

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-data#1542]
### Expected Behavior

Either of:
- saveAll updates all the documents even if they exists in the database
- updateAll updates all the documents and inserts them if they do not exist
- @MongoUpdateOptions(upsert = true) on saveAll method makes it update even if they exist
- @MongoUpdateOptions(upsert = true) on updateAll makes it create documents if they do not exist

### Actual Behaviour

- saveAll -> duplicate key error
- updateAll -> "not a valid ObjectId representation" error see stacktrace below
- @MongoUpdateOptions(upsert = true) on saveAll -> duplicate key error
- @MongoUpdateOptions(upsert = true) on updateAll -> "not a valid ObjectId...."

```
io.micronaut.configuration.kafka.exceptions.KafkaListenerException: invalid hexadecimal representation of an ObjectId: [c88fb9a5977ca1378c44c5b45000fb2b]
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.handleException(KafkaConsumerProcessor.java:693)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.createConsumerThreadPollLoop(KafkaConsumerProcessor.java:488)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$submitConsumerThread$7(KafkaConsumerProcessor.java:421)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [c88fb9a5977ca1378c44c5b45000fb2b]
	at org.bson.types.ObjectId.parseHexString(ObjectId.java:419)
	at org.bson.types.ObjectId.<init>(ObjectId.java:205)
	at io.micronaut.data.mongodb.operations.MongoUtils.idValue(MongoUtils.java:132)
	at io.micronaut.data.mongodb.operations.MongoUtils.entityIdValue(MongoUtils.java:110)
	at io.micronaut.data.mongodb.operations.MongoUtils.filterByEntityId(MongoUtils.java:152)
	at io.micronaut.data.mongodb.operations.MongoUtils.filterByIdAndVersion(MongoUtils.java:167)
	at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations$5.lambda$collectAutoPopulatedPreviousValues$1(DefaultMongoRepositoryOperations.java:855)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations$5.collectAutoPopulatedPreviousValues(DefaultMongoRepositoryOperations.java:855)
	at io.micronaut.data.runtime.operations.internal.BaseOperations.update(BaseOperations.java:113)
	at io.micronaut.data.runtime.operations.internal.SyncEntitiesOperations.update(SyncEntitiesOperations.java:33)
	at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.lambda$updateAll$14(DefaultMongoRepositoryOperations.java:549)
	at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.withClientSession(DefaultMongoRepositoryOperations.java:761)
	at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.updateAll(DefaultMongoRepositoryOperations.java:539)
	at io.micronaut.data.runtime.intercept.DefaultUpdateAllEntitiesInterceptor.intercept(DefaultUpdateAllEntitiesInterceptor.java:48)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:135)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:98)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at de.rhenus.fl.dpx.shipment.adapter.mongo.shipment.ShipmentRepository$Intercepted.updateAll(Unknown Source)
```

### Example Application

https://github.com/ckosmowski/micronaut-examples/tree/issues/mongodb/stringids

### Version

3.4.4

**Comment by ckosmowski** [comment]
This also applies to calling "deleteAll" it also raises the same Exception.

**Comment by ckosmowski** [comment]
Even if i switch everything to ObjectId "updateAll" will not create a non existing document even with @MicronautUpdateOptions(upsert = true).

**Comment by dstepanov** [comment]
Can you please provide a sample app?

**Comment by ckosmowski** [comment]
Please see: https://github.com/ckosmowski/micronaut-examples/tree/issues/mongodb/stringids

**Comment by ckosmowski** [comment]
Seems like this was not a simple one. Thank you!
