### ISSUE TITLE
ObjectId is not mapped while fetching the record using Micronaut Data MongoDb

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-data#1548]
### Expected Behavior

I have the below entity

```
import org.bson.types.ObjectId;
@MappedEntity
public record Discount(
        @Id
        @GeneratedValue
        ObjectId id,
        @NotNull
        String discountCode,

        // Other properties
)
```

And the repository

```
import org.bson.types.ObjectId;
    @MongoRepository
    public interface IDiscountRepository extends ReactorPageableRepository<Discount, ObjectId> {}
```

when I am saving the record the method returns the ID with the below code

```
public Mono<DiscountModel> create(DiscountModel model) {
    Discount discount = mapPojoToEntity(null, model);
    return this.iDiscountRepository.save(discount).map(item -> mapEntityToPojo(item));
}
```

![image](https://user-images.githubusercontent.com/84489031/170594716-f2edf45b-7062-4c04-8fca-c7c31c0a753b.png)

### Actual Behaviour

Now during retriving the records using below code

`var test = iDiscountRepository.findAll().blockFirst();`

The Id is Null

![image](https://user-images.githubusercontent.com/84489031/170594776-4470ced1-b22f-4996-a20f-cead318c90ac.png)

```
dependencies {
    annotationProcessor("io.micronaut.data:micronaut-data-document-processor:3.4.1")
    implementation("io.micronaut.data:micronaut-data-mongodb:3.4.1")
    runtimeOnly 'org.mongodb:mongodb-driver-reactivestreams:4.6.0'

    implementation "io.micronaut:micronaut-inject:3.5.0"
    annotationProcessor "io.micronaut:micronaut-inject-java:3.5.0"
    annotationProcessor "io.micronaut:micronaut-validation:3.5.0"
    implementation 'io.micronaut:micronaut-validation:3.5.0'
    implementation 'io.micronaut.reactor:micronaut-reactor:2.2.2'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'


    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation 'org.mongodb:mongodb-driver-reactivestreams:4.6.0'
}
```

### Environment Information

- Mac 
- Jdk 17

### Example Application

https://github.com/anandjaisy/MicronautMongoDbPagination

### Version

3.5.0

**Comment by anandjaisy** [comment]
Which release will include this fix?

**Comment by dstepanov** [comment]
Unfortunately, this needed some major changes, so it will be in 3.5.0 in a few weeks

**Comment by anandjaisy** [comment]
> Unfortunately, this needed some major changes, so it will be in 3.5.0 in a few weeks

Is there any workaround on this, I can't change the record to ordinary class. I have lots of records in the project. If I change to ordinary class and again change to records will be lots of work.

**Comment by anandjaisy** [comment]
```
repositories {
    mavenCentral()
    maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
}
```

```
dependencies {
    annotationProcessor("io.micronaut.data:micronaut-data-document-processor:3.5.0-SNAPSHOT")
    implementation("io.micronaut.data:micronaut-data-mongodb:3.5.0-SNAPSHOT")
    runtimeOnly 'org.mongodb:mongodb-driver-reactivestreams:4.6.0'
}
```

I tried the snapshot version, seems like couldn't found

`:infrastructure:test: Could not find io.micronaut.data:micronaut-data-mongodb:3.5.0-SNAPSHOT.`

Can you please let me know what I am missing

**Comment by anandjaisy** [comment]
> You can use the snapshot for now 3.5.0 SNAPSHOT with: repositories { mavenCentral() maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" } }

repositories {
    mavenCentral()
    maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    annotationProcessor("io.micronaut.data:micronaut-data-document-processor:3.5.0-SNAPSHOT")
    implementation("io.micronaut.data:micronaut-data-mongodb:3.5.0-SNAPSHOT")
    runtimeOnly 'org.mongodb:mongodb-driver-reactivestreams:4.6.0'
}
I tried the snapshot version, seems like couldn't found

:infrastructure:test: Could not find io.micronaut.data:micronaut-data-mongodb:3.5.0-SNAPSHOT.

Can you please let me know what I am missing

**Comment by dstepanov** [comment]
I see it here https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/data/

**Comment by anandjaisy** [comment]
> 

With this update I get `IllegalStateException`

```
java.lang.IllegalStateException: This synchronous transaction manager is implemented using blocking of the reactive transaction manager and only supports 'execute', 'executeRead' and 'executeWrite' methods.

	at io.micronaut.transaction.sync.SynchronousFromReactiveTransactionManager.noSupported(SynchronousFromReactiveTransactionManager.java:123)
	at io.micronaut.transaction.sync.SynchronousFromReactiveTransactionManager.getTransaction(SynchronousFromReactiveTransactionManager.java:58)
	at io.micronaut.transaction.test.DefaultTestTransactionExecutionListener.beforeTestExecution(DefaultTestTransactionExecutionListener.java:104)
```

**Comment by dstepanov** [comment]
You need to disable transaction in your test for now @MicronauTest(transactional = false)

**Comment by anandjaisy** [comment]
> You need to disable transaction in your test for now @MicronauTest(transactional = false)

I am still facing the same error with 3.5.0, here is the [repo](https://github.com/anandjaisy/discount)  and if change to class, getting codec registry error. You can run the test over [here](https://github.com/anandjaisy/discount/blob/main/api/src/test/java/fete/bird/functional/GetTest.java) which uses the test container. But facing the same issue, id is not bind can be tested here https://github.com/anandjaisy/discount/blob/main/core/src/main/java/fete/bird/service/DiscountService.java#L15

**Comment by dstepanov** [comment]
Sorry, there is one new option that is needed now:
```
mongodb:
  package-names: fete.bird
```
