### ISSUE TITLE
R2DBC Transactions are not found when using Kotlin

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-data#1579]
### Expected Behavior

I have created `Repositories` that extend `CoroutineCrudRepository` and have added necessary annotations:

```Kotlin
@TransactionalAdvice("accounts-datasource")
@R2dbcRepository(value = "accounts-datasource", dialect = Dialect.MYSQL)
interface UserAccountRepository : CoroutineCrudRepository<UserAccount, OptimizedUUID>,
    CoroutineJpaSpecificationExecutor<UserAccount> {
}
```

I have put the necessary annotations on my `Repository` interfaces to mandate transactions:
```Kotlin
@Transactional(Transactional.TxType.MANDATORY)
```

I have annotated `Service` calls with the proper annotations:
```Kotlin
    @Transactional
    @TransactionalAdvice("accounts-datasource")
    open suspend fun deleteByUsernameAndSiteId(username: String, siteId: Int) {
        userAccountRepository.deleteByUsernameAndSiteId(username, siteId)
    }
```

It _should_ save data to the database.

### Actual Behaviour

But the transaction is never found in the context. Like it doesn't exist.
```
        Caused by:
        io.micronaut.transaction.exceptions.NoTransactionException: Expected an existing transaction, but none was found in the Reactive context.
            at app//io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$withTransaction$13(DefaultR2dbcRepositoryOperations.java:364)
            at app//reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
            at app//reactor.core.publisher.Mono.subscribe(Mono.java:4400)
            at app//io.micronaut.data.runtime.operations.AsyncFromReactiveAsyncRepositoryOperation.toCompletionStage(AsyncFromReactiveAsyncRepositoryOperation.java:199)
            at app//io.micronaut.data.runtime.operations.AsyncFromReactiveAsyncRepositoryOperation.executeDelete(AsyncFromReactiveAsyncRepositoryOperation.java:144)
            at app//io.micronaut.data.runtime.intercept.async.DefaultDeleteAllAsyncInterceptor.intercept(DefaultDeleteAllAsyncInterceptor.java:53)
            at app//io.micronaut.data.runtime.intercept.async.DefaultDeleteAllAsyncInterceptor.intercept(DefaultDeleteAllAsyncInterceptor.java:36)
            at app//io.micronaut.data.intercept.DataIntroductionAdvice.lambda$interceptKotlinSuspend$0(DataIntroductionAdvice.java:155)
            at app//io.micronaut.transaction.support.TransactionSynchronizationManager.withState(TransactionSynchronizationManager.java:634)
            at app//io.micronaut.data.intercept.DataIntroductionAdvice.interceptKotlinSuspend(DataIntroductionAdvice.java:154)
            at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:130)
            at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:98)
            at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
            at app//io.micronaut.aop.internal.intercepted.KotlinInterceptedMethod.interceptResultAsCompletionStage(KotlinInterceptedMethod.java:105)
            at app//io.micronaut.aop.internal.intercepted.KotlinInterceptedMethod.interceptResult(KotlinInterceptedMethod.java:127)
            at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:155)
            at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
            at app//com.example.account.repositories.UserAccountRepository$Intercepted.deleteByUsernameAndSiteId(Unknown Source)
            at app//com.example.account.service.UserAccountService.deleteByUsernameAndSiteId$suspendImpl(UserAccountService.kt:78)
            at app//com.example.account.service.UserAccountService.deleteByUsernameAndSiteId(UserAccountService.kt)
            at app//com.example.account.service.$UserAccountService$Definition$Intercepted.$$access$$deleteByUsernameAndSiteId(Unknown Source)
            at app//com.example.account.service.$UserAccountService$Definition$Exec.dispatch(Unknown Source)
````

### Steps To Reproduce

Checkout this repository: https://github.com/charlie-harvey/micronaut-kotlintransactions
Run tests:
```
./gradlew build
```

### Environment Information

MacOS
Java 11

### Example Application

https://github.com/charlie-harvey/micronaut-kotlintransactions

### Version

3.5.1

**Comment by charlie-harvey** [comment]
I made all the changes but I am still getting the error. Its not making errors all over the place like before, but still not finding a transaction.

```
com.example.account.service.UserAccountServiceTest > findByUsername FAILED
    io.micronaut.transaction.exceptions.NoTransactionException: Expected an existing transaction, but none was found in the Reactive context.
        at app//io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$withTransaction$13(DefaultR2dbcRepositoryOperations.java:382)
        at app//reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at app//reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at app//reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
        at app//reactor.core.publisher.Mono.toFuture(Mono.java:4920)
        at app//io.micronaut.transaction.async.AsyncUsingReactiveTransactionOperations.lambda$withTransaction$5(AsyncUsingReactiveTransactionOperations.java:93)
        at app//io.micronaut.transaction.support.TransactionSynchronizationManager.withState(TransactionSynchronizationManager.java:637)
        at app//io.micronaut.transaction.support.TransactionSynchronizationManager.withGuardedState(TransactionSynchronizationManager.java:653)
        at app//io.micronaut.transaction.async.AsyncUsingReactiveTransactionOperations.withTransaction(AsyncUsingReactiveTransactionOperations.java:64)
        at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:138)
        at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at app//com.example.account.repositories.UserAccountRepository$Intercepted.save(Unknown Source)
        at app//com.example.account.service.UserAccountServiceTest.findByUsername(UserAccountServiceTest.kt:53)

        Caused by:
        io.micronaut.transaction.exceptions.NoTransactionException: Expected an existing transaction, but none was found in the Reactive context.
            at app//io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$withTransaction$13(DefaultR2dbcRepositoryOperations.java:382
```

**Comment by dstepanov** [comment]
That's because `findByUsername` doesn't have a transaction so the inner call to `save` fails.

**Comment by charlie-harvey** [comment]
Putting the annotations on the test function did not do the trick.
```Kotlin
    @Transactional
    @TransactionalAdvice("accounts-datasource")
    @Test
    open suspend fun findByUsername() {
        val ua = userAccountEntityArb(
            siteId = validUserAccount.siteId,
            tobedeleted = false,
            active = true,
            username = "pants"
        ).next()
        userAccountRepository.save(ua)

        userAccountService.findBySiteIdAndUsername(
            siteId = validUserAccount.siteId,
            username = "pants"
        ).shouldBe(ua)

        userAccountService.deleteByUsernameAndSiteId(ua.username, ua.siteId)
    }
```

Same exact error as above. Do I need annotations in different places? Do I need to create a transaction somewhere/somehow?

**Comment by charlie-harvey** [comment]
That did it. Removed all `@Transactional` annotations from the tests. Added a new method in the service. Called the service instead of the repository directly.
All good.

Thanks so much.

**Comment by charlie-harvey** [comment]
I think I want to reopen this one. I'm not sure what I did 2 weeks ago to make it work but I sure can't get it working anymore. I created a new repo from scratch and tried again.

What happens now when I build/test is it just stalls. Connection or transaction is never found and the test just waits - for hours if I don't cut it off.

https://github.com/charlie-harvey/micronaut-kotlintransactions-2

**Comment by charlie-harvey** [comment]
Thanks again! I really appreciate all this work. Also confirms my suspicions that I should continue working with Coroutines and never go anywhere near Reactive programming. :)

**Comment by dstepanov** [comment]
Coroutines work nicely with reactive stuff. All those problems are related to a combination of all technologies together. We need a better API to propagate the context across Reactor, Kotlin - sync Java.

**Comment by charlie-harvey** [comment]
Back for more!

https://github.com/charlie-harvey/micronaut-kotlintransactions-2

I updated the `application.yml` and `application-test.yml` to give the datasource a name: `account-datasource`

```yml
r2dbc:
  datasources:
    # default:
    accounts-datasource:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/accounts
      username: accounts
      password: secret
```

```kotlin
const val ACCOUNTS_DATASOURCE = "accounts-datasource"
// const val ACCOUNTS_DATASOURCE = "default"
```

```kotlin
@TransactionalAdvice(ACCOUNTS_DATASOURCE)
@R2dbcRepository(value = ACCOUNTS_DATASOURCE, dialect = Dialect.MYSQL)
interface UserAccountRepository : CoroutineCrudRepository<UserAccount, OptimizedUUID>,
    CoroutineJpaSpecificationExecutor<UserAccount> {
```

Now it can't find transactions again.

```
            Caused by:
            io.micronaut.context.exceptions.ConfigurationException: No reactive transaction management has been configured. Ensure you have correctly configured a async capable transaction manager
                at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.lambda$intercept$0(TransactionalInterceptor.java:111)
                at java.base@11.0.15/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
                at app//io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:95)
                at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
                at app//com.example.account.service.$UserAccountService$Definition$Intercepted.deleteByUsernameAndSiteId(Unknown Source)
                at app//com.example.account.service.UserAccountServiceTest$beforeEach$1.invokeSuspend(UserAccountServiceTest.kt:28)
                at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at app//com.example.account.service.UserAccountServiceTest.beforeEach(UserAccountServiceTest.kt:24)
```

**Comment by dstepanov** [comment]
@charlie-harvey Your test passes for me

**Comment by charlie-harvey** [comment]
I just tried again and it works. No changes. Unreal. That's a good thing though. Thanks for taking a look.

**Comment by lucasgust** [comment]
@dstepanov sorry to "relive" this issue, but I'm also working on a project that uses Kotlin + R2DBC + Coroutines and I'm experiencing similar difficulties that it's driving me crazy. my code is almost the same [example](https://github.com/charlie-harvey/micronaut-kotlintransactions-2) provided by @charlie-harvey.

in my project I exposed an simple API that inserts random data into a table and then calls an external service (for now I'm just mocking response) to save the response into another table. this block needs to be executed inside a transaction (one entry in each table or nothing). to simulate rollback, I'm throwing an exception in my "external service" every 5 times

most of the time it is working successfully, data is being inserted or being rolled back in exception cases, but randomly there are times that the application starts silently "bugged", that is, one of these two errors is thrown everytime API is called:
- `io.micronaut.transaction.exceptions.NoTransactionException: Expected an existing transaction, but none was found in the Reactive context.`
- or `java.lang.IllegalStateException: This synchronous transaction manager is implemented using blocking of the reactive transaction manager and only supports 'execute', 'executeRead' and 'executeWrite' methods.`

...so I just restart application a couple of times (**without making any changes**) until it starts to work again

should I open this issue?
