### ISSUE TITLE
ON CONFLICT DO UPDATE with WHERE

### ISSUE THREAD

**Issue by AidarKhusainov** [micronaut-projects/micronaut-data#1599]
### Expected Behavior

If the row being updated is filtered in the where clause, then an error occurs:

`Caused by: io.micronaut.data.exceptions.DataAccessException: Failed to generate ID for entity: TokenEntity(id=null, tokenCatalogue=TokenCatalogueEntity(id=1, address=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c, name=wbnb, symbol=wbnb, logoURI=https://s2.coinmarketcap.com/static/img/coins/64x64/7192.png, createDate=2022-06-29T18:48:58.366101), address=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c, name=wbnb, symbol=wbnb, logoURI=https://s2.coinmarketcap.com/static/img/coins/64x64/7192.png, status=NORMAL, isExclusionList=false, createDate=2022-06-30T12:30:06.000424)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcEntitiesOperations.execute(DefaultJdbcRepositoryOperations.java:1041)
	at io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:81)`

`
@Query(value =
	"INSERT INTO token(id, token_catalogue_id, address, name, symbol, logo_uri, status, is_exclusion_list) " +
	"VALUES ((SELECT nextval('token_id_seq')), :tokenCatalogue, lower(:address), :name, :symbol, :logoURI, :status, :isExclusionList) " +
	"ON CONFLICT (address) DO UPDATE SET token_catalogue_id = coalesce(:tokenCatalogue, token.token_catalogue_id), " +
	"                                    name               = coalesce(:name, token.name), " +
	"                                    symbol             = coalesce(:symbol, token.symbol), " +
	"                                    logo_uri           = coalesce(:logoURI, token.logo_uri), " +
	"                                    status             = coalesce(:status, token.status), " +
	"                                    is_exclusion_list  = coalesce(:isExclusionList, token.is_exclusion_list), " +
	"                                    create_date        = now() " +
	"WHERE token.status <> 'BASIC'")
void insertOrUpdate(final Iterable<TokenEntity> tokens);
`

### Actual Behaviour

The row was expected to neither be inserted nor updated.

### Version

3.3.0

**Comment by dstepanov** [comment]
There is not enough info on what is wrong. I would need to see at least the stack trace. The best would be a project with a reproducer.

**Comment by AidarKhusainov** [comment]
`io.micronaut.data.exceptions.DataAccessException: Error executing PERSIST: Failed to generate ID for entity: TokenEntity(id=null, tokenCatalogue=TokenCatalogueEntity(id=1, address=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c, name=wbnb, symbol=wbnb, logoURI=https://s2.coinmarketcap.com/static/img/coins/64x64/7192.png, createDate=2022-06-29T18:48:58.366101), address=0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c, name=wbnb, symbol=wbnb, logoURI=https://s2.coinmarketcap.com/static/img/coins/64x64/7192.png, status=NORMAL, isExclusionList=false, createDate=2022-06-30T12:30:06.000424)
	at io.micronaut.data.runtime.operations.internal.BaseOperations.failed(BaseOperations.java:131)
	at io.micronaut.data.runtime.operations.internal.BaseOperations.persist(BaseOperations.java:85)
	at io.micronaut.data.runtime.operations.internal.SyncEntitiesOperations.persist(SyncEntitiesOperations.java:33)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persistAll$17(DefaultJdbcRepositoryOperations.java:696)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeWrite$19(DefaultJdbcRepositoryOperations.java:719)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:182)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeWrite(DefaultJdbcRepositoryOperations.java:719)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persistAll(DefaultJdbcRepositoryOperations.java:679)
	at io.micronaut.data.runtime.intercept.DefaultSaveAllInterceptor.intercept(DefaultSaveAllInterceptor.java:46)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:115)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:89)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)`

**Comment by AidarKhusainov** [comment]
If the on conflict block is executed for a row, this row must be updated. But since the where condition filters this row, nothing should happen. 
Instead, an error is thrown.

**Comment by dstepanov** [comment]
Try to add at the end `RETURNING id`

**Comment by AidarKhusainov** [comment]
Same error

**Comment by dstepanov** [comment]
It's because each entity has the id marked as generated and is expected to receive it by executing the insert, and by adding a condition the response is fewer ids than entities, breaking the logic.

I want to introduce a new way to do execute-return which might be a solution to this problem.

**Comment by AidarKhusainov** [comment]
Спасибо, Денис! :)
I'll be waiting

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
