### ISSUE TITLE
"Could not obtain transaction" after micronaut upgrade

### ISSUE THREAD

**Issue by davidgiga1993** [micronaut-projects/micronaut-data#1602]
### Expected Behavior

Using repositories with custom queries (using the `EntityManager`) should work.

The app worked with micronaut `3.3.0` and they fail with `3.5.2`

### Actual Behaviour

When calling a repository method which uses an injected entity manager with custom query the repository throws an exception:

```
Could not obtain transaction-synchronized Session for current thread
org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread
	at app//io.micronaut.transaction.hibernate5.MicronautSessionContext.currentSession(MicronautSessionContext.java:91)
	at app//org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:508)
	at app//io.micronaut.configuration.hibernate.jpa.TransactionalSessionInterceptor.intercept(TransactionalSessionInterceptor.java:62)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted.createQuery(Unknown Source)
	at app//com.siemens.imagescanner.dao.billing.ScanHistoryRepository.findSumInRange(ScanHistoryRepository.java:36)
```

### Steps To Reproduce

My super minimal example worked, however all existing tests failed so something is definitely broken. Here are the snippets of the associated classes:

```java

@Repository
public abstract class ScanHistoryRepository implements PageableRepository<ScanHistory, Integer>
{
	private final EntityManager entityManager;

	public ScanHistoryRepository(EntityManager entityManager)
	{
		this.entityManager = entityManager;
	}

	public long findSumInRange(AppUser user, Date start, Date end)
	{
		return entityManager.createQuery("SELECT COUNT(A) FROM ScanHistory A WHERE A.user = :user AND " +
						"A.date >= :start AND A.date <= :end", Long.class)
				.setParameter("user", user)
				.setParameter("start", start)
				.setParameter("end", end)
				.getSingleResult();
	}
}
```

The following shows the test case, all other repositories use auto-generated queries from micronaut-data, only the last `findSumInRange` uses a custom query.

```java
@MicronautTest
class ImageJobSchedulerTest
{
	@Inject
	ImageJobScheduler scheduler;

	@Inject
	MessageBus messageBus;

	@Inject
	ScannerJobRepository scannerJobRepository;

	@Inject
	ScanHistoryRepository historyRepository;


	@MockBean(MessageBus.class)
	public MessageBus dependency()
	{
		return mock(MessageBus.class);
	}

	@Test
	public void createJobForImage() throws IOException
	{
		scheduler.registryClient = mock(OwnDockerRegistryClient.class);

		var images = new ArrayList<String>();
		images.add("group/project/image");

		var tags = new ArrayList<String>();
		tags.add("latest");

		var manifest = new Manifest();
		var manifestContainer = new ManifestContainer("sha256:123123", manifest);

		when(scheduler.registryClient.getCatalog(anyInt(), any())).thenReturn(images);
		when(scheduler.registryClient.getTags("group/project/image")).thenReturn(tags);
		when(scheduler.registryClient.getDigest("group/project/image", "latest")).thenReturn(manifestContainer);

		scheduler.checkForLocalImages();

		var captor = ArgumentCaptor.forClass(ImageScanJobDto.class);
		verify(messageBus, atLeastOnce()).submitJob(captor.capture());

		for (ImageScanJobDto jobDto : captor.getAllValues())
		{
			assertEquals("group/project/image", jobDto.image.imageName);
			assertEquals("latest", jobDto.image.tag);

			var job = scannerJobRepository.findById((int) jobDto.jobId);
			assertTrue(job.isPresent(), jobDto.scannerType + " " + jobDto.jobId);

			var jobGroup = job.get().getParent().getProject().getGroup();

			//  This next call failes with the exception above
			assertEquals(1, historyRepository.findSumInRange(jobGroup, new Date(), new Date()));
		}
	}
}
```

Note: Although this is a test, the Exception also gets thrown when the repository is called during the regular micronat runtime.

### Environment Information

- OS: Windows 10
- Adoptium JDK 17

### Version

3.5.2

**Comment by davidgiga1993** [comment]
I also found the related issue at #1583 however I don't see a final solution there

**Comment by dstepanov** [comment]
Can you please try Micronaut Data 3.4.3? If it doesn't work please create a project with a reproducer

**Comment by davidgiga1993** [comment]
Just tried it with `io.micronaut.data:micronaut-data-hibernate-jpa:3.4.3`, same results.
I'll try to build a demo project but it might take time since it does work with a very minimal query. Not sure what exactly triggers the condition

**Comment by davidgiga1993** [comment]
@dstepanov I could reproduce it here: https://github.com/davidgiga1993/micronaut-data-issue

```
14:07:54.860 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
14:07:55.312 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
14:07:55.326 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.6.9.Final
14:07:55.688 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
14:07:55.981 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
14:07:56.997 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Could not obtain transaction-synchronized Session for current thread
org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread
	at io.micronaut.transaction.hibernate5.MicronautSessionContext.currentSession(MicronautSessionContext.java:91)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:508)
	at io.micronaut.configuration.hibernate.jpa.TransactionalSessionInterceptor.intercept(TransactionalSessionInterceptor.java:62)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.configuration.hibernate.jpa.TransactionalSession$Intercepted.createQuery(Unknown Source)
	at com.example.ScanHistoryRepository.findSumInRange(ScanHistoryRepository.java:23)
	at com.example.Start.onApplicationEvent(Start.java:23)
	at com.example.Start.onApplicationEvent(Start.java:13)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1682)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:354)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:190)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:306)
	at com.example.Application.main(Application.java:9)

Process finished with exit code 1
```

**Comment by dstepanov** [comment]
I get the same error with Micronaut Data 3.3.0 even 3.2.0

**Comment by davidgiga1993** [comment]
Yep you're right, it never works in the sample, using `findById` works (maybe the state gets changed in the main app before this code gets executed?). 
But using the `EntityManager` like that should work, or? It's pretty much the minimal example from https://micronaut-projects.github.io/micronaut-data/latest/guide/#repositories.

The same behavior appears when using it from a test case:
```java
@MicronautTest
class DemoTest
{
	@Inject
	private ScanHistoryRepository test;

	@Test
	void testItWorks()
	{
        var result = test.findById(0);
        assertTrue(result.isEmpty());
		test.findSumInRange(new Date(), new Date());
	}
}
```

**Comment by astsiatsko** [comment]
Hey guys. Micronaut 4.7.6 and all libs are of versions 4.11.2. The same issue, absolutely unfixable for now, I spent much time on it, adding @Transactional does not work at all. I started debug micronaut internals and getting frustrated. It seems it does not work with EntityManager at all. Any idea how to fix that?
