### ISSUE TITLE
Micronaut GraalVM Data JDBC H2 app fails with GraalVM 22.2

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#1663]
### Issue description

https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768788003

```
atal error: 
[91](/2768788003#L91)java.lang.IllegalAccessError: class io.micronaut.buffer.netty.NettyFeature (in unnamed module @0x4af12a63) cannot access class com.oracle.svm.core.jdk.SystemPropertiesSupport (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @0x4af12a63
[92](/2768788003#L92)	at io.micronaut.buffer.netty.NettyFeature.beforeAnalysis(NettyFeature.java:66)
[93](/2768788003#L93)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
[94](/2768788003#L94)------------------------------------------------------------------------------------------------------------------------	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
[95](/2768788003#L95)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
[96](/2768788003#L96)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
[97](/2768788003#L97)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
[98](2768788003#L98)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
[99](/2768788003#L99)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
[100](/2768788003#L100)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by graemerocher** [comment]
this is not related to h2 or data, it is a problem with the Gradle or Maven plugins /cc @melix @alvarosanchez

**Comment by alvarosanchez** [comment]
I suppose this is the same as https://github.com/micronaut-projects/micronaut-core/issues/7738#issuecomment-1195179005

**Comment by melix** [comment]
Yes, and weirdly the build passes when I run locally.

**Comment by sdelamo** [comment]
This appears to be solved

**Comment by hussain-saif** [comment]
Guys, am still having the same issues, can anyOne help. I am using windows machine , with mvn plugin. Thanks

```
========================================================================================================================
[1/7] Initializing...                                                                                   (17.7s @ 0.14GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: cl.exe (microsoft, x64, 19.29.30146)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - io.micronaut.buffer.netty.NettyFeature
 - io.micronaut.core.graal.ServiceLoaderFeature
 - io.micronaut.http.netty.graal.HttpNettyFeature
 - io.micronaut.jackson.JacksonDatabindFeature

Fatal error: java.lang.IllegalAccessError: class io.micronaut.buffer.netty.NettyFeature (in unnamed module @0x6537ac) cannot access class com.oracle.svm.core.jdk.SystemPropertiesSupport (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @0x6537ac
        at io.micronaut.buffer.netty.NettyFeature.beforeAnalysis(NettyFeature.java:66)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                         0.8s (4.2% of total time) in 9 GCs | Peak RSS: 0.73GB | CPU load: 2.10
========================================================================================================================
```

**Comment by victordfb** [comment]
Same problem here...

**Comment by alvarosanchez** [comment]
For Maven, the workaround today (Micronaut 3.5.x) is to add the following configuration for `org.graalvm.buildtools:native-maven-plugin`:

```xml
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <configuration>
        <environment>
            <USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM>false</USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM>
        </environment>
    </configuration>
</plugin>
```

This will be done automatically via the parent POM in Micronaut 3.6 (due in a few days).

**Comment by kristofdho** [comment]
I just want to point out that `USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM` is a temporary workaround, and will be removed in a future GraalVM version (as per release notes: https://www.graalvm.org/release-notes/22_2/#native-image)
