### ISSUE TITLE
io.micronaut.data.model.Page serilization and deserialization not working with reference to io.micronaut.serde:micronaut-serde-jackson:1.2.0

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-data#1669]
### Expected Behavior

When using the Micronaut serialization 

`io.micronaut.serde:micronaut-serde-jackson:1.2.0`

The Page model from `io.micronaut.data.model.Page` should return the value from the controller response

This error is due to the reference below in `io.micronaut.data.model.Page` which has a dependency on jackson

```
@JsonIgnoreProperties(ignoreUnknown = true)
@TypeHint(Page.class)
@JsonDeserialize(as = DefaultPage.class)
```

Setting below code in the Gradle also not working

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
            .using(module("io.micronaut.serde:micronaut-serde-jackson:1.2.0"))
    }
}
```

### Actual Behaviour

Throws an exception 

```
Error decoding HTTP response body: No bean introspection available for type [interface io.micronaut.data.model.Page]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: No bean introspection available for type [interface io.micronaut.data.model.Page]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeNormalBodyParseError(DefaultHttpClient.java:3353)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:3292)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.buildResponse(DefaultHttpClient.java:3200)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$BaseHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:3175)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:3238)
	at app//io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:3200)
	at app//io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:49)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockFirst(Flux.java:2600)
		at io.micronaut.http.client.netty.DefaultHttpClient$3.exchange(DefaultHttpClient.java:617)
		at io.micronaut.http.client.BlockingHttpClient.exchange(BlockingHttpClient.java:77)
		at io.micronaut.http.client.BlockingHttpClient.exchange(BlockingHttpClient.java:106)
		at fete.bird.functional.GetTest.shouldGetTheListOfDiscounts(GetTest.java:31)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [interface io.micronaut.data.model.Page]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at app//io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:117)
	at java.base@17.0.2/java.util.Optional.orElseThrow(Optional.java:403)
	at app//io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:117)
	at app//io.micronaut.serde.support.DefaultSerdeIntrospections.lambda$getDeserializableIntrospection$1(DefaultSerdeIntrospections.java:146)
	at java.base@17.0.2/java.util.Optional.orElseGet(Optional.java:364)
	at app//io.micronaut.serde.support.DefaultSerdeIntrospections.getDeserializableIntrospection(DefaultSerdeIntrospections.java:137)
	at app//io.micronaut.serde.support.deserializers.ObjectDeserializer.createDeserBean(ObjectDeserializer.java:83)
	at app//io.micronaut.serde.support.deserializers.ObjectDeserializer.getDeserializableBean(ObjectDeserializer.java:75)
	at app//io.micronaut.serde.support.deserializers.ObjectDeserializer.createSpecific(ObjectDeserializer.java:61)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue0(JacksonJsonMapper.java:122)
	at app//io.micronaut.serde.jackson.JacksonJsonMapper.readValue(JacksonJsonMapper.java:116)

```

### Steps To Reproduce

1. Put the reference of `io.micronaut.serde:micronaut-serde-jackson:1.2.0` and don't put any reference of Jackson

### Environment Information

- Mac os M1 2022
- JDK 17 oracle open source

### Version

Micronaut 3.5.4

**Comment by anandjaisy** [comment]
Setting below works

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("io.micronaut:micronaut-jackson-databind"))
                .using(module("io.micronaut.serde:micronaut-serde-jackson:1.2.0"))
    }
}
```

and don't add any dependency of `io.micronaut.serde:micronaut-serde-jackson` below


```
dependencies {
    //.....
}
```
