### ISSUE TITLE
Error on startup after setting LOG_QUERIES_SLOWER_THAN_MS property

### ISSUE THREAD

**Issue by aliiabdii** [micronaut-projects/micronaut-data#1752]
### Expected Behavior

The app should continue to run normally, and then later on Hibernate will issue a log if a query exceeds the specified time.

### Actual Behaviour

The application startup fails with the following error: `Could not determine how to handle configuration value [name=hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS, value=500(java.lang.Integer)] as long`

Here's the full stack trace:
```Message: Could not determine how to handle configuration value [name=hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS, value=500(java.lang.Integer)] as long
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.SessionFactory]

Path Taken: new HibernateJpaOperations(SessionFactory sessionFactory,TransactionOperations transactionOperations,ExecutorService executorService,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService dataConversionService) --> new HibernateJpaOperations(SessionFactory sessionFactory,[TransactionOperations transactionOperations],ExecutorService executorService,RuntimeEntityRegistry runtimeEntityRegistry,DataConversionService dataConversionService) --> new HibernateTransactionManager([SessionFactory sessionFactory],DataSource dataSource,Interceptor entityInterceptor) --> SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2352)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2290)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2236)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3001)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2903)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2864)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2785)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1602)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2339)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2290)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2236)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3001)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2903)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2864)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2785)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1602)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.transaction.hibernate5.$HibernateTransactionManager$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:769)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:158)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2339)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2290)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2236)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3001)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2903)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2864)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2785)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1665)
	at io.micronaut.context.BeanDefinitionDelegate.getParametersValues(BeanDefinitionDelegate.java:195)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:157)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2339)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2290)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2236)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3001)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2903)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2722)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1900)
	... 7 common frames omitted
Caused by: org.hibernate.internal.util.config.ConfigurationException: Could not determine how to handle configuration value [name=hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS, value=500(java.lang.Integer)] as long
	at org.hibernate.internal.util.config.ConfigurationHelper.getLong(ConfigurationHelper.java:231)
Caused by: org.hibernate.internal.util.config.ConfigurationException: Could not determine how to handle configuration value [name=hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS, value=500(java.lang.Integer)] as long

	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:59)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:107)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.model.relational.Database.determineDialect(Database.java:65)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:49)
	at org.hibernate.boot.model.relational.Database.<init>(Database.java:42)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:184)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactoryBuilder(EntityManagerFactoryBean.java:188)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2339)
	... 54 common frames omitted
```

### Steps To Reproduce

Environment:
```
plugins {
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.micronaut.application") version "3.5.3"
}

boilerplate {
    javaVersionCompatibility {
        sourceCompatibility = JavaVersion.VERSION_16
        targetCompatibility = JavaVersion.VERSION_16
    }
}

dependencies {
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut:micronaut-http-validation")
    implementation("io.micronaut:micronaut-runtime")
    implementation("javax.annotation:javax.annotation-api")
    implementation("io.micronaut:micronaut-http-client")

    // JPA, databases and Hibernate
    annotationProcessor("io.micronaut.data:micronaut-data-processor")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.postgresql:postgresql:42.5.0")
    testImplementation(platform("org.testcontainers:testcontainers-bom:1.17.3"))
    testRuntimeOnly("org.testcontainers:postgresql")
    implementation("com.vladmihalcea:hibernate-types-52:2.19.2")

   // more dependencies to follow
}
```

Configuration:
```
jpa:
  default:
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 500
        generate_statistics: false
        show_sql: false
        hbm2ddl:
          auto: update
```

I also tried with `500L` but then it capture it as a String. But for instance, something like `${random.long}` which is a guaranteed `Long` works fine. 

### Environment Information

- JDK Version: 16.0.1
- micronaut-data:3.4.3
- micronaut-core:3.5.5

### Version

3.4.3

**Comment by aliiabdii** [comment]
@radovanradic  Ah, yes. Thank you. That makes sense considering the implementation.
I will close the issue.
