### ISSUE TITLE
'Could not open JDBC Connection for transaction' when parallel threads are used

### ISSUE THREAD

**Issue by StefanSrf** [micronaut-projects/micronaut-data#1763]
### Expected Behavior

The application should work normally.

### Actual Behaviour

Since micronaut 3.6 and micronaut-data-jdbc 3.5 the following issue exists:
A race-condition is present when parallel threads are used for database interaction. The following exception is thrown when using project-reactor with Mono.zip:

[io-executor-thread-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Could not open JDBC Connection for transaction
io.micronaut.transaction.exceptions.CannotCreateTransactionException: Could not open JDBC Connection for transaction
	at io.micronaut.transaction.jdbc.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:242)
	at io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.getTransaction(AbstractSynchronousStateTransactionManager.java:422)
	at io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.execute(AbstractSynchronousStateTransactionManager.java:142)
	at io.micronaut.transaction.support.AbstractSynchronousStateTransactionManager.executeRead(AbstractSynchronousStateTransactionManager.java:160)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:150)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:689)
...
Caused by: java.lang.IllegalStateException: Already value [io.micronaut.transaction.jdbc.ConnectionHolder@793ebe2d] for key [HikariDataSource (HikariPool-1)] bound to thread [io-executor-thread-2]

### Steps To Reproduce

```
demoRepository.findById(1L)
    .doOnNext { logger.info("after first db interaction") }
    // if no previous transaction was running, the race-condition does not appear
    // e.g. if processing would start here with: Mono.just("")
    .flatMap {
        Mono.zip(
            demoRepository.findById(1L).map { logger.info("after db invocation 1") },
            demoRepository.findById(1L).map { logger.info("after db invocation 2") },
        )
    }
```
See also example application which contains a test to reproduce the issue

### Environment Information

- Ubuntu
- JDK 17

### Example Application

https://github.com/StefanSrf/micronaut-connectionissue

### Version

>= 3.6

**Comment by zhangandyhui** [comment]
+1

**Comment by rehnarama** [comment]
Also noticing that this happens with DB access triggered by a micronaut-kafka consumer

**Comment by graemerocher** [comment]
@dstepanov can you take a look?

**Comment by Discordia** [comment]
Bumping this as this is hindering us from updating our services to 3.7.x, today we are at 3.4.x. @graemerocher @dstepanov
