### ISSUE TITLE
Mongo DB API's not working with GraalVM image

### ISSUE THREAD

**Issue by nikhmalh** [micronaut-projects/micronaut-data#1769]
### Expected Behavior

We are using the Micronaut mongo DB module to connect to Oracle ATP.
When we upgraded the versions of Micronaut core to 3.7.0 and Micronaut-data to 3.8.0, Mongo queries stopped working with GraalVM image. 
We are getting this error now:
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.security.rules.IpPatternsRule - One or more of the IP patterns matched the host address [10.244.0.0]. Continuing request processing.
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.s.rules.AbstractSecurityRule - The given roles [[isAnonymous(), isAuthenticated()]] matched one or more of the required roles [[isAuthenticated()]]. Allowing the request
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.security.filters.SecurityFilter - Authorized request POST /backup/user/api/v1/devices. The rule provider io.micronaut.security.rules.SecuredAnnotationRule authorized the request.
08:26:21.742 [io-executor-thread-2] INFO  org.mongodb.driver.cluster - Cluster created with id ClusterId{value='6334052d8047ce403b1f8645', description='oracle-ee-backupservice-atpmongo'} and settings {hosts=[g5c84ba3e53cd0f-db202204221219.adb.us-ashburn-1.oraclecloudapps.com:27017], mode=LOAD_BALANCED, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
08:26:21.743 [io-executor-thread-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]
Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]
Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext$6.create(DefaultBeanContext.java:2994)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$getOrCreate$0(RefreshScope.java:102)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.getOrCreate(RefreshScope.java:101)
        at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:2977)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2903)
        at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1424)
        at io.micronaut.configuration.mongo.sync.$NamedMongoClientFactory$MongoClient0$Definition$Intercepted.interceptedTarget(Unknown Source)
        at io.micronaut.transaction.support.TransactionSynchronizationUtils.unwrapResourceIfNecessary(TransactionSynchronizationUtils.java:67)
        at io.micronaut.transaction.support.TransactionSynchronizationManager.getSynchronousTransactionStateOrCreate(TransactionSynchronizationManager.java:306)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.findOrCreateState(AbstractSynchronousTransactionManager.java:115)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.execute(AbstractSynchronousTransactionManager.java:144)
        at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:145)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.createDeviceAsUser(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.api.AbstractBackupUserServiceController.createDeviceAsUserApi(AbstractBackupUserServiceController.java:77)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.$$access$$createDeviceAsUserApi(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:143)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.createDeviceAsUserApi(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Thread

### Actual Behaviour

We are getting this error now:
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.security.rules.IpPatternsRule - One or more of the IP patterns matched the host address [10.244.0.0]. Continuing request processing.
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.s.rules.AbstractSecurityRule - The given roles [[isAnonymous(), isAuthenticated()]] matched one or more of the required roles [[isAuthenticated()]]. Allowing the request
08:26:21.721 [default-nioEventLoopGroup-1-2] DEBUG i.m.security.filters.SecurityFilter - Authorized request POST /backup/user/api/v1/devices. The rule provider io.micronaut.security.rules.SecuredAnnotationRule authorized the request.
08:26:21.742 [io-executor-thread-2] INFO  org.mongodb.driver.cluster - Cluster created with id ClusterId{value='6334052d8047ce403b1f8645', description='oracle-ee-backupservice-atpmongo'} and settings {hosts=[g5c84ba3e53cd0f-db202204221219.adb.us-ashburn-1.oraclecloudapps.com:27017], mode=LOAD_BALANCED, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
08:26:21.743 [io-executor-thread-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]
Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]
Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext$6.create(DefaultBeanContext.java:2994)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$getOrCreate$0(RefreshScope.java:102)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.getOrCreate(RefreshScope.java:101)
        at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:2977)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2903)
        at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1424)
        at io.micronaut.configuration.mongo.sync.$NamedMongoClientFactory$MongoClient0$Definition$Intercepted.interceptedTarget(Unknown Source)
        at io.micronaut.transaction.support.TransactionSynchronizationUtils.unwrapResourceIfNecessary(TransactionSynchronizationUtils.java:67)
        at io.micronaut.transaction.support.TransactionSynchronizationManager.getSynchronousTransactionStateOrCreate(TransactionSynchronizationManager.java:306)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.findOrCreateState(AbstractSynchronousTransactionManager.java:115)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.execute(AbstractSynchronousTransactionManager.java:144)
        at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:145)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.createDeviceAsUser(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.api.AbstractBackupUserServiceController.createDeviceAsUserApi(AbstractBackupUserServiceController.java:77)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.$$access$$createDeviceAsUserApi(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:143)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Intercepted.createDeviceAsUserApi(Unknown Source)
        at [com.oracle.ee](http://com.oracle.ee/).backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Thread

### Environment Information

Operating system : Linux
JDK : 17
Micronaut Core : 3.7.0
Micronaut Data: 3.8.0
GraalVM: 22.2

### Version

3.7.0

**Comment by graemerocher** [comment]
@dstepanov could you look at this one when you get back as a priority? Thanks

**Comment by dstepanov** [comment]
@nikhmalh  Please post the causing exception stacktrace

**Comment by nikhmalh** [comment]
@dstepanov :  When I degraded the version of GraalVM to 22.1.0 , it looks to be working fine with all the new versions of Micronaut Libs. So the problem seems to be with GraalVM 22.2.0.

Here is the complete stack trace:
08:30:47.444 [scheduled-executor-thread-1] INFO  org.mongodb.driver.cluster - Cluster created with id ClusterId{value='633406378047ce403b1f8646', description='oracle-ee-backupservice-atpmongo'} and settings {hosts=[g5c84ba3e53cd0f-db202204221219.adb.us-ashburn-1.oraclecloudapps.com:27017], mode=LOAD_BALANCED, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
08:30:47.445 [scheduled-executor-thread-1] ERROR i.m.s.DefaultTaskExceptionHandler - Error invoking scheduled task for bean [com.oracle.ee.backupsvc.scheduledjobs.$PreAuthRequestCleanup$Definition$Intercepted@21b4bf42] Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]

Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManager]

Path Taken: new MongoSynchronousTransactionManager(MongoClient mongoClient,String name) --> new MongoSynchronousTransactionManager([MongoClient mongoClient],String name)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext$6.create(DefaultBeanContext.java:2994)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$getOrCreate$0(RefreshScope.java:102)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micronaut.runtime.context.scope.refresh.RefreshScope.getOrCreate(RefreshScope.java:101)
        at io.micronaut.context.DefaultBeanContext.getOrCreateScopedRegistration(DefaultBeanContext.java:2977)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2903)
        at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1424)
        at io.micronaut.configuration.mongo.sync.$NamedMongoClientFactory$MongoClient0$Definition$Intercepted.interceptedTarget(Unknown Source)
        at io.micronaut.transaction.support.TransactionSynchronizationUtils.unwrapResourceIfNecessary(TransactionSynchronizationUtils.java:67)
        at io.micronaut.transaction.support.TransactionSynchronizationManager.getSynchronousTransactionStateOrCreate(TransactionSynchronizationManager.java:306)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.findOrCreateState(AbstractSynchronousTransactionManager.java:115)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.execute(AbstractSynchronousTransactionManager.java:144)
        at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:145)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at com.oracle.ee.backupsvc.scheduledjobs.$PreAuthRequestCleanup$Definition$Intercepted.execute(Unknown Source)
        at com.oracle.ee.backupsvc.scheduledjobs.$PreAuthRequestCleanup$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
        at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76)
        at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:127)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.NullPointerException: null
        at java.lang.String.valueOf(String.java:4218)
        at com.mongodb.WriteConcern.toString(WriteConcern.java:335)
        at java.lang.String.valueOf(String.java:4218)
        at com.mongodb.MongoClientSettings.toString(MongoClientSettings.java:881)
        at java.lang.String.valueOf(String.java:4218)
        at java.lang.StringBuilder.append(StringBuilder.java:173)
        at com.oracle.svm.enterprise.core.stringformat.a.a(stripped:153)
        at com.oracle.svm.enterprise.core.stringformat.a.format(stripped:104)
        at com.mongodb.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:87)
        at com.mongodb.client.internal.MongoClientImpl.<init>(MongoClientImpl.java:70)
        at com.mongodb.client.MongoClients.create(MongoClients.java:108)
        at com.mongodb.client.MongoClients.create(MongoClients.java:50)
        at io.micronaut.configuration.mongo.sync.NamedMongoClientFactory.mongoClient(NamedMongoClientFactory.java:45)
        at io.micronaut.configuration.mongo.sync.$NamedMongoClientFactory$MongoClient0$Definition.build(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
        ... 31 common frames omitted

**Comment by graemerocher** [comment]
@nikhmalh Are you able to isolate an example application that reproduces the problem?

**Comment by graemerocher** [comment]
Also please see can you provide the output of java --version from the GraalVM binary being used.

**Comment by nikhmalh** [comment]
Step 10/17 : RUN java --version
12:56:36   ---> Running in 6ca65bd40e0b
12:56:36  java 17.0.4 2022-07-19 LTS
12:56:36  Java(TM) SE Runtime Environment GraalVM EE 22.2.0 (build 17.0.4+11-LTS-jvmci-22.2-b05)
12:56:36  Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.2.0 (build 17.0.4+11-LTS-jvmci-22.2-b05, mixed mode, sharing)

**Comment by dstepanov** [comment]
We have a test that is validation that Mongo works with GraalVM native image
