### ISSUE TITLE
Upgrade to 3.7.0 breaks pipeline

### ISSUE THREAD

**Issue by jesperancinha** [micronaut-projects/micronaut-data#1775]
### Expected Behavior

I expect the upgrade not to cause breaking changes or if it does cause breaking changes, that the exceptions or errors thrown are readable up to a point of being solvable.

When it comes to versions:
I've noticed that micronaut-data varies a bit from micronaut-data-r2dbc and these vary a lot more when it comes to maven versions or the main micronaut-version. I've also noticed that micronaut-java-inject was left behind in the main parent micronaut file and I had to add it, like `micronaut-core` to the kapt configuration annotation processors.

### Actual Behaviour

This is what results now after just the compilation action on version 3.7.0

```shell
[INFO] --- kotlin-maven-plugin:1.7.20:kapt (kapt) @ buy-oyc-commons ---
[WARNING] 'tools.jar' was not found, kapt may work unreliably
[INFO] Applied plugin: 'all-open'
[INFO] Applied plugin: 'jpa'
[INFO] Applied plugin: 'no-arg'
[ERROR] error: Unable to implement Repository method: MealReservationRepository.exists(QuerySpecification arg0). Cannot query persistentEntity [MealReservation] on non-existent property: arg0
[ERROR] Note: Creating bean classes for 24 type elements
[INFO] --------------------------------------------------------
```

It complains now about this `exists` method. Up to version 3.7.0 this never happened. I've unified all versions to micronaut.version in my project, but it still fails.

A failing pipeline example here:

https://github.com/jesperancinha/buy-odd-yucca-concert/actions/runs/3152167819/jobs/5127037077

```shell
Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.7.20:kapt (kapt) on project buy-oyc-commons: Compilation failure: Compilation failure: 
Error: [ERROR] error: Unable to implement Repository method: AuditLogRepository.exists(QuerySpecification arg0). Cannot query persistentEntity [AuditLog] on non-existent property: arg0
Error:  Note: Creating bean classes for 24 type elements
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :buy-oyc-commons
```

### Steps To Reproduce

1. Just run the build locally and you should be able to reproduce this issue. The project is located here: https://github.com/jesperancinha/buy-odd-yucca-concert/

### Environment Information

- Linux/MAC-OS
- JDK17

### Example Application

https://github.com/jesperancinha/buy-odd-yucca-concert

### Version

3.7.0

**Comment by radovanradic** [comment]
Hi @jesperancinha , is this still an issue? I checked out recently and was able to compile that project.

**Comment by jesperancinha** [comment]
Hi there @radovanradic , thanks for having a look. The master branch builds fine, but the fail comes in the upgrade branch. You can see the error I'm getting here: https://github.com/jesperancinha/buy-odd-yucca-concert/pull/596

**Comment by radovanradic** [comment]
Hi @jesperancinha , I looked more at this issue and seems this PR https://github.com/jesperancinha/buy-odd-yucca-concert/pull/696 should resolve compilation error for repository.exists (after it is passed then some other error in module `buy-oyc-parking-service` is failing, related to OpenAPI - hopefully someone else might know what is that error)

**Comment by dstepanov** [comment]
Maybe @altro3 would know about open api

**Comment by radovanradic** [comment]
Micronaut version is 3.7.2, micronaut data 3.8.1 and openapi 4.0.0 and this is the compile error
```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.7.21:kapt (kapt) on project buy-oyc-parking-service: Compilation failure: Compilation failure: 
[ERROR] Note: Generating OpenAPI Documentation
[ERROR] Note: Writing OpenAPI YAML to destination: /dev/projects/buy-odd-yucca-concert/buy-oyc-parking-service/target/classes/META-INF/swagger/openapi-definition-0.0.0-SNAPSHOT.yml
[ERROR] Note: Writing OpenAPI View to destination: /dev/projects/buy-odd-yucca-concert/buy-oyc-parking-service/target/classes/META-INF/swagger/views/swagger-ui/index.html
[ERROR] Note: Creating bean classes for 5 type elements
[ERROR] java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException
[ERROR] 	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:104)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:99)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
[ERROR] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execCompiler(KotlinCompileMojoBase.java:228)
[ERROR] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:237)
[ERROR] 	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:152)
[ERROR] 	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:44)
[ERROR] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute(KotlinCompileMojoBase.java:209)
[ERROR] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute(K2JVMCompileMojo.java:222)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:90)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)
[ERROR] 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:235)
[ERROR] 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:198)
[ERROR] 	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:106)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:116)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:126)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:100)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:265)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
[ERROR] 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:256)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:99)
[ERROR] 	... 34 more
[ERROR] Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoSuchMethodError: 'boolean io.micronaut.annotation.processing.visitor.JavaMethodElement.isAccessible()'
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1035)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
[ERROR] 	... 51 more
[ERROR] Caused by: java.lang.NoSuchMethodError: 'boolean io.micronaut.annotation.processing.visitor.JavaMethodElement.isAccessible()'
[ERROR] 	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor$AnnBeanElementVisitor.visitExecutable(BeanDefinitionInjectProcessor.java:938)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$MethodSymbol.accept(Symbol.java:2245)
[ERROR] 	at java.compiler@17.0.4/javax.lang.model.util.ElementScanner6.scan(ElementScanner6.java:153)
[ERROR] 	at java.compiler@17.0.4/javax.lang.model.util.ElementScanner6.scan(ElementScanner6.java:140)
[ERROR] 	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor$AnnBeanElementVisitor.visitType(BeanDefinitionInjectProcessor.java:618)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:1575)
[ERROR] 	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.lambda$process$7(BeanDefinitionInjectProcessor.java:282)
[ERROR] 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[ERROR] 	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.process(BeanDefinitionInjectProcessor.java:277)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
[ERROR] 	... 55 more
[ERROR] -> [Help 1]
```

**Comment by altro3** [comment]
@radovanradic try to use Micronaut OpenAPI 4.7.1

**Comment by radovanradic** [comment]
I tried (also some other version, but it always fails with some different error). With `4.7.1`
```
[ERROR] Note: Generating OpenAPI Documentation
[ERROR] java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException
[ERROR] 	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:104)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:99)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
[ERROR] 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
[ERROR] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execCompiler(KotlinCompileMojoBase.java:228)
[ERROR] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execCompiler(K2JVMCompileMojo.java:237)
[ERROR] 	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:152)
[ERROR] 	at org.jetbrains.kotlin.maven.kapt.KaptJVMCompilerMojo.execCompiler(KaptJVMCompilerMojo.java:44)
[ERROR] 	at org.jetbrains.kotlin.maven.KotlinCompileMojoBase.execute(KotlinCompileMojoBase.java:209)
[ERROR] 	at org.jetbrains.kotlin.maven.K2JVMCompileMojo.execute(K2JVMCompileMojo.java:222)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:90)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:31)
[ERROR] 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:235)
[ERROR] 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:198)
[ERROR] 	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:106)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:116)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:126)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:100)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:265)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
[ERROR] 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:256)
[ERROR] 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:99)
[ERROR] 	... 34 more
[ERROR] Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoSuchMethodError: 'java.util.List io.micronaut.inject.ast.EnumElement.elements()'
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1035)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
[ERROR] 	... 51 more
[ERROR] Caused by: java.lang.NoSuchMethodError: 'java.util.List io.micronaut.inject.ast.EnumElement.elements()'
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getEnumValues(AbstractOpenApiVisitor.java:2087)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:1811)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:780)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.processPropertyElements(AbstractOpenApiVisitor.java:2264)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.populateSchemaProperties(AbstractOpenApiVisitor.java:2215)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:1856)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.readAllInterfaces(AbstractOpenApiVisitor.java:1950)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:1840)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:900)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.lambda$buildContent$24(AbstractOpenApiEndpointVisitor.java:1542)
[ERROR] 	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4966)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.buildContent(AbstractOpenApiEndpointVisitor.java:1540)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.processBody(AbstractOpenApiEndpointVisitor.java:866)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.processParameter(AbstractOpenApiEndpointVisitor.java:597)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.processParameters(AbstractOpenApiEndpointVisitor.java:515)
[ERROR] 	at io.micronaut.openapi.visitor.AbstractOpenApiEndpointVisitor.visitMethod(AbstractOpenApiEndpointVisitor.java:453)
[ERROR] 	at io.micronaut.annotation.processing.visitor.LoadedVisitor.visit(LoadedVisitor.java:178)
[ERROR] 	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitExecutable(TypeElementVisitorProcessor.java:504)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$MethodSymbol.accept(Symbol.java:2245)
[ERROR] 	at java.compiler@17.0.4/javax.lang.model.util.ElementScanner6.scan(ElementScanner6.java:153)
[ERROR] 	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitType(TypeElementVisitorProcessor.java:410)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:1575)
[ERROR] 	at io.micronaut.annotation.processing.TypeElementVisitorProcessor.process(TypeElementVisitorProcessor.java:251)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
[ERROR] 	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)
[ERROR] 	... 55 more
```

**Comment by altro3** [comment]
@radovanradic Well, I'm sure you have a problem with the micronaut version. And you are using an old version of the core. Because the method you don't have was added in version 3.6.0. Check the version of micronaut-core that is connected to the annotation-processor.

![изображение](https://user-images.githubusercontent.com/48474279/204261844-3e547296-f446-4eed-b285-2eeea34bbaab.png)

**Comment by radovanradic** [comment]
It's version 3.7.2, like micronaut.version
If I change it to 3.7.4 I am getting the same error so no idea how this can be resolved.

**Comment by altro3** [comment]
I'm sure the problem is with the micronaut version. But to be sure of this - please provide an example to reproduce your problem, because locally everything works fine for me with java , kotlin and groovy

**Comment by radovanradic** [comment]
Here is the repo I forked from the user https://github.com/radovanradic/buy-odd-yucca-concert and checkout branch `data-processor-fix`

**Comment by radovanradic** [comment]
Thanks @altro3 for looking into it. Yes, when I changed to 3.7.2 micronaut version in micronaut data and tested with 3.8.2-SNAPSHOT locally and openapi 4.7.1 then it compiles. So this is probably have to wait for some next micronaut data version.

**Comment by altro3** [comment]
@dstepanov @radovanradic I think you need to release updates for EVERY minor / major core update. Otherwise, similar problems in the future are inevitable.

**Comment by jesperancinha** [comment]
Everything works now after @radovanradic 's commits. Thank you!

**Comment by radovanradic** [comment]
Awesome @jesperancinha, glad that it finally got resolved.
