### ISSUE TITLE
Serializing MongoDB mapped types over HTTP does not work

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-data#1779]
### Expected Behavior

Should serialize

### Actual Behaviour

```
Caused by: io.micronaut.serde.exceptions.SerdeException: Expected an instance of BsonWriterEncoder got: io.micronaut.serde.jackson.SpecializedJacksonEncoder$ReuseChildEncoder@741f658
        at io.micronaut.serde.bson.custom.AbstractBsonSerde.asBson(AbstractBsonSerde.java:59)
        at io.micronaut.serde.bson.custom.AbstractBsonSerde.serialize(AbstractBsonSerde.java:45)
        at 
```

### Version

3.7.1

**Comment by graemerocher** [comment]
[demo.zip](https://github.com/micronaut-projects/micronaut-data/files/9706941/demo.zip)

**Comment by graemerocher** [comment]
example app ☝️

**Comment by justinemina** [comment]
remove
 implementation("io.micronaut.serde:micronaut-serde-jackson")
and remplace with
    implementation("io.micronaut.serde:micronaut-serde-bson")
