### ISSUE TITLE
Unable to use Attribute converter as mentioned in help document.

### ISSUE THREAD

**Issue by Kartikvk1996** [micronaut-projects/micronaut-data#1849]
### Expected Behavior

The attribute converter should work by converting the class to a primitive data type.

### Actual Behaviour

An exception is thrown. 

`Message: Could not determine type for: example.micronaut.domain.Quantity, at table: book, for columns: [org.hibernate.mapping.Column(quantity)]
Path Taken: SessionFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2367)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2737)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
	... 9 common frames omitted
Caused by: org.hibernate.MappingException: Could not determine type for: example.micronaut.domain.Quantity, at table: book, for columns: [org.hibernate.mapping.Column(quantity)]
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:515)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:482)
	at org.hibernate.mapping.Property.isValid(Property.java:231)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:627)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:267)
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:359)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471)
	at io.micronaut.configuration.hibernate.jpa.conf.AbstractHibernateFactory.buildHibernateSessionFactory(AbstractHibernateFactory.java:105)
	at io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryPerDataSourceFactory.java:105)
	at io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildHibernateSessionFactoryBuilder4$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
`

### Steps To Reproduce

1. Download the project from https://guides.micronaut.io/latest/micronaut-jpa-hibernate-maven-java.html 
2. Add "Quantity" class and associated Attribute converter mentioned in steps https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcAttributeConverter 
3. Try to start the application, The application will not start instead throws an error.

### Environment Information

- Windows OS
- Java 8

### Version

3.7.3

**Comment by dstepanov** [comment]
The section applies for Micronaut Data JDBC/R2DBC

**Comment by Kartikvk1996** [comment]
@dstepanov  Is this a bug or configuration issue with any missing annotation?

**Comment by dstepanov** [comment]
For Hibernate, you need to create a converter using `javax.persistence.AttributeConverter`
