### ISSUE TITLE
Error deserialising nested objects with MongoDB

### ISSUE THREAD

**Issue by cosmin-marginean** [micronaut-projects/micronaut-data#1880]
### Expected Behavior

Reading a document with nested objects from MongoDB should perform without error. 

### Actual Behaviour

When reading from MongoDB an object that contains nested objects, an error is thrown:
```
org.bson.BsonInvalidOperationException: readStartDocument can only be called when State is VALUE, not when State is END_OF_DOCUMENT.
	at app//org.bson.AbstractBsonReader.throwInvalidState(AbstractBsonReader.java:668)
	at app//org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:686)
	at app//org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:721)
	at app//org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:449)
	at app//io.micronaut.serde.bson.BsonReaderDecoder.nextToken(BsonReaderDecoder.java:99)
	at app//io.micronaut.serde.support.AbstractStreamDecoder.skipValue(AbstractStreamDecoder.java:844)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.skipUnknown(SimpleObjectDeserializer.java:134)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.skipUnknownProperties(SimpleObjectDeserializer.java:127)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.readProperties(SimpleObjectDeserializer.java:74)
	at app//io.micronaut.serde.support.deserializers.SimpleObjectDeserializer.deserialize(SimpleObjectDeserializer.java:59)
	at app//io.micronaut.data.mongodb.serde.MappedCodec.decode(MappedCodec.java:83)
	at app//com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at app//com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
...
```

### Steps To Reproduce

```kotlin
@Serdeable
@MappedEntity
data class NestedDoc(
    val child: Child = Child(),

    @field:Id
    val id: String = UUID.randomUUID().toString()
)

@Serdeable
data class Child(
    val name: String = UUID.randomUUID().toString(),
)


@MongoRepository
interface NestedDocRepository : PageableRepository<NestedDoc, String>


@MicronautTest
class BugTestSimplified {

    @Inject
    lateinit var nestedDocRepo: NestedDocRepository

    @Test
    fun test() {
        val nestedDoc = NestedDoc()
        nestedDocRepo.save(nestedDoc)
        println("Nested doc: " + nestedDocRepo.findById(nestedDoc.id).get())
    }
}
```

There is a repository where this can be reproduced (uses test containers)
1. Checkout https://github.com/cosmin-marginean/micronaut-mongo-nested-objects-bug
2. Run `./gradlew clean test`
3. Check `build/reports/tests/test/index.html`

The code reproducing this can be found in this test https://github.com/cosmin-marginean/micronaut-mongo-nested-objects-bug/blob/main/src/test/kotlin/com/test/BugTest.kt

### Environment Information

- Mac OS
- JDK17

### Example Application

https://github.com/cosmin-marginean/micronaut-mongo-nested-objects-bug

### Version

* Micronaut 3.7.4
* Micronaut Data 3.8.1

**Comment by radovanradic** [comment]
@cosmin-marginean I think this should be changed to be either
```
@Serdeable
@MappedEntity
data class NestedDoc(
    var child: Child = Child(),

    @field:Id
    val id: String = UUID.randomUUID().toString()
)

@Serdeable
data class Child(
    var name: String = UUID.randomUUID().toString(),
)
```

or
```
@Serdeable
@MappedEntity
data class NestedDoc(
    val child: Child,

    @field:Id
    val id: String = UUID.randomUUID().toString()
)

@Serdeable
data class Child(
    val name: String,
)
```
In 2nd case you would have to pass constructor params when creating `NestedDoc` instance. In first case, fields should be `var` or else could not be deserialized since already initialized as `val` so cannot be changed afterwards. In first case, fields would be initialized but since mutable then deserialization can set them again. I believe this is the issue and if you change to either of these two then tests would pass.

**Comment by cosmin-marginean** [comment]
@radovanradic That seems to be work. Thank you for this, it's at least good to know this kind of constraint.
