### ISSUE TITLE
 Error instantiating bean of type  [io.micronaut.http.server.codec.TextStreamCodec]

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#1996]
### Steps to reproduce

Clone https://github.com/grails-core-issues-forks/micronaut-data-1996

Run  ./mvnw verify  

You will get:

```
Unexpected error occurred: Error instantiating bean of type  [io.micronaut.http.server.codec.TextStreamCodec]
Message: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,List codecs,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,[List codecs],DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new TextStreamCodec(ApplicationConfiguration applicationConfiguration,[ByteBufferFactory byteBufferFactory],BeanProvider codecRegistryProvider,CodecConfiguration codecConfiguration)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.codec.TextStreamCodec]
Message: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,List codecs,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,[List codecs],DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new TextStreamCodec(ApplicationConfiguration applicationConfiguration,[ByteBufferFactory byteBufferFactory],BeanProvider codecRegistryProvider,CodecConfiguration codecConfiguration)
	
```

This is an application which uses Lambda and Data JDBC and thus it does not use netty. Because of that `TextStreamCodec` is expected not to be loaded. https://github.com/micronaut-projects/micronaut-core/blob/3.8.x/http-server/src/main/java/io/micronaut/http/server/codec/TextStreamCodec.java#L57

**Comment by sdelamo** [comment]
@dstepanov @radovanradic any idea?

**Comment by radovanradic** [comment]
Micronaut data does not have dependency on http-server so not sure how it can be related to DefaultJdbcRepositoryOperations creation?

**Comment by sdelamo** [comment]
`TextStreamCodec` is a bean of type `MediaTypeCodec`. And Micronaut Data uses that.

**Comment by timyates** [comment]
FTR: Gradle fails too

https://scans.gradle.com/s/w3jwyjisjqyem

With the same error:

```
?[36m12:26:13.073?[0;39m ?[1;30m[Test worker]?[0;39m ?[1;31mERROR?[0;39m ?[35mi.m.http.server.RouteExecutor?[0;39m - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.http.server.codec.TextStreamCodec]

Message: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,List codecs,DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new DefaultJdbcRepositoryOperations(String dataSourceName,DataJdbcConfiguration jdbcConfiguration,DataSource dataSource,TransactionOperations transactionOperations,ExecutorService executorService,BeanContext beanContext,[List codecs],DateTimeProvider dateTimeProvider,RuntimeEntityRegistry entityRegistry,DataConversionService conversionService,AttributeConverterRegistry attributeConverterRegistry,SchemaTenantResolver schemaTenantResolver,JdbcSchemaHandler schemaHandler) --> new TextStreamCodec(ApplicationConfiguration applicationConfiguration,[ByteBufferFactory byteBufferFactory],BeanProvider codecRegistryProvider,CodecConfiguration codecConfiguration)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.codec.TextStreamCodec]
```

**Comment by timyates** [comment]
Progress report:

- Tried switching to implementation in core for buffer-netty
    - Didn't make a difference
- Added `@Requires(notEnv={"lambda"})` to TextStreamCodec
    - It then fails on a different class (JsonConverterRegistrar)

This only occurs when the test calls the `delete` endpoint...

If I remove that from the test (by [commenting this out](https://github.com/grails-core-issues-forks/micronaut-data-1996/blob/c5fd7521fe138f454951cbb6afe5e6f126058d1e/src/test/java/com/unicorn/store/UnicornControllerTest.java#L53-L59)) then `./mvn verify` passes...  Does this make any sense @sdelamo @dstepanov ?

**Comment by graemerocher** [comment]
with the example attached I get

```
com.amazonaws.serverless.exceptions.ContainerInitializationException: Error starting Micronaut container: Bean definition [io.micronaut.data.jdbc.config.SchemaGenerator] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Error configuring data source 'default'. No URL specified
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration) --> DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
```

**Comment by timyates** [comment]
@graemerocher with `./mvnw verify`?

**Comment by graemerocher** [comment]
with mvn verify I get

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.789 s <<< FAILURE! - in com.unicorn.store.UnicornControllerTest
[ERROR] unicornCrud  Time elapsed: 1.782 s  <<< ERROR!
com.amazonaws.serverless.exceptions.ContainerInitializationException:
Error starting Micronaut container: Bean definition [io.micronaut.data.jdbc.config.SchemaGenerator] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not resolve placeholder ${auto.test.resources.datasources.default.password}
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration) --> DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at com.unicorn.store.UnicornControllerTest.unicornCrud(UnicornControllerTest.java:29)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException:
Bean definition [io.micronaut.data.jdbc.config.SchemaGenerator] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not resolve placeholder ${auto.test.resources.datasources.default.password}
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration) --> DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at com.unicorn.store.UnicornControllerTest.unicornCrud(UnicornControllerTest.java:29)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException:
Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not resolve placeholder ${auto.test.resources.datasources.default.password}
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration) --> DataSource.dataSource([DatasourceConfiguration datasourceConfiguration])
	at com.unicorn.store.UnicornControllerTest.unicornCrud(UnicornControllerTest.java:29)
Caused by: io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${auto.test.resources.datasources.default.password}
	at com.unicorn.store.UnicornControllerTest.unicornCrud(UnicornControllerTest.java:29)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   UnicornControllerTest.unicornCrud:29 » ContainerInitialization Error starting ...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.056 s
[INFO] Finished at: 2023-04-14T13:24:47+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Test resources service already started on port 59724
[info] Shutting down Micronaut Test Resources service
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project store-micronaut: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/graemerocher/dev/micronaut/apps/micronaut-data-1996/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by timyates** [comment]
I'm really confused now...

I added GE via the instructions [here](https://docs.gradle.com/enterprise/maven-extension/#getting_set_up) (so I can show you what I see) 

[And I get a different error](https://ge.micronaut.io/s/qecosy7mv3yg2/console-log?page=1#L42) the same as @sdelamo was seeing

More confused than ever...

**Comment by radovanradic** [comment]
This should be fixed in Micronaut 4 because `DefaultJdbcRepositoryOperations` no longer uses `MediaTypeCodec`. I was not able to try it and convert this demo app to mn4 because it requires a lot of changes in aws function stuff.

**Comment by sdelamo** [comment]
I have updated the [sample application to Micronaut Framework 4 ](https://github.com/grails-core-issues-forks/micronaut-data-1996/tree/mn4) and I can confirm it is fixed in 4 M3. Thanks everyone for looking into it.
