### ISSUE TITLE
[4.0.x] Custom interceptors cannot be instantiated: io.micronaut.core.reflect.exception.InstantiationException: No default constructor exists

### ISSUE THREAD

**Issue by rlubke** [micronaut-projects/micronaut-data#2079]
### Expected Behavior

See this interceptor: https://github.com/micronaut-projects/micronaut-coherence/blob/master/coherence-data/src/main/java/io/micronaut/coherence/data/interceptors/GetEntityTypeInterceptor.java

I would expect it to be used as in previous versions of Micronaut, however, attempts to use this interceptor are met with:

### Actual Behaviour

`No default constructor exists
io.micronaut.core.reflect.exception.InstantiationException: No default constructor exists
	at app//io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:231)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.findInterceptor(DataInterceptorResolver.java:127)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.lambda$resolve$2(DataInterceptorResolver.java:94)
	at java.base@17.0.6/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at app//io.micronaut.data.runtime.intercept.DataInterceptorResolver.resolve(DataInterceptorResolver.java:73)
	at app//io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//io.micronaut.coherence.data.repositories.CoherenceBookRepository$Intercepted.getEntityTypeInternal(Unknown Source)`

### Steps To Reproduce

1. Checkout the mn4.0 branch within the https://github.com/micronaut-projects/micronaut-coherence project.
2. Run RepositoryTest.shouldReturnEntityType()

### Environment Information

- OS: MacOS Ventura 13.2
- -Java Version: "17.0.6" 2023-01-17 LTS

### Version

4.0

**Comment by dstepanov** [comment]
@rlubke Can you change the constructors to have a not private scope, so no reflection is needed? In Micronaut 4 we will require explicit `@ReflectiveAccess`  for this cases
