### ISSUE TITLE
Invalid query parameters when using Pageable as argument to declarative http client

### ISSUE THREAD

**Issue by Uniqen** [micronaut-projects/micronaut-data#219]
It would be very usable if Pageable was converted to the correct query parameters when used with the declarative http client. For example for an API-gateway that should just forward the request or when writing tests. This would also make it possible to share a common interface between Controller and Client.

The problem as I see it is to make it a non breaking change or is there a way to configure how the query parameters is resolved that I don't know about? 

### Steps to Reproduce

1. Create Controller with Pageable as argument
```java
@Controller("/pets")
class PetController {
    @Get("/{?pageable*}") // No really needed but for symmetrical 
    List<NameDTO> all(Pageable pageable) {
        return petRepository.list(pageable);
    }
}
```
2. Create corresponding declarative http client
```java
@Client("/pets")
public interface PetClient {
    @Get("/{?pageable*}")
    List<NameDTO> all(Pageable pageable);
}
```
3. Use client to invoke controller. 
```java
List<NameDTO> results = petClient.all(Pageable.from(1,1).order("name", DESC));
```
### Expected Behaviour
The pageable should be sent using the query parameters page, size and sort:
`GET /parent/?size=1&sort=name%2CDESC&page=1`

### Actual Behaviour
The query string is invalid (both page (sent as number) and sort) plus som additional irrelevant parameters.
`GET /pets/?sort=io.micronaut.data.model.DefaultSort%40f331e9d7&sorted=true&number=1&orderBy=io.micronaut.data.model.Sort%24Order%40f331e999&offset=1&size=1`

And then an exception is raised on the server side since the sorting is invalid:
```java
21:23:05.541 [pool-2-thread-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Cannot sort on non-existent property path: io.micronaut.data.model.DefaultSort@f331e9d7
java.lang.IllegalArgumentException: Cannot sort on non-existent property path: io.micronaut.data.model.DefaultSort@f331e9d7
	at io.micronaut.data.model.query.builder.AbstractSqlLikeQueryBuilder.lambda$buildOrderBy$35(AbstractSqlLikeQueryBuilder.java:1310)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.micronaut.data.model.query.builder.AbstractSqlLikeQueryBuilder.buildOrderBy(AbstractSqlLikeQueryBuilder.java:1310)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findAll$6(HibernateJpaOperations.java:252)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findAll(HibernateJpaOperations.java:245)
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:52)
	at io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:36)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:78)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at example.repositories.PetRepository$Intercepted.list(Unknown Source)
	at example.controllers.PetController.all(PetController.java:24)
...
``` 

### Environment Information

- **Operating System**: Mac OS 10.14.3
- **Micronaut Version:**  1.2.3
- **Micronaut Data Version:**  1.0.0.M3
- **JDK Version:** 8.0.222

### Example Application

- See https://github.com/Uniqen/micronaut-predator/tree/pageable_as_query_parameter
- Or just the relevant commit https://github.com/Uniqen/micronaut-predator/commit/619bcf54d4061cf4b4658cc96da297f3c8670a1f

**Comment by graemerocher** [comment]
This would be nice. Currently the client implementation is not flexible enough to allow custom encoding of arguments. So we would need an improvement in Micronaut Core first to implement this.

**Comment by Uniqen** [comment]
I've duplicated the Pageable (and DefaultPageable, Sort, DefaultSort) as a workaround until it is resolved. This still blocks sharing interface between Client and Controller but at least makes it easy to use in tests and api gateway.

```java
@Controller("/pets")
class PetGatewayController {
    @Get("/{?pageable*}")
    List<NameDTO> all(Pageable pageable) {
        return petClient.all(PageableQuery.from(pageable));
    }
}

@Client("/pets")
public interface PetClient {
    @Get("/{?pageable*}")
    List<NameDTO> all(PageableQuery pageable);
}

//Usage in tests is the same as Pageable
PageableQuery pageable = PageableQuery.from(1, 1)
    .order("name", DESC);
List<NameDTO> results = petClient.all(pageable);
```

If anyone else is interested in the workaround see commit: https://github.com/Uniqen/micronaut-predator/commit/37147347b4e1c6d59d2816e658c3ba9d6ed623d0

**Comment by njimenezotto** [comment]
Another option is to pass to the @Client the values of the Pageable like this:
```
@QueryValue("size") int size,
@QueryValue("number") int number
```
And the @Controller can still declare the 
```
@QueryValue("pageable") Pageable page
```

**Comment by regine-chan** [comment]
Any updates on this? Would be terrific to be able to share interface between controllers and clients.

**Comment by graemerocher** [comment]
In Micronaut 4 we added support for custom message writers so maybe it is possible now

**Comment by Hc747** [comment]
Bumping this - any updates for `Pageable` parameters within `@Controller` methods?

**Comment by dstepanov** [comment]
Triage: still reproducible. There's a `PageableRequestArgumentBinder` that parses `Pageable` from query parameters on the `@Controller` side, but I found no equivalent client-side argument binder for encoding a `Pageable`/`Sort` into query parameters when it's used on a declarative `@Client` method — so it still falls back to default reflective/toString-style encoding and produces the broken query string described here.

In the meantime, the workaround already posted in this thread (bind `page`/`size`/`sort` as individual `@QueryValue` params on the client, or duplicate a query-string-friendly `Pageable`-like type) is still the way to go. Keeping this open as a valid, still-active enhancement.
