### ISSUE TITLE
Can not set up the null through the Criteria API

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-data#2368]
### Actual Behaviour

```
08:53:04.611 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at io.micronaut.data.runtime.criteria.RuntimePersistentEntityCriteriaUpdate.asParameter(RuntimePersistentEntityCriteriaUpdate.java:79)
        at io.micronaut.data.runtime.criteria.RuntimePersistentEntityCriteriaUpdate.setValue(RuntimePersistentEntityCriteriaUpdate.java:71)
        at io.micronaut.data.model.jpa.criteria.impl.AbstractPersistentEntityCriteriaUpdate.set(AbstractPersistentEntityCriteriaUpdate.java:131)
        at io.micronaut.data.model.jpa.criteria.impl.AbstractPersistentEntityCriteriaUpdate.set(AbstractPersistentEntityCriteriaUpdate.java:59)
        at com.example.Specifications.lambda$setNewName$3(Specifications.java:29)
        at io.micronaut.data.repository.jpa.criteria.SpecificationComposition.toPredicate(SpecificationComposition.java:139)
        at io.micronaut.data.repository.jpa.criteria.SpecificationComposition.lambda$composed$2(SpecificationComposition.java:73)
        at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.lambda$getCriteriaUpdateBuilder$9(AbstractSpecificationInterceptor.java:420)
        at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.buildUpdateAll(AbstractSpecificationInterceptor.java:185)
        at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.preparedQueryForCriteria(AbstractSpecificationInterceptor.java:160)
        at io.micronaut.data.runtime.intercept.criteria.UpdateAllSpecificationInterceptor.intercept(UpdateAllSpecificationInterceptor.java:45)
        at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at com.example.DemoRepository$Intercepted.updateAll(Unknown Source)
        at com.example.IssuesController.jsonp(IssuesController.java:60)
        at com.example.$IssuesController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
        at io.micronaut.context.DefaultBeanContext$BeanContextExecutionHandle.invoke(DefaultBeanContext.java:4256)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:223)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
        at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:440)
        at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:430)
        at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$2(RequestLifecycle.java:146)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
        at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$4(RequestLifecycle.java:146)
        at io.micronaut.http.server.RequestLifecycle.lambda$runWithFilters$14(RequestLifecycle.java:264)
        at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:308)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner$FilterChainImpl.proceed(FilterRunner.java:971)
        at io.micronaut.session.http.HttpSessionFilter.doFilter(HttpSessionFilter.java:98)
        at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)
        at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:280)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:242)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
        at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
        at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:272)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner$FilterChainImpl.proceed(FilterRunner.java:971)
        at io.micronaut.jaxrs.runtime.core.JaxRsResponseFilter.doFilter(JaxRsResponseFilter.java:46)
        at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)
        at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:280)
        at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
        at io.micronaut.http.filter.FilterRunner.filterRequest(FilterRunner.java:167)
        at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:162)
        at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:281)
        at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:143)
        at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:85)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:223)
        at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.accept(NettyServerWebSocketUpgradeHandler.java:156)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:344)
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:202)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpRequestChannelRead(WebSocketServerExtensionHandler.java:160)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:83)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps To Reproduce

```
static PredicateSpecification<Demo> idIsLessThan(int id) {
        return (root, criteria) -> {
        	System.out.println(root.get("id").getJavaType());
        	return criteria.lessThan(root.get("id"), id);
        };
    }

static UpdateSpecification<Demo> setNewName(String newName) {
        return (root, query, criteriaBuilder) -> {
            query.set(root.get("name"), newName);
            return null;
        };
    }
demoRepository.updateAll(setNewName(null).where(idIsLessThan(123)));
```

### Version

4.0.0-RC1

**Comment by appflowpersistent** [comment]
updated.
