### ISSUE TITLE
[Data Mongo]: Mock  failed with Spock 

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-data#2374]
### Expected Behavior

```groovy
@MicronautTest(transactional = false)
class CustomerControllerSpec extends Specification {

    @Inject
    EmbeddedApplication<?> application

    @Inject
    @Client("/")
    ReactorHttpClient client

    @Inject
    CustomerRepository customerRepository

   // tests

    @MockBean(CustomerRepository)
    CustomerRepository mockedCustomerRepository() {// must use explicit type declaration
        Mock(CustomerRepository)
    }
}
```

When running the tests, it still try to connect a Mongo server.

### Actual Behaviour

```bash
12:27:59.805 [Test worker] INFO  i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment - Established active environments: [test]
12:28:01.092 [cluster-ClusterId{value='64b22050eb1a710ff34c11c5', description='demo'}-localhost:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:73)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:209)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:199)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:159)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:107)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:82)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68)
	... 4 common frames omitted

```

### Environment Information

Windows 10 Pro
Java 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/data-mongodb-groovy

### Version

4.0.0

**Comment by radovanradic** [comment]
@hantsy This happens because of 
```
micronaut:
  ...
  data:
    mongodb:
      create-collections: true
```
and this tries to connect and create collections. Adding this annotation to `CustomerControllerSpec` should resolve the error:
`@Property(name = "micronaut.data.mongodb.create-collections", value = "false")`

Few other changes are needed for this project to pass tests, you can try applying this diff patch 
[micronaut-sandbox.diff.zip](https://github.com/micronaut-projects/micronaut-data/files/12066824/micronaut-sandbox.diff.zip)
