### ISSUE TITLE
NullPointerException when using JacksonObjectSerializer.deserialize

### ISSUE THREAD

**Issue by spacecenter** [micronaut-projects/micronaut-data#239]
NPE error while trying to deserialize string "null".
In this case `ObjectMapper `returns null value, but `JacksonObjectSerializer` use Optional.of method to wrap result.
And it throws a `NullPointerException`.

Example of code
```java
    ObjectMapper objectMapper = new ObjectMapperFactory().objectMapper(null, null);
    new JacksonObjectSerializer(objectMapper).deserialize("null".getBytes());
```

Stack Trace:
```stacktrace
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at io.micronaut.jackson.serialize.JacksonObjectSerializer.deserialize(JacksonObjectSerializer.java:68)
	at io.micronaut.core.serialize.ObjectSerializer.deserialize(ObjectSerializer.java:111)
```

Expected  Behavior: returned empty Optional.

**Comment by graemerocher** [comment]
I am unsure how this relates to Micronaut Data? Why you are instantiating the `JacksonObjectSerializer` directly?

**Comment by spacecenter** [comment]
You are right. Sorry, I've confused projects
