### ISSUE TITLE
Connect micronaut application with both Mongo DB & MySQL

### ISSUE THREAD

**Issue by cprashantgupta** [micronaut-projects/micronaut-data#2401]
### Issue description

I need to connect micronaut with both MySQL and Mongo DB where in the Mongo DB will be primary and MySql is just to fetch some results. 
If I am using JPA and creating a lambda for the same following error occurs on start of it  :

`<html>
<body>

Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.data.mongodb.transaction.MongoSynchronousTransactionManagerImpl, io.micronaut.transaction.hibernate5.HibernateTransactionManager]
--

<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by dstepanov** [comment]
Try to rename the datasource to something other than the default.

**Comment by cprashantgupta** [comment]
If I try renaming database then jdbc hikari initialization fails.

**Comment by dstepanov** [comment]
Hmm that's strange, can you please create a sample app to reproduce the problem?

**Comment by cprashantgupta** [comment]
Sure will create a dummy project. 

Just by changing default DB name , I get following : 

`Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.operations.PrimaryRepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859)
`

**Comment by dstepanov** [comment]
You might need to use `@Repository("mydb")`

**Comment by cprashantgupta** [comment]
Even adding the correct db name , I get this : 

No bean of type [io.micronaut.data.operations.PrimaryRepositoryOperations] exists for the given qualifier: @Named('mydb').

**Comment by cprashantgupta** [comment]
I think the problem is or connecting MySQL I need following dependencies : 

`<dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-hibernate-jpa</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.micronaut.sql</groupId>
      <artifactId>micronaut-jdbc-hikari</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <scope>runtime</scope>
    </dependency>`
    
    
    For connecting Mongo I need following : 
    
    ` <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-mongodb</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-sync</artifactId>
      <scope>runtime</scope>
    </dependency>`
    
    And it appears even micronaut launcher is not allowing both in one: 
    
    
![image](https://github.com/micronaut-projects/micronaut-data/assets/43907358/07d659c0-d461-452b-b358-aa863e0357fb)

**Comment by radovanradic** [comment]
I think this reproduces the issue, uses h2 and mongodb. Calling controller http://localhost:8080/login/create will reproduce the issue.
[mn3-mongo-hibernate.zip](https://github.com/micronaut-projects/micronaut-data/files/12146495/mn3-mongo-hibernate.zip)
Same happens in Micronaut 4 as well as in tests (when transactional = true, and it will find two trans managers).
