### ISSUE TITLE
generated CRUDRepository finder fails on setting connection read-only on postgres DB

### ISSUE THREAD

**Issue by jakobmagiera** [micronaut-projects/micronaut-data#2402]
### Expected Behavior

An auto-implemented read-only method (e. g. findById) should create a read-only transaction by default without throwing an exception.

### Actual Behaviour

The auto-implemented method first creates a connection then tries to modify it to read-only later, which the postgres driver rejects. Stacktrace:

```
Could not set JDBC Connection [HikariProxyConnection@625868084 wrapping org.postgresql.jdbc.PgConnection@7262532a] read-only: Cannot change transaction read-only property in the middle of a transaction.
io.micronaut.data.connection.exceptions.ConnectionException: Could not set JDBC Connection [HikariProxyConnection@625868084 wrapping org.postgresql.jdbc.PgConnection@7262532a] read-only: Cannot change transaction read-only property in the middle of a transaction.
	at app//io.micronaut.data.connection.support.JdbcConnectionUtils.setConnectionReadOnly(JdbcConnectionUtils.java:170)
	at app//io.micronaut.data.connection.support.JdbcConnectionUtils.applyReadOnly(JdbcConnectionUtils.java:75)
	at app//io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.lambda$setupConnection$0(DefaultDataSourceConnectionOperations.java:67)
	at java.base@17.0.7/java.util.Optional.ifPresent(Optional.java:178)
	at app//io.micronaut.data.connection.jdbc.operations.DefaultDataSourceConnectionOperations.setupConnection(DefaultDataSourceConnectionOperations.java:65)
	at app//io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:142)
	at app//io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
	at app//io.micronaut.data.connection.ConnectionOperations.executeRead(ConnectionOperations.java:71)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:765)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:310)
	at app//io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
	at app//io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
	at app//io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
...
Caused by: org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at app//org.postgresql.jdbc.PgConnection.setReadOnly(PgConnection.java:897)
	at app//com.zaxxer.hikari.pool.ProxyConnection.setReadOnly(ProxyConnection.java:410)
	at app//com.zaxxer.hikari.pool.HikariProxyConnection.setReadOnly(HikariProxyConnection.java)
	at app//io.micronaut.data.connection.support.JdbcConnectionUtils.setConnectionReadOnly(JdbcConnectionUtils.java:167)
	... 23 more
```

### Steps To Reproduce

1. Have a Postgrees DB with a simple table
2. Write a CrudRepository that extends io.micronaut.data.repository.CrudRepository using `@JdbcRepository(dialect = Dialect.POSTGRES)`
3. Add a findById method to the repo
4. Call the method in a test

### Environment Information

OS: MacOS VEntura 13.4.1
Java: 17

### Version

4.0.1

**Comment by jakobmagiera** [comment]
Thanks for the quick reply and example! I forgot one detail which is that our tests are transactional=false. However, even with that your tests still pass. I noticed that in org.postgresql.jdbc.PgConnection#setReadOnly the transactionstate is not idel in our case, so I will investigate why that is the case. Any hints appreciated.

**Comment by dstepanov** [comment]
@jakobmagiera What exactly is your use case? Do you use auto-commit false false by default? Did it work in the v3?

**Comment by radovanradic** [comment]
Looks like this example with the same configuration (auto commit false and `@MicronautTest(transactional = false)`) does not have errors in Micronaut 3
[mn3-postgres-readonly-trans.zip](https://github.com/micronaut-projects/micronaut-data/files/12181940/mn3-postgres-readonly-trans.zip)

**Comment by dstepanov** [comment]
The problem will occur with an inner TX that is marked as read only.
