### ISSUE TITLE
Composite keys using EmbeddedId 

### ISSUE THREAD

**Issue by oujesky** [micronaut-projects/micronaut-data#2439]
### Expected Behavior

Queries for repositories for entities with composite keys defined using `@EmbeddedId` and `@Embeddable` generates queries with correct column names.

Example for Micronaut 3.10.0, ANSI dialect:

* `save` -> `INSERT INTO "some_table" ("col","some_column","other_entity_id") VALUES (?,?,?)`
* `findById` -> `SELECT some_entity_."some_column",some_entity_."other_entity_id",some_entity_."col" FROM "some_table" some_entity_ WHERE (some_entity_."some_column" = ? AND some_entity_."other_entity_id" = ?)`
* `findAll` -> `SELECT some_entity_."some_column",some_entity_."other_entity_id",some_entity_."col" FROM "some_table" some_entity_`

In real usage, queries are executed properly

### Actual Behaviour

Same queries generated with Micronaut 4.0.3:

* `save` -> `INSERT INTO "some_table" ("col","primary_key_some_column","primary_key_other_entity_id") VALUES (?,?,?)`
* `findById` -> `SELECT some_entity_."primary_key_some_column",some_entity_."primary_key_other_entity_id",some_entity_."col" FROM "some_table" some_entity_ WHERE (some_entity_."primary_key_some_column" = ? AND some_entity_."primary_key_other_entity_id" = ?)`
* `findAll` -> `SELECT some_entity_."primary_key_some_column",some_entity_."primary_key_other_entity_id",some_entity_."col" FROM "some_table" some_entity_`

Note the extra `primary_key_` prefix in column name, coming from the `@EmbeddedId` annotated field name `primaryKey`

Obviously such query will fail on invalid column name when executed on real DB 

### Steps To Reproduce

1. Create entity class with composite key:

```
@MappedEntity("some_table")
public class SomeEntity {

    @EmbeddedId
    private PrimaryKey primaryKey;

    private String col;

    ...

    @Embeddable
    public record PrimaryKey(
        int someColumn,
        @Relation(Kind.MANY_TO_ONE) OtherEntity otherEntity
    ) {}

}
```

2. Create repository

```
@JdbcRepository(dialect = Dialect.ANSI)
public interface AnsiRepository extends PageableRepository<SomeEntity, SomeEntity.PrimaryKey> {
}
```

3. Check generated queries using a test

```
@MicronautTest
class MicronautDataCompositeTest {


    @Inject
    private BeanContext beanContext;

    @Test
    void testAnsi() {
        var saveQuery = getQueryFor(AnsiRepository.class, "save", SomeEntity.class);
        assertEquals("INSERT INTO \"some_table\" (\"col\",\"some_column\",\"other_entity_id\") VALUES (?,?,?)", saveQuery);

        var loadSingleQuery = getQueryFor(AnsiRepository.class, "findById", SomeEntity.PrimaryKey.class);
        assertEquals("SELECT some_entity_.\"some_column\",some_entity_.\"other_entity_id\",some_entity_.\"col\" FROM \"some_table\" some_entity_ WHERE (some_entity_.\"some_column\" = ? AND some_entity_.\"other_entity_id\" = ?)", loadSingleQuery);

        var loadAllQuery = getQueryFor(AnsiRepository.class, "findAll");
        assertEquals("SELECT some_entity_.\"some_column\",some_entity_.\"other_entity_id\",some_entity_.\"col\" FROM \"some_table\" some_entity_", loadAllQuery);
    }

    private String getQueryFor(Class<? extends CrudRepository<SomeEntity, SomeEntity.PrimaryKey>> repository, String methodName, Class<?>... argumentTypes) {
        var definition = beanContext.getBeanDefinition(repository);
        var method = definition.getRequiredMethod(methodName, argumentTypes);
        return method.stringValue(Query.class).orElse(null);
    }

}
```
Demo project based on Micronaut 3.10.0: [micronaut-data-composite-3.zip](https://github.com/micronaut-projects/micronaut-data/files/12268475/micronaut-data-composite-3.zip)

Demo project based on Micronaut 4.0.3: [micronaut-data-composite-4.zip](https://github.com/micronaut-projects/micronaut-data/files/12268476/micronaut-data-composite-4.zip)

### Environment Information

MacOS 13.3.1
JDK 17.0.4.1

### Version

4.0.3

**Comment by oujesky** [comment]
There seems to be a workaround to annotate the `@EmbeddedId` field with `@MappedProperty(value = "", alias = "")`, i.e.:

```
@MappedEntity("some_table")
public class SomeEntity {

    @EmbeddedId
    // workaround
    @MappedProperty(alias = "", value = "")
    private PrimaryKey primaryKey;

    ...
}
```

With this the queries matches those from Micronaut 3.10.0

**Comment by oujesky** [comment]
Additionally, when mapping explicit query result to an entity class, the fields are mapped wrong as well

```
@JdbcRepository(dialect = Dialect.ANSI)
public interface AnsiRepository extends PageableRepository<SomeEntity, SomeEntity.PrimaryKey> {

    @Query("SELECT * FROM some_table WHERE other_entity_id = :otherEntityId")
    List<SomeEntity> findByOtherEntityId(int otherEntityId);

}
```

Call to the method results in following exception:

```
io.micronaut.data.exceptions.DataAccessException: Error reading object for name [primary_key_other_entity_id] from result set: Unknown label 'primary_key_other_entity_id'. Possible value [some_table.some_column, some_column, some_table.other_entity_id, other_entity_id, col, some_table.col]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.exceptionForColumn(ColumnNameResultSetReader.java:263)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readInt(ColumnNameResultSetReader.java:169)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readInt(ColumnNameResultSetReader.java:43)
	at io.micronaut.data.runtime.mapper.ResultReader.readDynamic(ResultReader.java:112)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readDynamic(ColumnNameResultSetReader.java:69)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.readDynamic(ColumnNameResultSetReader.java:43)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readProperty(SqlResultEntityTypeMapper.java:577)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntityId(SqlResultEntityTypeMapper.java:605)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:426)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntityId(SqlResultEntityTypeMapper.java:603)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:399)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:190)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$1.tryAdvance(DefaultJdbcRepositoryOperations.java:512)
...
```

**Comment by radovanradic** [comment]
Hm, there were not supposed to be changes in this area in Micronaut 4, I think the naming logic was generating the same names always for embedded id. 
I noticed something strange, when this inner `PrimaryKey` record in `micronaut-data-composite-3` sample project was moved to external public class then the test fails the same way as in `micronaut-data-composite-4`. Not sure what happens there.
As for workaround, maybe a bit simpler way could be mapping `PrimaryKey` record like this using `@MappedProperty`:
```
@Embeddable
    public record PrimaryKey(
        @MappedProperty("some_column")
        int someColumn,
        @MappedProperty("other_entity_id")
        @Relation(Kind.MANY_TO_ONE) OtherEntity otherEntity
    ) {}
```

**Comment by radovanradic** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-data/pull/3410 in 5.0.x
