### ISSUE TITLE
JpaSpecificationExecutor findall method GET ERROR

### ISSUE THREAD

**Issue by laifugroup** [micronaut-projects/micronaut-data#2442]
### Expected Behavior

Expecting to properly execute the jpa method and return the queried data.

code：
````
@Repository()
interface UserRepo: PageableRepository<User, Long>, JpaSpecificationExecutor<User> {
}

````

````
@Entity
@Table(name = "user", schema = "\"bot\"")
@Introspected
data class User(
    @Id
    val  id:Long?=null,
    var  name:String?=null,
): Serializable {

}

````

````
package com.example.queryspecification.controlller

import com.example.queryspecification.entity.User
import com.example.queryspecification.repo.UserRepo
import io.micronaut.data.model.Page
import io.micronaut.data.model.Pageable
import io.micronaut.data.repository.jpa.criteria.PredicateSpecification
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import jakarta.inject.Inject
import jakarta.persistence.criteria.CriteriaBuilder
import jakarta.persistence.criteria.Root

@Controller("/query")
class QuerySpecificationDemoController {
    @Inject
    lateinit var userRepo: UserRepo


    @Get(uri="/")
    fun index(): Page<User> {
        val pageable= Pageable.from(1,10)
       return userRepo.findAll(keyEquals("John"),pageable)
    }


    fun keyEquals(key: String?): PredicateSpecification<User> {
        return PredicateSpecification<User> { root: Root<User>, criteriaBuilder: CriteriaBuilder ->
            criteriaBuilder.equal(
                root.get<Any>("key"),
                key
            )
        }
    }
}

````

### Actual Behaviour

website：  http://localhost:8080/query

How should I configure the parameters to be able to get the data queried by jpa?

····

java.lang.IllegalStateException: Cannot determine QueryBuilder
	at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.lambda$preparedQueryForCriteria$0(AbstractSpecificationInterceptor.java:140)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.lambda$preparedQueryForCriteria$1(AbstractSpecificationInterceptor.java:140)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.preparedQueryForCriteria(AbstractSpecificationInterceptor.java:138)
	at io.micronaut.data.runtime.intercept.criteria.FindPageSpecificationInterceptor.intercept(FindPageSpecificationInterceptor.java:64)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.queryspecification.repo.UserRepo$Intercepted.findAll(Unknown Source)
	at com.example.queryspecification.controlller.QuerySpecificationDemoController.index(QuerySpecificationDemoController.kt:23)
	at com.example.queryspecification.controlller.$QuerySpecificationDemoController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
	at io.micronaut.context.DefaultBeanContext$BeanContextExecutionHandle.invoke(DefaultBeanContext.java:4256)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:223)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
	at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:470)
	at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$2(RequestLifecycle.java:146)
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
	at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$4(RequestLifecycle.java:146)
	at io.micronaut.http.server.RequestLifecycle.lambda$runWithFilters$14(RequestLifecycle.java:264)
	at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:308)
	at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
	at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
	at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:242)
	at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
	at io.micronaut.http.filter.FilterRunner.lambda$filterRequest0$3(FilterRunner.java:183)
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
	at io.micronaut.http.filter.FilterRunner.processRequestFilter(FilterRunner.java:272)
	at io.micronaut.http.filter.FilterRunner.filterRequest0(FilterRunner.java:183)
	at io.micronaut.http.filter.FilterRunner.filterRequest(FilterRunner.java:167)
	at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:162)
	at io.micronaut.http.server.RequestLifecycle.runWithFilters(RequestLifecycle.java:281)
	at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:143)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:85)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:220)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:357)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:206)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
····

### Steps To Reproduce

1. git clone https://github.com/laifugroup/queryspecificationDemo

2. run this app

3. access:    http://localhost:8080/query

5. you will get the error message.

### Environment Information

window10
jdk11

### Example Application

https://github.com/laifugroup/queryspecificationDemo

### Version

4.0.3

**Comment by radovanradic** [comment]
@laifugroup It seems you should use `io.micronaut.data.jpa.repository.JpaSpecificationExecutor` as documented [here](https://micronaut-projects.github.io/micronaut-data/latest/guide/#hibernateSpecifications).
So, UserRepo would look like this (complains without `@Transactional` that there is no transaction):
```
package com.example.queryspecification.repo

import com.example.queryspecification.entity.User
import io.micronaut.data.annotation.Repository
import io.micronaut.data.repository.PageableRepository
import io.micronaut.data.jpa.repository.JpaSpecificationExecutor
import io.micronaut.transaction.annotation.Transactional

@Repository
@Transactional
interface UserRepo: PageableRepository<User, Long>, JpaSpecificationExecutor<User> {
}
```
and controller: 
```
package com.example.queryspecification.controlller

import com.example.queryspecification.entity.User
import com.example.queryspecification.repo.UserRepo
import io.micronaut.data.jpa.repository.criteria.Specification
import io.micronaut.data.model.Page
import io.micronaut.data.model.Pageable
import io.micronaut.data.repository.jpa.criteria.PredicateSpecification
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import jakarta.inject.Inject
import jakarta.persistence.criteria.CriteriaBuilder
import jakarta.persistence.criteria.CriteriaQuery
import jakarta.persistence.criteria.Root

@Controller("/query")
class QuerySpecificationDemoController {
    @Inject
    lateinit var userRepo: UserRepo


    @Get(uri="/")
    fun index(): Page<User> {
        val pageable= Pageable.from(1,10)
       return userRepo.findAll(keyEquals("John"),pageable)
    }

    private fun keyEquals(name: String): Specification<User> {
        return Specification { root: Root<User>, _: CriteriaQuery<*>, criteriaBuilder: CriteriaBuilder ->
            criteriaBuilder.equal(
                root.get<String>("name"), name
            )
        }
    }
}
```
That seems to fixes it.

Alternative solution would be explicitly annotating `UserRepo` with
`@RepositoryConfiguration(queryBuilder = JpaQueryBuilder::class)`

Btw, specification compares `key` and should use `name` as user does not have `key` field.

**Comment by laifugroup** [comment]
Thank you for your reply and reminder.

this code is work for me.

``````
@RepositoryConfiguration(queryBuilder = JpaQueryBuilder::class)
``````

The difference between the two JpaSpecificationExecutor is simply too small.
