### ISSUE TITLE
hibernate-reactive 2.0.5 trying to access private methods

### ISSUE THREAD

**Issue by fdittz** [micronaut-projects/micronaut-data#2547]
### Expected Behavior

I've been using micronaut-data-hibernate reactive with micronaut 4.1.1 without issues.

### Actual Behaviour

Once I try to access data I get a illegalAccessError. I believe its due to micronaut-data bom including hibernate-reactive-core 2.0.5.Final. Keeping micronaut-parent in 4.1.3 and downgrading hibernate-reactive-core to 2.0.4.Final works.

java.lang.IllegalAccessError: class org.hibernate.reactive.session.impl.ReactiveSessionImpl tried to access private method 'org.hibernate.query.spi.HqlInterpretation org.hibernate.internal.AbstractSharedSessionContract.interpretHql(java.lang.String, java.lang.Class)' (org.hibernate.reactive.session.impl.ReactiveSessionImpl and org.hibernate.internal.AbstractSharedSessionContract are in unnamed module of loader 'app')
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:368)
	at org.hibernate.reactive.stage.impl.StageSessionImpl.createQuery(StageSessionImpl.java:495)

### Environment Information

Ubuntu 22.04
Amazon Corretto 17

### Version

4.1.3

**Comment by dstepanov** [comment]
Are you forcing any versions of dependencies? Our test suite works fine.

**Comment by fdittz** [comment]
I don't think so, here are my dependencies:
```
<dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>${jackson-dataformat-xml.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-server-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.data</groupId>
            <artifactId>micronaut-data-hibernate-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.kotlin</groupId>
            <artifactId>micronaut-kotlin-runtime</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-oracle-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>${kotlinVersion}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlinVersion}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.beanvalidation</groupId>
            <artifactId>micronaut-hibernate-validator</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.reactor</groupId>
            <artifactId>micronaut-reactor</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.security</groupId>
            <artifactId>micronaut-security-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.security</groupId>
            <artifactId>micronaut-security-oauth2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.serde</groupId>
            <artifactId>micronaut-serde-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micronaut.openapi</groupId>
            <artifactId>micronaut-openapi-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.testresources</groupId>
            <artifactId>micronaut-test-resources-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-lombok</artifactId>
            <version>${kotlinVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-inject-groovy</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.test</groupId>
            <artifactId>micronaut-test-spock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.groovy</groupId>
                    <artifactId>groovy-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>${modelmapper.version}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
    </dependencies>```

**Comment by radovanradic** [comment]
Can you provide an example that reproduces the issue? Since our tests work fine, we need something to validate when new version of hibernate reactive (or orm) is provided.

**Comment by fdittz** [comment]
Sure, I extracted a minimal part of our project to https://github.com/fdittz/hibernate.git
just run `mvn test` and it will thrown the exception:
```
java.lang.IllegalAccessError: class org.hibernate.reactive.session.impl.ReactiveSessionImpl tried to access private method 'org.hibernate.query.spi.HqlInterpretation org.hibernate.internal.AbstractSharedSessionContract.interpretHql(java.lang.String, java.lang.Class)' (org.hibernate.reactive.session.impl.ReactiveSessionImpl and org.hibernate.internal.AbstractSharedSessionContract are in unnamed module of loader 'app')
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:368)
	at org.hibernate.reactive.stage.impl.StageSessionImpl.createQuery(StageSessionImpl.java:495)
	at io.micronaut.data.hibernate.reactive.operations.DefaultHibernateReactiveRepositoryOperations.createQuery(DefaultHibernateReactiveRepositoryOperations.java:182)
	at io.micronaut.data.hibernate.reactive.operations.DefaultHibernateReactiveRepositoryOperations.createQuery(DefaultHibernateReactiveRepositoryOperations.java:65)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.collectResults(AbstractHibernateOperations.java:363)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.collectFindOne(AbstractHibernateOperations.java:287)
	at io.micronaut.data.hibernate.reactive.operations.DefaultHibernateReactiveRepositoryOperations.lambda$findOne$2(DefaultHibernateReactiveRepositoryOperations.java:197)
	at io.micronaut.data.hibernate.reactive.operations.DefaultHibernateReactiveRepositoryOperations.lambda$operation$20(DefaultHibernateReactiveRepositoryOperations.java:368)
	at io.micronaut.transaction.support.AbstractReactorTransactionOperations.executeCallbackMono(AbstractReactorTransactionOperations.java:255)
	at io.micronaut.data.hibernate.reactive.operations.DefaultHibernateReactorTransactionOperations.lambda$executeTransactionMono$1(DefaultHibernateReactorTransactionOperations.java:83)
	at io.micronaut.data.hibernate.reactive.operations.ReactiveHibernateHelper.lambda$withTransactionMono$11(ReactiveHibernateHelper.java:115)
	at org.hibernate.reactive.stage.impl.StageSessionImpl$Transaction.executeInTransaction(StageSessionImpl.java:394)
	at org.hibernate.reactive.stage.impl.StageSessionImpl$Transaction.lambda$execute$0(StageSessionImpl.java:384)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:536)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:184)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
	at io.vertx.oracleclient.impl.commands.OracleCommand.fireResponse(OracleCommand.java:90)
	at io.vertx.oracleclient.impl.OracleJdbcConnection.lambda$actionComplete$7(OracleJdbcConnection.java:263)
	at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81)
	at io.vertx.oracleclient.impl.OracleJdbcConnection.actionComplete(OracleJdbcConnection.java:262)
	at io.vertx.oracleclient.impl.OracleJdbcConnection.lambda$checkPending$5(OracleJdbcConnection.java:197)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Transformation$1.onSuccess(Transformation.java:63)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.Transformation.onSuccess(Transformation.java:44)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
