### ISSUE TITLE
Cannot update autopopulated property via custom query

### ISSUE THREAD

**Issue by radovanradic** [micronaut-projects/micronaut-data#2575]
### Expected Behavior

Having an entity with autopopulated field 
```
@MappedEntity
public class Entity {

    @Id
    private Long id;

    @AutoPopulated
    private UUID customId;

    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getCustomId() {
        return customId;
    }

    public void setCustomId(UUID customId) {
        this.customId = customId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```
and repository
```
@JdbcRepository(dialect = Dialect.H2)
public interface Repository extends CrudRepository<Entity, Long> {

    void updateCustomId(@Id Long id, UUID customId);
}
```
should be able to update `customId` by calling `repository.updateCustomId(entity.getId(), UUID.randomUUID());`

### Actual Behaviour

An exception is thrown:
> Cannot auto populate property: customId for entity: com.example.Entity
java.lang.IllegalStateException: Cannot auto populate property: customId for entity: com.example.Entity
	at io.micronaut.data.runtime.support.DefaultRuntimeEntityRegistry.autoPopulateRuntimeProperty(DefaultRuntimeEntityRegistry.java:99)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$JdbcParameterBinder.autoPopulateRuntimeProperty(DefaultJdbcRepositoryOperations.java:1024)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersStoredQuery.bindParameter(DefaultBindableParametersStoredQuery.java:122)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersStoredQuery.bindParameters(DefaultBindableParametersStoredQuery.java:85)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersPreparedQuery.bindParameters(DefaultBindableParametersPreparedQuery.java:82)
	at io.micronaut.data.runtime.operations.internal.query.BindableParametersPreparedQuery.bindParameters(BindableParametersPreparedQuery.java:51)

### Steps To Reproduce

Extract application 
[mn-update-autopopulated.zip](https://github.com/micronaut-projects/micronaut-data/files/13070787/mn-update-autopopulated.zip)
and run `RepositoryTest.testUpdate`

### Environment Information

Any

### Version

4.1.5

**Comment by radovanradic** [comment]
This might be mapping/config issue. If we want to use field and update manually then can mark `@AutoPopulated(updateable = false)`. Seems anyway it's not the usual way to use the annotation, closing now.
