### ISSUE TITLE
Entity field type information is not available to custom Hibernate types when using mapping resources

### ISSUE THREAD

**Issue by aaronjwhiteside** [micronaut-projects/micronaut-data#2632]
### Expected Behavior

I should be able to define my mapping using a hbm file and reference a custom type and everything should just work..

```xml
<hibernate-mapping package="com.example">
    <class name="Entity" table="entity">
        <id name="id"/>
        <property name="json">
            <column name="json" sql-type="json"/>
            <type name="io.hypersistence.utils.hibernate.type.json.JsonType"/>
        </property>
    </class>
</hibernate-mapping>
```

### Actual Behaviour

```
Message: Could not resolve property type!
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder]) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([Metadata metadata],JpaConfiguration jpaConfiguration,String name)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)

	...
Caused by: org.hibernate.HibernateException: Could not resolve property type!
	at app//io.hypersistence.utils.hibernate.type.json.internal.JsonJavaTypeDescriptor.setParameterValues(JsonJavaTypeDescriptor.java:87)
	at app//io.hypersistence.utils.hibernate.type.MutableDynamicParameterizedType.setParameterValues(MutableDynamicParameterizedType.java:32)
	at app//org.hibernate.mapping.MappingHelper.injectParameters(MappingHelper.java:111)
	at app//org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:164)
	at app//org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:124)
	at app//org.hibernate.boot.model.TypeDefinition.resolve(TypeDefinition.java:109)
	at app//org.hibernate.mapping.BasicValue.interpretExplicitlyNamedType(BasicValue.java:662)
	at app//org.hibernate.mapping.BasicValue.buildResolution(BasicValue.java:374)
	at app//org.hibernate.mapping.BasicValue.resolve(BasicValue.java:310)
	at app//org.hibernate.mapping.BasicValue.resolve(BasicValue.java:300)
	at app//org.hibernate.boot.internal.InFlightMetadataCollectorImpl.lambda$processValueResolvers$4(InFlightMetadataCollectorImpl.java:1855)
	at java.base@17.0.9/java.util.ArrayList.removeIf(ArrayList.java:1682)
	at java.base@17.0.9/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at app//org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processValueResolvers(InFlightMetadataCollectorImpl.java:1854)
	at app//org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1840)
	at app//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:331)
	at app//org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:128)
	at app//org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:451)
	at app//org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:102)
	at app//org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:209)
	at app//io.micronaut.configuration.hibernate.jpa.conf.AbstractHibernateFactory.buildMetadata(AbstractHibernateFactory.java:92)
	at app//io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory.buildMetadata(SessionFactoryPerDataSourceFactory.java:90)
	at app//io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildMetadata2$Definition.doInstantiate(Unknown Source)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.instantiate(AbstractInitializableBeanDefinition.java:774)
	at app//io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:156)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
	... 123 more
```

### Steps To Reproduce

See attached project, run `DemoTest`
[demo 3.zip](https://github.com/micronaut-projects/micronaut-data/files/13330770/demo.3.zip)

### Environment Information

MacOS
JDK 17

### Version

Micronaut Platform: 4.1.6

**Comment by radovanradic** [comment]
Looks like hbm is missing parameter type
```
<type name="io.hypersistence.utils.hibernate.type.json.JsonType">
  <param name="org.hibernate.type.ParameterType">java.lang.String</param>
</type>
```
after this the type is resolved.
Not sure why, another error then pops up telling 
> Could not locate setter method for property [com.example.Entity#id]

and then when changed Entity to 
```
@Entity
data class Entity(
    @Id 
    var id: String,
    var json: List<String>
)
```
this test is passing
```
@MicronautTest
class DemoTest(
    private val application: EmbeddedApplication<*>,
    private val repository: EntityRepository
): StringSpec({

    "test the server is running" {
        assert(application.isRunning)
    }

    "test the repository" {
        val id = UUID.randomUUID().toString()
        val data = listOf("elem1", "elem2")
        val entity = Entity(id, data)
        repository.save(entity)
        val opt = repository.findById(id)
        assert(opt.isPresent)
        assert(opt.get().id == id)
        assert(opt.get().json == data)
    }
})
```

**Comment by aaronjwhiteside** [comment]
Thanks @radovanradic, I had wrongly assumed that micronaut was doing something wrong here, by not making available the right class metadata (reflection), but this issue seems to be hibernate + hypersistence related.

I had oversimplified my example, in my real code I use a `List<CustomType>` instead of a list of `List<String>`, but changing my configuration to the following seems to have fixed the issue.

```xml
    <type name="io.hypersistence.utils.hibernate.type.json.JsonType">
        <param name="org.hibernate.type.ParameterType">java.util.List</param>
    </type>
```

I think somehow hibernate/hypersistence is picking up the generic type of the field a bit later on? *shrug* - it seems to work.

**Comment by aaronjwhiteside** [comment]
Closing issue as its not related to micronaut data

**Comment by aaronjwhiteside** [comment]
Closing issue as its not related to micronaut data

**Comment by aaronjwhiteside** [comment]
Actually I think I spoke too soon, the hibernate first level cache seems to be causing my test to pass by returning the exact same instance I persisted in a later findById() call, but still this is not a micronaut issue.. 

Thanks again.
