### ISSUE TITLE
JPA: how to get page,but no hope excute count() method to get total number

### ISSUE THREAD

**Issue by laifugroup** [micronaut-projects/micronaut-data#2697]
### Issue description

now,i use code      get the Page object. it is ok.
 ````
    @Override
    Mono<Page<T>> findAll(PredicateSpecification<T> spec, Pageable pageable);

````

    when my database have big data. i want findAll method igore count() 
    
    I dont find like this api:

 ````
   @Override
    Mono<Slice<T>> findAll(PredicateSpecification<T> spec, Pageable pageable);
 ````
    
    i try do custom interceptor ：
    
 ````
    import io.micronaut.data.intercept.annotation.DataMethod
import io.micronaut.data.model.Page
import io.micronaut.data.model.Pageable
import io.micronaut.data.model.Slice
import io.micronaut.data.repository.jpa.criteria.PredicateSpecification
import io.micronaut.data.repository.jpa.criteria.QuerySpecification
import io.micronaut.data.repository.jpa.reactive.ReactorJpaSpecificationExecutor
import io.micronaut.data.runtime.intercept.criteria.reactive.FindPageReactiveSpecificationInterceptorExt
import reactor.core.publisher.Mono

interface ReactiveStreamsBaseSpecificationExecutor<T> : ReactorJpaSpecificationExecutor<T> {


    //run ok
    fun list(pageable: Pageable): Mono<Slice<T>>

    //run  error
    @DataMethod(interceptor = FindPageReactiveSpecificationInterceptorExt::class)
     fun findSlice(spec: PredicateSpecification<T>, pageable: Pageable): Mono<Page<T>>
}
````

FindPageReactiveSpecificationInterceptorExt
````
package io.micronaut.data.runtime.intercept.criteria.reactive;

import io.micronaut.aop.MethodInvocationContext;
import io.micronaut.core.async.publisher.Publishers;
import io.micronaut.data.intercept.RepositoryMethodKey;
import io.micronaut.data.model.Page;
import io.micronaut.data.model.Pageable;
import io.micronaut.data.model.runtime.PreparedQuery;
import io.micronaut.data.operations.RepositoryOperations;
import io.micronaut.data.runtime.intercept.criteria.reactive.AbstractReactiveSpecificationInterceptor;
import io.micronaut.data.runtime.intercept.criteria.reactive.FindPageReactiveSpecificationInterceptor;
import jakarta.inject.Singleton;
import org.reactivestreams.Publisher;
import reactor.core.publisher.Flux;

@Singleton
public class FindPageReactiveSpecificationInterceptorExt extends AbstractReactiveSpecificationInterceptor<Object, Object> {
    /**
     * Default constructor.
     *
     * @param operations The operations
     */
    protected FindPageReactiveSpecificationInterceptorExt(RepositoryOperations operations) {
        super(operations);
    }

    public Object intercept(RepositoryMethodKey methodKey, MethodInvocationContext<Object, Object> context) {
        if (context.getParameterValues().length != 2) {
            throw new IllegalStateException("Expected exactly 2 arguments to method");
        }

        Publisher<?> result;

        Pageable pageable = getPageable(context);
        if (pageable.isUnpaged()) {
            PreparedQuery<?, ?> preparedQuery = preparedQueryForCriteria(methodKey, context, Type.FIND_PAGE);
            Flux<?> results = Flux.from(reactiveOperations.findAll(preparedQuery));
            result = results.collectList().map(resultList -> Page.of(resultList, pageable, resultList.size()));
        } else {
            PreparedQuery<?, ?> preparedQuery = preparedQueryForCriteria(methodKey, context, Type.FIND_PAGE);
            result = Flux.from(reactiveOperations.findAll(preparedQuery))
                    .collectList()
            ;
        }
        return Publishers.convertPublisher(conversionService, result, context.getReturnType().getType());

    }
}


 ````

but，get error

 ````
java.lang.IllegalStateException: Micronaut Data Interceptor [io.micronaut.data.runtime.intercept.criteria.reactive.FindPageReactiveSpecificationInterceptorExt] is not on the classpath but required by the method: Mono findSlice(PredicateSpecification spec,Pageable pageable)
	at io.micronaut.data.runtime.intercept.DataInterceptorResolver.findDataInterceptor(DataInterceptorResolver.java:109)
	at io.micronaut.data.runtime.intercept.DataInterceptorResolver.resolve(DataInterceptorResolver.java:77)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:75)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)

 ````

**Comment by dstepanov** [comment]
It needs to be `@Introspected`

**Comment by laifugroup** [comment]
who need @Introspected？   FindPageReactiveSpecificationInterceptorExt ？

**Comment by laifugroup** [comment]
close this issuse.
the reson is my project is a kotlin project. kotlin compiler will rename the source.java to  another name.
