### ISSUE TITLE
micronaut ignores GenerationType.SEQUENCE and generates invalid insert statements

### ISSUE THREAD

**Issue by witi83** [micronaut-projects/micronaut-data#273]
### Steps to Reproduce

1. Create an entity with the following ID:
```java
    @Id
    @SequenceGenerator(name = "mySeq", sequenceName = "MY_SEQ", initialValue = 3)
    @GeneratedValue(generator = "mySeq", strategy = GenerationType.SEQUENCE)
    private Long id;
```
2. Using an h2 database create a schema: `CREATE SEQUENCE MY_SEQ MINVALUE 1 MAXVALUE 99999 INCREMENT BY 2 START WITH 3 NOCACHE NOCYCLE;` and import it as follows: `url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'`

3. Implement a `CrudRepository`, e.g. `public interface UserRepository extends CrudRepository<User, Long>`
4. Implement a create-method in a controller, e.g. `@Post User create(String name) { return repo.save(new User(name)); }`
5. Call this interface-method. With httpie: `http POST localhost:8080/users name=John`

### Expected Behaviour

An entity with `ID=3` should be created.

### Actual Behaviour

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column count does not match; SQL statement:
INSERT INTO `users` (`name`,`id`) VALUES (?) [21002-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.message.DbException.get(DbException.java:170)
        at org.h2.command.dml.Insert.prepare(Insert.java:314)
        at org.h2.command.Parser.prepareCommand(Parser.java:689)
        at org.h2.engine.Session.prepareLocal(Session.java:627)
        at org.h2.engine.Session.prepareCommand(Session.java:565)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1211)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy29.prepareStatement(Unknown Source)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persistOne$9(DefaultJdbcRepositoryOperations.java:508)
```

As you can see, an invalid insert statement was generated, no value for id was provided: ```INSERT INTO `users` (`name`,`id`) VALUES (?)```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.6
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

### Example Application

https://github.com/witi83/micronaut-data-sequence-issue

**Comment by graemerocher** [comment]
The issue is that Micronaut JDBC doesn't currently support the JPA sequence annotations. You can use:

```java
@GeneratedValue(ref="MY_SEQ", value=GeneratedValue.TYPE.SEQUENCE)
```

or

```
@GeneratedValue(definition="CREATE SEQUENCE "MY_SEQ" MINVALUE 1 START WITH 3")
```
