### ISSUE TITLE
Build fails when mapping composite key with OneToMany annotation

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#277]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

When mapping master-detail relationships based on a composite detail key the `mappedBy` value of the JPA annotation `@OneToMany` causes an exeception during the build. Using the micronaut-data annotation `@Relation` works and can be used as a workaround.

### Expected Behaviour

Parsing an annotation like `@OneToMany(mappedBy = "id.template")` should work (example: the anwser to this question: https://stackoverflow.com/questions/23066432/) .

### Actual Behaviour

Build fails with message _Unable to enhance class: ...;_. Runing with `--stacktrace` yields

```java
Caused by: org.gradle.api.GradleException: Unable to enhance class : ...
        at org.hibernate.orm.tooling.gradle.HibernatePlugin.doEnhancement(HibernatePlugin.java:183)                                                                             
        at org.hibernate.orm.tooling.gradle.HibernatePlugin.access$300(HibernatePlugin.java:46)                                                                                 
        at org.hibernate.orm.tooling.gradle.HibernatePlugin$2.execute(HibernatePlugin.java:132)                                                                                 
        at org.hibernate.orm.tooling.gradle.HibernatePlugin$2.execute(HibernatePlugin.java:80)                                                                                  
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)                                                                                
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)                                                                                
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)                                                        
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)                            
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)                            
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)                                                       
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)                                                         
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)                                                         
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)                                                              
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)                                                        
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)                                                
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)                                               
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)                                                    
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)                                        
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)                                                                                
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)                                                                                         
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)                                                                                         
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)                                                                           
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)                                                                           
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)                                                                 
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)                                                                 
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)                                                                         
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)                                                                           
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)                                                                                         
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)                                                                           
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)                                                                             
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)                                                                         
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)                                                                         
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)                                                                                
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)                                                                                             
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)                                                                                             
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)                                                       
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)                                                                           
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)                                                                           
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)                                                                             
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)                                                                             
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)                                                                        
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)                                                                      
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)                                                                               
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)                                                                               
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)                                                                           
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)                                                                           
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)                                    
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)                                    
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)                                                                 
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)                                                                 
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)                                                 
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)                                                 
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)                                                                          
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)                                                      
        ... 34 more                                                                                                                                                             
Caused by: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class ...                                                       
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:138)                                                                        
        at org.hibernate.orm.tooling.gradle.HibernatePlugin.doEnhancement(HibernatePlugin.java:180)                                                                             
        ... 87 more                                                                                                                                                             
Caused by: java.lang.IllegalStateException: Could not locate field                                                                                                              
        at net.bytebuddy.dynamic.scaffold.FieldLocator$Resolution$Illegal.getField(FieldLocator.java:90)                                                                        
        at org.hibernate.bytecode.enhance.internal.bytebuddy.BiDirectionalAssociationHandler.wrap(BiDirectionalAssociationHandler.java:70)                                      
        at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.fieldWriter(PersistentAttributeTransformer.java:255)                                
        at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.applyTo(PersistentAttributeTransformer.java:199)                                    
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:288)                                                                      
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:132)                                                               
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:141)                                                                            
        at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:132)                                                                        
        ... 88 more                                                                                                                                                             
```

### Environment Information

- **Micronaut Version:** 1.2.6, data 1.0.0.M5
- **JDK Version:** 8

**Comment by graemerocher** [comment]
this seems unrelated to Micronaut Data and a possible bug in the hibernate build time enhancement. Please report the issue to https://hibernate.atlassian.net/projects/HHH/issues

**Comment by esocode** [comment]
Based on the stacktrace I first thought the same. But why do the JPA `@OneToMany` and Micronaut `@Relation` annotations behave differently then? Is Hibernate processing initiated earlier for JPA annotations?

**Comment by graemerocher** [comment]
The `@Relation` annotations only apply to Micronaut JDBC
