### ISSUE TITLE
NoSuchBeanException: No bean of type [org.hibernate.boot.SessionFactoryBuilder] exists for the given qualifier: @Named('default')

### ISSUE THREAD

**Issue by stanleyw2014** [micronaut-projects/micronaut-data#2891]
### Expected Behavior

micronaut can be started normally

### Actual Behaviour

micronaut can't be started due be exception : NoSuchBeanException: No bean of type [org.hibernate.boot.SessionFactoryBuilder] exists for the given qualifier: @Named('default')

And the most strange thing is that sometimes the application can be started normally, and sometimes will fail with the exception, without any changes...Is that possible the atp database is not stable?

the content of application.properties file:
micronaut.application.name=messaging-api
kafka.bootstrap.servers=localhost:9092

micronaut.http.client.read-timeout=45s
micronaut.http.client.connect-timeout=45s

micronaut.executors.io.type=fixed
micronaut.executors.io.nThreads=75
micronaut.server.cors.enabled=true
oci.config.profile=DEFAULT
datasources.default.dialect=ORACLE
datasources.default.ocid=ocid1.autonomousdatabase.oc1.eu-frankfurt-1.xxxxxxxxxxxxxxxxxxxx
datasources.default.walletPassword=xxxxxxxxxx
datasources.default.username=xxxxx
datasources.default.password=xxxxxxx
datasources.default.driverClassName=oracle.jdbc.OracleDriver

Full stacktrace:
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Failed to inject value for parameter [sessionFactoryBuilder] of method [buildHibernateSessionFactoryBuilder] of class: io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory

Message: No bean of type [org.hibernate.boot.SessionFactoryBuilder] exists for the given qualifier: @Named('default'). 
* [SessionFactoryBuilder] requires the presence of a bean of type [org.hibernate.boot.Metadata] with qualifier [@Named('default')].
 * [Metadata] requires the presence of a bean of type [org.hibernate.boot.MetadataSources] with qualifier [@Named('default')].
  * [MetadataSources] requires the presence of a bean of type [org.hibernate.service.ServiceRegistry] with qualifier [@Named('default')].
   * [ServiceRegistry] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('default')].
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.ucp.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder])
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
	at app//io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
	at app//io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
	at app//io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
	at app//io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
	at app//io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:502)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:341)
	at app//io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at java.base@17.0.8/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [sessionFactoryBuilder] of method [buildHibernateSessionFactoryBuilder] of class: io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory

Message: No bean of type [org.hibernate.boot.SessionFactoryBuilder] exists for the given qualifier: @Named('default'). 
* [SessionFactoryBuilder] requires the presence of a bean of type [org.hibernate.boot.Metadata] with qualifier [@Named('default')].
 * [Metadata] requires the presence of a bean of type [org.hibernate.boot.MetadataSources] with qualifier [@Named('default')].
  * [MetadataSources] requires the presence of a bean of type [org.hibernate.service.ServiceRegistry] with qualifier [@Named('default')].
   * [ServiceRegistry] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('default')].
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.ucp.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder])
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2181)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at app//io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildHibernateSessionFactoryBuilder4$Definition.instantiate(Unknown Source)
	at app//io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
	at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
	at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
	at app//io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
	at app//io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at app//io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
	at app//io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
	at app//io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
	... 9 more
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.hibernate.boot.SessionFactoryBuilder] exists for the given qualifier: @Named('default'). 
* [SessionFactoryBuilder] requires the presence of a bean of type [org.hibernate.boot.Metadata] with qualifier [@Named('default')].
 * [Metadata] requires the presence of a bean of type [org.hibernate.boot.MetadataSources] with qualifier [@Named('default')].
  * [MetadataSources] requires the presence of a bean of type [org.hibernate.service.ServiceRegistry] with qualifier [@Named('default')].
   * [ServiceRegistry] requires the presence of a bean of type [javax.sql.DataSource] with qualifier [@Named('default')].
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
    * [DataSource] requires the presence of a bean of type [io.micronaut.configuration.jdbc.ucp.DatasourceConfiguration] with qualifier [@Named('default')].
     * [DatasourceConfiguration] is disabled because:
      - Configuration requires entries under the prefix: [datasources.default]
	at app//io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2787)
	at app//io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:307)
	at app//io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2756)
	at app//io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
	at app//io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at app//io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)

### Steps To Reproduce

build a micronaut project with above properties file
start will failed
below is dependencies in build.gradle:
dependencies {
    
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut:micronaut-inject-java")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut.discovery:micronaut-discovery-client")
    implementation("io.micronaut.cache:micronaut-cache-caffeine")
    implementation("com.oracle.oci.log:oci-logging-lib:${oci_logging_version}") {
        exclude group: 'io.dropwizard', module: 'dropwizard-core'
    }
   
    implementation("io.micronaut.kafka:micronaut-kafka")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-http-client-core")
    implementation("org.json:json:20240303")
    runtimeOnly("ch.qos.logback:logback-classic")

    compileOnly("io.micronaut.data:micronaut-data-processor")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut.data:micronaut-data-jdbc")
    implementation("io.micronaut.flyway:micronaut-flyway")
    implementation("io.micronaut.groovy:micronaut-runtime-groovy")
    implementation("io.micronaut.oraclecloud:micronaut-oraclecloud-atp")
    implementation("io.micronaut.oraclecloud:micronaut-oraclecloud-sdk")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa")
    compileOnly("io.micronaut:micronaut-http-validation")
    compileOnly("io.micronaut.serde:micronaut-serde-processor")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("org.flywaydb:flyway-database-oracle")

}

### Environment Information

macos 13.6.6
jdk17

### Version

4.3.1

**Comment by stanleyw2014** [comment]
I run about 10 tests, 8 times of them failed due to above exception, and 2 times of them succeed, no code change between the failed and succeed tests. I connect to atp database remotely from my laptop.

**Comment by graemerocher** [comment]
attach an example that reproduces the issue

**Comment by stanleyw2014** [comment]
the whole project in zip?

**Comment by stanleyw2014** [comment]
there is some sensitive info such as password in application.properties file

**Comment by graemerocher** [comment]
If you are internal to Oracle, reach out to me internally at Oracle and we will create an internal ticket to track this

**Comment by radovanradic** [comment]
Since there is jdbc-hikari dependency added `implementation("io.micronaut.sql:micronaut-jdbc-hikari")`, I noticed there is also jdbc-ucp transitive dependency and tried to exclude it from build.gradle
```
implementation("com.oracle.engage.foundation:engage-foundation:${engage_foundation_version}") {
        exclude group: 'ch.qos.logback', module: 'logback-classic'
        exclude group: "io.micronaut.sql", module: "micronaut-jdbc-ucp"
    }
```
seems to fix the issue. Not sure if this is valid solution for you, but I am not getting random ucp connection issues or hibernate bean not found after that.

**Comment by stanleyw2014** [comment]
thansk Radovan, the issue is fixed, close this issue.
