### ISSUE TITLE
Migrating from 4.2.4 to 4.6.3 results in no identity returned from RuntimePersistentEntity.getIdentity()

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-data#3166]
### Expected Behavior

RuntimePersistentEntity.getIdentity() returns a non-null, valid value.

### Actual Behaviour

An assertion in our repository implementation, `DefaultCoherenceRepositoryOperations.getId(T entity)` fails as `getIdentity()` is returning `null`

### Steps To Reproduce

1.  Check out the mn-4.6.3 branch from https://github.com/oracle/coherence-micronaut-sockshop-sample
2. Run test `CoherenceCatalogRepositoryTest` (any of them) in the catalog module
3. Observe failure:

```
Caused by: java.lang.AssertionError: null
	at io.micronaut.coherence.data.ops.DefaultCoherenceRepositoryOperations.getId(DefaultCoherenceRepositoryOperations.java:179)
	at io.micronaut.coherence.data.interceptors.GetIdInterceptor.intercept(GetIdInterceptor.java:52)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
	at com.oracle.coherence.examples.sockshop.micronaut.catalog.CoherenceCatalogRepository$Intercepted.getIdInternal(Unknown Source)
	at io.micronaut.coherence.data.AbstractCoherenceRepository.getId(AbstractCoherenceRepository.java:52)
	at com.oracle.coherence.repository.AbstractRepository.save(AbstractRepository.java:79)
	at io.micronaut.coherence.data.AbstractCoherenceRepository.save(AbstractCoherenceRepository.java:63)
	at com.oracle.coherence.examples.sockshop.micronaut.catalog.CoherenceCatalogRepository$Intercepted.$$access$$save(Unknown Source)
	at com.oracle.coherence.examples.sockshop.micronaut.catalog.$CoherenceCatalogRepository$Intercepted$Definition$Exec.dispatch(Unknown Source)
```

### Environment Information

MacOS 14.7 (Apple Silicon)
JDK 17.0.11

### Example Application

https://github.com/oracle/coherence-micronaut-sockshop-sample

### Version

4.6.3

**Comment by radovanradic** [comment]
Looks like the issue is with Lombok. If `Sock` class is delomboked then the issue does not occur. If class uses Lombok, then it seems the issue is with annotation processor ordering - Lombok must come first. Changing `annotationProcessorPaths` in catalog module pom.xml (and other modules as well) to this also resolves the issue
```
<annotationProcessorPaths combine.self="override">
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${version.lib.lombok}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut.coherence</groupId>
                            <artifactId>micronaut-coherence-data</artifactId>
                            <version>${micronaut.coherence.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut.openapi</groupId>
                            <artifactId>micronaut-openapi</artifactId>
                            <version>${micronaut.openapi.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut</groupId>
                            <artifactId>micronaut-inject-java</artifactId>
                            <version>${micronaut.core.version}</version>
                        </path>
                        <path>
                            <groupId>io.micronaut.validation</groupId>
                            <artifactId>micronaut-validation</artifactId>
                            <version>${micronaut.validation.version}</version>
                        </path>
                    </annotationProcessorPaths>
```
Btw, locally I am getting the same error with 4.2.4 as well as 4.6.3. Not sure how it worked before, but according to this section 
```
Micronaut Data and Lombok

If you intend to use Lombok with Micronaut Data then you must place the Lombok annotation processor before the Micronaut processors in your build configuration since Micronaut needs to see the mutations to the AST that Lombok applies.
```
in https://micronaut-projects.github.io/micronaut-data/latest/guide/#buildConfig Lombok annotation processor must come before other annotation processors.
Cc @dstepanov

**Comment by dstepanov** [comment]
Lombok needs to be defined before any Micronaut annotation processors.
