### ISSUE TITLE
jpa findall method get org.hibernate.sql.ast.SqlTreeCreationException: Could not locate TableGroup 

### ISSUE THREAD

**Issue by easy-agent-skills** [micronaut-projects/micronaut-data#3204]
### Expected Behavior

 val result= platformRepo.findAll(spec, Pageable.from(0, 10))
just use this method will get a error:
rg.hibernate.sql.ast.SqlTreeCreationException: Could not locate TableGroup

error position:

io.micronaut.data.runtime.intercept.criteria.FindPageSpecificationInterceptor.java
````
   if (pageable.requestTotal()) {
            count = count(methodKey, context);
        }
````

### Actual Behaviour

22:43:44.569 [default-nioEventLoopGroup-1-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Could not locate TableGroup - com.example.demo.domain.po.LuckPlatformPO(3880944043100)
org.hibernate.sql.ast.SqlTreeCreationException: Could not locate TableGroup - com.example.demo.domain.po.LuckPlatformPO(3880944043100)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.prepareReusablePath(BaseSqmToSqlAstConverter.java:3703)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.prepareReusablePath(BaseSqmToSqlAstConverter.java:3646)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.prepareReusablePath(BaseSqmToSqlAstConverter.java:3630)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitBasicValuedPath(BaseSqmToSqlAstConverter.java:4298)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitBasicValuedPath(BaseSqmToSqlAstConverter.java:445)
	at org.hibernate.query.sqm.tree.domain.SqmBasicValuedSimplePath.accept(SqmBasicValuedSimplePath.java:145)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitComparisonPredicate(BaseSqmToSqlAstConverter.java:7549)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitComparisonPredicate(BaseSqmToSqlAstConverter.java:445)
	at org.hibernate.query.sqm.tree.predicate.SqmComparisonPredicate.accept(SqmComparisonPredicate.java:111)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitJunctionPredicate(BaseSqmToSqlAstConverter.java:7209)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitJunctionPredicate(BaseSqmToSqlAstConverter.java:445)
	at org.hibernate.query.sqm.tree.predicate.SqmJunctionPredicate.accept(SqmJunctionPredicate.java:74)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitWhereClause(BaseSqmToSqlAstConverter.java:2484)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitQuerySpec(BaseSqmToSqlAstConverter.java:2080)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitQuerySpec(BaseSqmToSqlAstConverter.java:445)
	at org.hibernate.query.sqm.tree.select.SqmQuerySpec.accept(SqmQuerySpec.java:122)
	at org.hibernate.query.sqm.spi.BaseSemanticQueryWalker.visitQueryPart(BaseSemanticQueryWalker.java:244)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitQueryPart(BaseSqmToSqlAstConverter.java:1934)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitSelectStatement(BaseSqmToSqlAstConverter.java:1619)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitSelectStatement(BaseSqmToSqlAstConverter.java:445)
	at org.hibernate.query.sqm.tree.select.SqmSelectStatement.accept(SqmSelectStatement.java:234)
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.translate(BaseSqmToSqlAstConverter.java:784)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:422)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:328)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:302)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:526)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:423)
	at org.hibernate.query.spi.AbstractSelectionQuery.uniqueResult(AbstractSelectionQuery.java:549)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$24(HibernateJpaOperations.java:645)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$executeRead$21(HibernateJpaOperations.java:567)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.lambda$execute$2(AbstractPropagatedStatusTransactionOperations.java:68)
	at io.micronaut.transaction.TransactionCallback.apply(TransactionCallback.java:37)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeTransactional(AbstractTransactionOperations.java:333)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeWithNewTransaction(AbstractTransactionOperations.java:318)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeNew(AbstractTransactionOperations.java:235)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:137)
	at io.micronaut.transaction.support.AbstractTransactionOperations.lambda$doExecute$0(AbstractTransactionOperations.java:122)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:143)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:120)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.execute(AbstractPropagatedStatusTransactionOperations.java:65)
	at io.micronaut.transaction.TransactionOperations.executeRead(TransactionOperations.java:76)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.executeRead(HibernateJpaOperations.java:567)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:645)
	at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.count(AbstractSpecificationInterceptor.java:178)
	at io.micronaut.data.runtime.intercept.criteria.FindPageSpecificationInterceptor.intercept(FindPageSpecificationInterceptor.java:60)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
	at com.example.demo.repo.PlatformRepo$Intercepted.findAll(Unknown Source)
	at com.example.demo.JpaFindallQuestionController.index(JpaFindallQuestionController.kt:23)
	at com.example.demo.$JpaFindallQuestionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4350)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:231)
	at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:38)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:498)
	at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:488)
	at io.micronaut.http.server.RequestLifecycle.callRoute(RequestLifecycle.java:182)
	at io.micronaut.http.server.RequestLifecycle.executeRoute(RequestLifecycle.java:170)
	at io.micronaut.http.server.RequestLifecycle$2.provideResponse(RequestLifecycle.java:390)
	at io.micronaut.http.filter.FilterRunner.run(FilterRunner.java:245)
	at io.micronaut.http.server.RequestLifecycle.runServerFilters(RequestLifecycle.java:422)
	at io.micronaut.http.server.RequestLifecycle.normalFlow(RequestLifecycle.java:160)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:93)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:235)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.accept(NettyServerWebSocketUpgradeHandler.java:156)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:415)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpRequestChannelRead(WebSocketServerExtensionHandler.java:158)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### Environment Information

windows 
jdk21

### Example Application

https://github.com/laifugroup/jpa-findall-question

### Version

4.6.3

**Comment by radovanradic** [comment]
Tried rewriting (simplifying) predicate to this
```
fun <LuckPlatformPO> toSpecification(): PredicateSpecification<LuckPlatformPO> {
        val predSpec = PredicateSpecification<LuckPlatformPO> { root, builder ->
            builder.equal(root.get<String>("id"), 1)
        }
        return predSpec
    }
```
from
```
fun <T : LuckPlatformPO> toSpecification(entity: T): PredicateSpecification<T> {
        val predicateList = mutableListOf<Predicate>()
        val predSpec = PredicateSpecification<T> { root, builder ->
            val pathString = root.get<String>("id")
            predicateList.add(builder.equal(pathString, 1))
            val predicate=predicateList.toTypedArray()
            builder.createQuery().where(*predicate).restriction
        }
        return predSpec
    }
```
and then it seems to be working. Not sure if you need to create query in the `toSpecification` function
Cc @dstepanov

**Comment by easy-agent-skills** [comment]
thinks for you reply。 i get the right code. but its very 神奇。

GET ONE ERROR
````
fun <T : LuckPlatformPO> toSpecification(entity: T): PredicateSpecification<T> {
        val predicateList = mutableListOf<Predicate>()
        val predSpec = PredicateSpecification<T> { root, builder ->
            val pathString = root.get<String>("id")
            predicateList.add(builder.equal(pathString, 1))
            val predicate=predicateList.toTypedArray()
            builder.createQuery().where(*predicate).restriction
        }
        return predSpec
    }
   ````


move this below mutableListOf code to PredicateSpecification method inner .it works ok.
````
 val predicateList = mutableListOf<Predicate>()
````

blow code works ok.
````
 fun <T > toSpecification(entity: T): PredicateSpecification<T> {
          val predSpec = PredicateSpecification<T> { root, builder ->
              val predicateList = mutableListOf<Predicate>()
            val pathString = root.get<String>("id")
            predicateList.add(builder.equal(pathString, 1))
            val predicate=predicateList.toTypedArray()
            builder.createQuery().where(*predicate).restriction
        }
        return predSpec
    }
````

**Comment by radovanradic** [comment]
Considering you were able to write specification that works, I think this can be closed.

**Comment by dstepanov** [comment]
in `PredicateSpecification` you not supposed to call `createQuery`, just return `builder.equal(pathString, 1)` or use `builder.and` to have an AND predicate.
