### ISSUE TITLE
Update Entity with @EmbeddedId fail #data #jdbc #crudrepository

### ISSUE THREAD

**Issue by GatienTeniereScub** [micronaut-projects/micronaut-data#323]
# Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create entity with embedded id
2. Insert this entity with CrudRepository
3. Update this entity with CrudRepository

### Expected Behaviour
Should update entity

### Actual Behaviour

Update does not work :-1: 

ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Cannot perform update for non-existent property: Employee.id.companyId
java.lang.IllegalStateException: Cannot perform update for non-existent property: Employee.id.companyId
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$update$8(DefaultJdbcRepositoryOperations.java:449)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:177)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.update(DefaultJdbcRepositoryOperations.java:437)
	at io.micronaut.data.runtime.intercept.DefaultUpdateEntityInterceptor.intercept(DefaultUpdateEntityInterceptor.java:28)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:79)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at updatewithembeddedid.repository.EmployeeRepository$Intercepted.update(Unknown Source)
	at io.micronaut.data.repository.CrudRepository$update$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at updatewithembeddedid.controller.EmployeeController.updateJohnDoeToJaneDoe(EmployeeController.groovy:43)
	at updatewithembeddedid.controller.$EmployeeControllerDefinition$$exec3.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:145)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2844)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:235)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1401)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Environment Information

Ubuntu 18.04.3 LTS
- **Micronaut Version:** 1.2.6
- **Micronaut Data Version:** 1.0.0M5
- **JDK Version:** Open JDK 11.0.5

### Example Application

https://github.com/GatienTeniereScub/micronautIssueUpdateEmbeddedId

**Comment by mphouston** [comment]
I have seen the same thing.  When the @ID is not 'id', then the update fails.  It tries to using the a non-existent 'id' field, instead of the 'uuid' field.  I used a custom JDBC update operation and fixed the parameter name to be 'uuid' and it worked.

The insert works fine.

I also uploaded an example project: 
    [https://github.com/mphouston/mn-issues/tree/master/update-id-issue](https://github.com/mphouston/mn-issues/tree/master/update-id-issue)

**Comment by hrpath** [comment]
Same conclusion here with error message
`Error starting Micronaut server: Cannot perform update for non-existent property`

**Comment by graemerocher** [comment]
This is fixed in master, I believe by https://github.com/micronaut-projects/micronaut-data/commit/7f45bcc2b97e2065d2f7233afb8d28ee5b7d129c
