### ISSUE TITLE
Expandable query parts size should be the same as parameters size + 1

### ISSUE THREAD

**Issue by meriouma** [micronaut-projects/micronaut-data#3233]
### Expected Behavior

Everything works as with micronaut-data 4.9.x

### Actual Behaviour

I have this repository setup :
```
import io.micronaut.data.jdbc.annotation.JdbcRepository
import io.micronaut.data.model.Pageable
import io.micronaut.data.model.Slice
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.repository.CrudRepository

@JdbcRepository(dialect = Dialect.MYSQL)
interface OutboxJdbcOperations : CrudRepository<OutboxEntryEntity, OutboxEntryId> {
    fun findAll(pageable: Pageable): Slice<OutboxEntryEntity>
}
```
```
@MappedEntity("\${application.datasource.table-prefix}rabbitmq_outbox")
data class OutboxEntryEntity(
    @field:Id
    @MappedProperty("id", type = DataType.LONG)
    val id: OutboxEntryId? = null,
    @MappedProperty("exchange", type = DataType.STRING)
    val exchange: String,
    @MappedProperty("topic", type = DataType.STRING)
    val topic: String,
    @MappedProperty("headers", type = DataType.JSON)
    val headers: Map<String, Any?>,
    @MappedProperty("body", type = DataType.STRING)
    val body: String,
)
```
```
data class OutboxEntryId(
    val value: Long,
) {
    override fun toString(): String {
        return "OutboxEntryId($value)"
    }
}
```

Calling the `findAll` method with a `Pageable` (e.g.: `operations.findAll(Pageable.from(0, count))`) throws the following :
```
java.lang.IllegalStateException: Expandable query parts size should be the same as parameters size + 1. 6 != 1 + 1 SELECT outbox_entry_entity_.`id`,outbox_entry_entity_.`exchange`,outbox_entry_entity_.`topic`,outbox_entry_entity_.`headers`,outbox_entry_entity_.`body` FROM `tester_rabbitmq_outbox` outbox_entry_entity_ [SELECT outbox_entry_entity_.`id`, outbox_entry_entity_.`exchange`, outbox_entry_entity_.`topic`, outbox_entry_entity_.`headers`, outbox_entry_entity_.`body` FROM `tester_rabbitmq_outbox` outbox_entry_entity_, ]
	at io.micronaut.data.runtime.operations.internal.sql.DefaultSqlStoredQuery.<init>(DefaultSqlStoredQuery.java:68)
	at io.micronaut.data.runtime.operations.internal.sql.AbstractSqlRepositoryOperations.decorate(AbstractSqlRepositoryOperations.java:189)
	at io.micronaut.data.runtime.intercept.AbstractQueryInterceptor.findStoreQuery(AbstractQueryInterceptor.java:245)
	at io.micronaut.data.runtime.intercept.AbstractQueryInterceptor.prepareQuery(AbstractQueryInterceptor.java:230)
	at io.micronaut.data.runtime.intercept.DefaultFindSliceInterceptor.intercept(DefaultFindSliceInterceptor.java:55)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
```

### Version

micronaut 4.7.0, micronaut-data 4.10.x

**Comment by radovanradic** [comment]
Hello @meriouma,

I tried to reproduce issue but not reproducing it. Here is the example created based on your posted model and repo 
[mn-kotlin-jdbc-pageable.zip](https://github.com/user-attachments/files/17797925/mn-kotlin-jdbc-pageable.zip)
with minor difference - I had to add converter for the id field, not sure how the save is working for you. But, it should not affect behavior with pageable. Please review this example and add what is missing to reproduce the issue.

Thanks

**Comment by dstepanov** [comment]
Might be related to the property expression in the entity name

**Comment by meriouma** [comment]
@dstepanov You're right, removing the expression in the entity name works. Was it working by accident and this is unsupported or a new bug?

**Comment by radovanradic** [comment]
Looks like a bug in micronaut-data 4.10.x

**Comment by meriouma** [comment]
Thanks for the fix!
