### ISSUE TITLE
Can't get data from Postgres RETURNING clause as transaction is read-only

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-data#324]
### Steps to Reproduce

Create repository finder method with @Query which updates some relation before returning result. I.e. stored procedure or Postgres UPDATE ... RETURNING.

I would like to be able to return data using Postgres RETURNING clause from finder repository methods. Perhaps add an @Modifing annotation to make requested connection updateable.

Example:

```
@Entity
data class Test(
    @Id @GeneratedValue @Column(name = "test_id") var id: Long,
    var foo: String? = null,
    var bar: Int = 0
)

@JdbcRepository(dialect = Dialect.POSTGRES)
interface TestRepository : ReactiveStreamsCrudRepository<Test, Long> {

    @Query("""
WITH task AS (
    SELECT test_id FROM test where foo != :key LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE test SET foo = :key FROM task WHERE test.test_id = task.test_id
RETURNING test.*""")
    fun nextTask(key: String): Mono<Test>
}
```
### Expected Behaviour

Updated entity is returned from finder.

### Actual Behaviour

Exception is thrown:

```
java.util.concurrent.CompletionException: *io.micronaut.data.exceptions.DataAccessException: Error executing SQL Query: ERROR: cannot execute UPDATE in a read-only transaction*
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.micronaut.data.exceptions.DataAccessException: Error executing SQL Query: ERROR: cannot execute UPDATE in a read-only transaction
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:217)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:174)
	at io.micronaut.data.runtime.operations.ExecutorAsyncOperations.lambda$findOptional$4(ExecutorAsyncOperations.java:113)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	... 8 common frames omitted
Caused by: org.postgresql.util.PSQLException: *ERROR: cannot execute UPDATE in a read-only transaction*
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:177)
	... 12 common frames omitted
```

### Environment Information

Micronaut Data 1.0.0.M5

**Comment by graemerocher** [comment]
The issue here is the automatic application of a read only transaction for `@Query(..)` I think we should add a way to set whether it is is read only explicitly in the annotation
