### ISSUE TITLE
When retrieving data from DB Exception thrown with "Null value read for non-null constructor argument" message - after upgrading to Micronaut Parent 4.7.2

### ISSUE THREAD

**Issue by balapal** [micronaut-projects/micronaut-data#3267]
### Expected Behavior

@MappedEntity should be possible be created with null field values when retrieving data from DB.

### Actual Behaviour

When retrieving data from DB Exception thrown with "Null value read for non-null constructor argument" message after upgrading to Micronaut Parent 4.7.2

Stack trace
```
io.micronaut.data.exceptions.DataAccessException: Null value read for non-null constructor argument [title] of type: micronaut.reproduce.Book
		at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:541)
		at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper$4.processRow(SqlResultEntityTypeMapper.java:376)
		at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations$DefaultR2dbcReactiveRepositoryOperations.lambda$findAll$8(DefaultR2dbcRepositoryOperations.java:544)
		at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$executeAndMapEachRow$7(DefaultR2dbcRepositoryOperations.java:451)
		at io.r2dbc.h2.H2Result.lambda$map$1(H2Result.java:103)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
		... 52 more
```

See example at to reproduce the problem at https://github.com/balapal/micronaut-47-null-check-introduced 

I downgrade to micronaut-parent 4.7.0, everything works again.

### Steps To Reproduce

See the example app to reproduce this issue at https://github.com/balapal/micronaut-47-null-check-introduced

### Example Application

https://github.com/balapal/micronaut-47-null-check-introduced

### Version

4.7.2

**Comment by radovanradic** [comment]
Looks like caused by micronaut-core 4.7.6 release @graemerocher and supposedly this PR https://github.com/micronaut-projects/micronaut-core/pull/11347
Adding property `<micronaut.core.version>4.7.5</micronaut.core.version>` fixes the issue.

**Comment by balapal** [comment]
Yeah, It works with micronaut.core.version 4.7.5

I have also tried with micronaut.core.version 4.7.9 to see if https://github.com/micronaut-projects/micronaut-core/pull/11451 fixes it, but it does not

**Comment by radovanradic** [comment]
It gets fixed by annotating title field as `@Nullable` and adding this to lombok.config

`lombok.copyableannotations += io.micronaut.core.annotation.Nullable`

So this may not be a bug but configuration issue.

**Comment by balapal** [comment]
I did find that "workaround" and it "solves" it, but I don't think it is an elegant or reasonable solution.
I had a POJO with ~15 fields and had to add `@Nullable` to most of them after a version upgrade (works in 4.7.0, does not work in 4.7.1)

If I don't want a field to allow nulls I add `@NotNull` and not the other way around.
I think it is not user friendly or straightforward to force the client code to add `@Nullable` to all fields.

And also it is a not documented regression.

**Comment by aoyanb** [comment]
@graemerocher 
Could you please check this one too!
https://github.com/micronaut-projects/micronaut-core/issues/11432#issuecomment-2548367309

**Comment by graemerocher** [comment]
I don't think this is related to an upstream change. @radovanradic do you know if we added non-checking somewhere?

**Comment by radovanradic** [comment]
I don't think there were changes in micronaut-data around this in this release where issue is reported.
Just changing to `<micronaut.core.version>4.7.5</micronaut.core.version>` which resolves issue made me think it was caused by core changes. As soon as it is updated to 4.7.6+ the issue pops up.

**Comment by graemerocher** [comment]
ok will investigate

**Comment by graemerocher** [comment]
I sent a PR for this https://github.com/micronaut-projects/micronaut-core/pull/11481

**Comment by sdelamo** [comment]
@graemerocher @radovanradic I have released core 4.7.10.

**Comment by graemerocher** [comment]
should probably add a downstream test in data once we upgrade

**Comment by balapal** [comment]
Hi,
I have upgraded to micronaut-parent 4.7.3 and set the mirconaut-core version to 4.7.11 version and my attached example test works https://github.com/balapal/micronaut-47-null-check-introduced

**Comment by radovanradic** [comment]
> should probably add a downstream test in data once we upgrade

Added test in this PR https://github.com/micronaut-projects/micronaut-data/pull/3289
