### ISSUE TITLE
@MappedEntity with an @Embeddable property can't be retrieved from CrudRepository

### ISSUE THREAD

**Issue by adbonnin** [micronaut-projects/micronaut-data#334]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an `@Embeddable` class `Address`
2. Create a `@MappedEntity` class `Author`
3. Create an `address` property of type `Address` in `Author` with `@Relation(Relation.Kind.EMBEDDED)`
4. Retrive an `Address` from a `CrudRepository`

### Stacktrace

```
17:34:36.364 [Test worker] INFO  l.lockservice.StandardLockService - Successfully released change log lock
17:34:42.193 [Test worker] DEBUG io.micronaut.data.query - Executing SQL Insert: INSERT INTO `author` (`name`,`address_city`) VALUES (?,?)
17:34:42.218 [Test worker] DEBUG io.micronaut.data.query - Executing Query: SELECT author_.`id`,author_.`name`,author_.`address_city` FROM `author` author_ WHERE (author_.`id` = ?)

Error reading object for name [address] from result set: Colonne "address" non trouvée
Column "address" not found [42122-199]
io.micronaut.data.exceptions.DataAccessException: Error reading object for name [address] from result set: Colonne "address" non trouvée
Column "address" not found [42122-199]
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.exceptionForColumn(ColumnNameResultSetReader.java:206)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.getRequiredValue(ColumnNameResultSetReader.java:201)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.getRequiredValue(ColumnNameResultSetReader.java:35)
	at io.micronaut.data.runtime.mapper.ResultReader.readDynamic(ResultReader.java:133)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:323)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:146)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:190)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:174)
	at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
	at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:79)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at issue.repositories.AuthorRepositorySpec.should save an author(AuthorRepositorySpec.groovy:25)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "address" non trouvée
Column "address" not found [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3188)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3287)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:533)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.getRequiredValue(ColumnNameResultSetReader.java:188)
	... 12 more
```

### Expected Behaviour

In the stacktrace the query to retrieve an author is fine :
```
SELECT author_.id, author_.name, author_.address_city
FROM author author_
WHERE (author_.id = ?);
```

The expected behaviour is that Micronaut don't look for the column of the @Embeddable property
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Colonne "address" non trouvée
Column "address" not found [42122-199]
```

### Actual Behaviour

Micronaut look for an extra column of the @Embeddable property.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.8
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** 1.8.0_221

### Example Application

- https://github.com/adbonnin/micronaut-embedded-issue
- launch the unit test `issue.repositories.AuthorRepositorySpec`

**Comment by ckosmowski** [comment]
I have a similar problem with a custom JDBC Query method. It Useses the method `entityStream` like in the examples to get multiple entities from one query.

The entity class contains multiple properties anotated with @Embedded (javax.persistence). The `entityStream` method uses the SQLResultEntityTypeMapper to map the results (i suspect this issue to end in the same code section).

The method `readEntity` here does not yet take properties of type `@Embedded` into account. However the properties were correctly marked as Embedded (instanceof Embedded yielded true) during debugging.

The result i get is the same as in this issue. "Unknown column name [nameOfTheEmbeddedProperty]".

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-data/commit/7f45bcc2b97e2065d2f7233afb8d28ee5b7d129c
