### ISSUE TITLE
Migrating strategy to Micronaut Data

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-data#347]
Hi team, 

Since the beginning of project we are very excited about Micronaut Data. However companies like us who relied on existing java technologies like Spring and our their internal tools is not easy to completely move to Micronaut at one shot. I would like to move our project's data layer to Micronaut Data and migrating remaining parts slowly. 

Would you please include a programmatically instantiate a repository and use it? 

Thanks

**Comment by graemerocher** [comment]
I am not sure you can directly instantiate a repository in Spring Data either no?

**Comment by cemo** [comment]
I am not using actually Spring Data. Instead of it we are relying on our internal implementation of it. Instead of it, I would like to use micronaut-data which is superior. 😎

**Comment by graemerocher** [comment]
ok :)

So since the repositories themselves are produced at compilation time and use Micronaut AOP you can't really instantiate them directly. However it is easy to get a reference using the Micronaut context. Like so:

```
try (ApplicationContext context = ApplicationContext.run()) {
       MyRepository repo = context.getBean(MyRepository.class);
}
```

**Comment by cemo** [comment]
Hi @graemerocher I started to revisit this issue and giving a try now. 

I followed the quickstart. However I could not make code generation successful. After checking examples I noticed that 
https://github.com/micronaut-projects/micronaut-data/blob/afc8c57f0bfcc0d395eb6b7b2a40d308165bd154/examples/example-jdbc/pom.xml#L156-L160
seems required as well. Is this a bug? Should I open a new issue or continue my findings here? 

It is also be quite useful to see some logs about processing since I struggled to find it. (Another issue maybe?)

**Comment by cemo** [comment]
My new error is related to transaction. 

```
Exception in thread "main" io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations]

Message: Missing bean argument value: transactionOperations
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataSource dataSource,[TransactionOperations transactionOperations],ExecutorService executorService,BeanContext beanContext,List codecs,DateTimeProvider dateTimeProvider)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:103)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:121)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
```

I added `data-tx` as a dependency first. I noticed on it there is `missingClasses = "org.springframework.jdbc.datasource.DataSourceTransactionManager"`condition. Then I removed data-tx I switched to `micronaut-data-spring`. SpringJdbcTransactionOperations seems reachable. `org.springframework.jdbc.datasource.DataSourceTransactionManager` is also available on my classpat. However error still is persisting.  
Then I noticed a transient runtime dependency `micronaut-hibernate-jpa-spring` which is coming from `micronaut-data-spring`. I excluded it. This time I could it make running. Do you think that it is a bug?

**Comment by cemo** [comment]
@graemerocher `micronaut-data-spring` seems all its dependencies are compile scope. It may be better to make them optional? Otherwise unpleasant surprises may come up. For example I am only interested in `jdbc` package of  `micronaut-data-spring` but hibernate and spring-data dependencies are transitively appear in my classpath. On my side I was expecting only glue code with Spring and Micronaut. However I got hibernate dependencies on my classpath. :) The problem is that these packages are triggering other Micronaut features which are mostly activated presence of a class in classpath.

Here is the relevant packages: 
https://github.com/micronaut-projects/micronaut-data/tree/master/data-spring/src/main/java/io/micronaut/data/spring  

PS: Still I could not understand why I had a "Message: Missing bean argument value: transactionOperations". I will be glad if you can explain this as well.

I hope I am doing fine as I am writing here. In case a need for new issues, I can delete from here and file new issues. 

I want to help you more :)

**Comment by cemo** [comment]
By the way, I noticed a very good explanation of this project in documents. 

`Micronaut Data JDBC is designed for users who prefer a lower-level experience and working directly with SQL. 💘 `

Thank you and the team for your all efforts.
