### ISSUE TITLE
Save/Read entity with JSON type works but Read as DTO fails

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-data#387]
Using Micronaut Data JDBC and MySQL, saving an entity with a JSON type and read it back as the same entity type works. Reading an entity as a DTO fails.

Take a look at the sample application and run the tests. The first one passes but the second one fails with:
```
Failed to convert argument [gps] for value [null] due to: Value [{"lat": -40.123, "lng": 25.987}] cannot be converted to type : interface java.util.Map
io.micronaut.core.convert.exceptions.ConversionErrorException: Failed to convert argument [gps] for value [null] due to: Value [{"lat": -40.123, "lng": 25.987}] cannot be converted to type : interface java.util.Map
	at io.micronaut.core.beans.BeanProperty.lambda$convertAndSet$1(BeanProperty.java:153)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.core.beans.BeanProperty.convertAndSet(BeanProperty.java:151)
	at io.micronaut.data.runtime.mapper.BeanIntrospectionMapper.map(BeanIntrospectionMapper.java:91)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:205)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:175)
	at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
	at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:123)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at data.mysql.json.AlertRepositorySpec.save and read as DTO with json format works(AlertRepositorySpec.groovy:83)
Caused by: java.lang.IllegalArgumentException: Value [{"lat": -40.123, "lng": 25.987}] cannot be converted to type : interface java.util.Map
	at io.micronaut.core.beans.BeanProperty.lambda$null$0(BeanProperty.java:153)
	at io.micronaut.core.convert.exceptions.ConversionErrorException.<init>(ConversionErrorException.java:37)
	... 14 more
```

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** OpenJDK 11

### Example Application

https://github.com/ilopmar/mn-data-dto-json

**Comment by alworks** [comment]
Is this fix in a Version already?
