### ISSUE TITLE
Micronaut Data JDBC does not support non-Long Generated ID types

### ISSUE THREAD

**Issue by emmanuj** [micronaut-projects/micronaut-data#420]
When using Micronaut Data JDBC, using Id types that are not `Long` will yield an error.

### Steps to Reproduce

**1. DDL:**

```
create table if not exists example
(
    id uuid DEFAULT uuid_generate_v1() PRIMARY KEY,
    name text not null unique,
    for_date timestamptz not null,
    created_at timestamp default current_timestamp not null,
    notes text
);
```

**2. Entity:**

```
@MappedEntity
public class Example {

	@Id
	@GeneratedValue
	private String id;

	private String name;

	Date forDate;

	@DateCreated
	Date createdAt;

	///... removed constructors getters and setters for brevity
}
```

**3. Repository**

```
@JdbcRepository(dialect = Dialect.POSTGRES)
public interface ExampleRepository extends CrudRepository<Example, String> {
	Example find(String name);
}
```

**4. Query:**

```
Example example = new Example("Foo", new Date());
exampleRepository.save(example);
```

### Expected Behaviour

Data should be saved without any errors

### Actual Behaviour

Exception is thrown:

```
io.micronaut.data.exceptions.DataAccessException: SQL Error executing INSERT: Bad value for type long : 9c401364-5a01-11ea-803a-0242ac320500
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$persistOne$9(DefaultJdbcRepositoryOperations.java:660)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:177)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persistOne(DefaultJdbcRepositoryOperations.java:612)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.persist(DefaultJdbcRepositoryOperations.java:602)

```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.3.2
- **JDK Version:** java version 11.0.1

**Comment by emmanuj** [comment]
I think the problem is caused by this line 
` long id = generatedKeys.getLong(1);` in `DefaultJdbcRepositoryOperations.java` (line 639).

This prevents one from using anything other than long with `@Id @GeneratedValue`

**Comment by emmanuj** [comment]
@graemerocher What if I did something like this:

`Object id = generatedKeys.getObject(1, identity.getType())`

Would this be a reasonable fix?

**Comment by graemerocher** [comment]
To make it more efficient it would probably be better to do something like:

```java
DataType dataType = insert.getIdentity().getDataType();
Object id;
switch(dataType) {
        case LONG:
            id = generatedKeys.getLong(1);
        break;
         /// ... other cases
        default:
            id = generatedKeys.getObject(1, identity.getType())
}

```

**Comment by emmanuj** [comment]
@graemerocher Can I submit a pull request for this or do you already have it planned?

**Comment by graemerocher** [comment]
Please go ahead
