### ISSUE TITLE
Jpa native queries don't bind with enums

### ISSUE THREAD

**Issue by augustobmoura** [micronaut-projects/micronaut-data#422]
### Steps to Reproduce

1. Configure a new micronaut project with jpa micronaut data
2. Create new tables with varchar/text columns to be mapped into a enum
``` sql
CREATE TABLE books (
  id BIGINT SERIAL,
  type TEXT
);
```
``` groovy
enum BookType {
  FICTION,
  BIOGRAPHY,
}
```
3. Try to list all types from a auto generated `@Repository`
``` groovy
@Repository
interface BookRepository extends CrudRepository<Book, Long> {
  @Query(value = "SELECT type FROM books", nativeQuery = true)
  Stream<BookType> findAllBookTypes()
}
```

### Expected Behaviour

To list all types as the result of the native query

### Actual Behaviour

Throws a error at runtime "Unknown entity: com.package.BookType"

### Environment Information

- **Operating System**: Linux/Ubuntu 18.04
- **Micronaut Version:** 1.3.0, Data: 1.0.0
- **JDK Version:** Adopt11.0.6+OpenJ9

**Comment by augustobmoura** [comment]
I tried returning `Stream<String>` instead of the enum, also didn't worked.
Relevant part of the stack trace:
```org.hibernate.MappingException: Unknown entity: java.lang.String
	at org.hibernate.metamodel.internal.MetamodelImpl.entityPersister(MetamodelImpl.java:704)
	at org.hibernate.engine.spi.SessionFactoryImplementor.getEntityPersister(SessionFactoryImplementor.java:345)
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.getSQLLoadable(SQLQueryReturnProcessor.java:445)
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processRootReturn(SQLQueryReturnProcessor.java:498)
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processReturn(SQLQueryReturnProcessor.java:465)
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.process(SQLQueryReturnProcessor.java:180)
	at org.hibernate.loader.custom.sql.SQLCustomQuery.<init>(SQLCustomQuery.java:74)
	at org.hibernate.engine.query.internal.NativeQueryInterpreterStandardImpl.createQueryPlan(NativeQueryInterpreterStandardImpl.java:44)
	at org.hibernate.engine.query.spi.QueryPlanCache.getNativeSQLQueryPlan(QueryPlanCache.java:226)
	at org.hibernate.internal.AbstractSharedSessionContract.getNativeQueryPlan(AbstractSharedSessionContract.java:604)
	at org.hibernate.internal.AbstractSharedSessionContract.scroll(AbstractSharedSessionContract.java:1139)
	at org.hibernate.query.internal.NativeQueryImpl.doScroll(NativeQueryImpl.java:220)
	at org.hibernate.query.internal.AbstractProducedQuery.scroll(AbstractProducedQuery.java:1483)
	at org.hibernate.query.internal.AbstractProducedQuery.stream(AbstractProducedQuery.java:1507)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findStream$14(HibernateJpaOperations.java:465)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations$$Lambda$878/0000000000000000.call(Unknown Source)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findStream(HibernateJpaOperations.java:433)
	at io.micronaut.data.runtime.intercept.DefaultFindStreamInterceptor.intercept(DefaultFindStreamInterceptor.java:49)
	at io.micronaut.data.runtime.intercept.DefaultFindStreamInterceptor.intercept(DefaultFindStreamInterceptor.java:34)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:123)
```

**Comment by graemerocher** [comment]
This is fixed by the above commit but note for enums only supported with:

```
@Enumerated(EnumType.STRING)
```

If you want ordinal enums you need to define a converter that converts between the ordinal value and the enum value.
