### ISSUE TITLE
Why the entity-scan.packages could not scan the entity from dependency

### ISSUE THREAD

**Issue by qianwj** [micronaut-projects/micronaut-data#434]
## Description
I have an twatch-core.jar used to save the common entity, and this module, twatch-conf depend the twatch-core.jar, when I configure the package `com.tinet.core.entity` in `entity-scan.packages`, the class which annotated by `@Entity` will not be found.
## Configuration
the `application.yml`:
```yml
micronaut:
  application:
    name: twatch-conf
  jackson:
    bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:postgresql://...
    driverClassName: org.postgresql.Driver
    username:
    password: 
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
       - com.tinet.twatch.core.entity
       - com.tinet.twatch.conf.entity
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
```
the `pom.xml`:
```
<dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-jdbc</artifactId>
      <version>1.0.0.RC1</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-hibernate-jpa</artifactId>
      <version>1.0.0.RC1</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-spring-jpa</artifactId>
      <version>1.0.0.RC1</version>
    </dependency>

<dependency>
      <groupId>com.tinet.twatch</groupId>
      <artifactId>twatch-core</artifactId>
      <version>0.0.2</version>
    </dependency>

    <!-- sql -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.2.10</version>
      <scope>runtime</scope>
    </dependency>

```
the package naming roles:
- in the core: entity package is `com.tinet.twatch.core.entity`
- in the conf: entity package is `com.tinet.twatch.conf.entity`

## code
```java
import com.tinet.twatch.core.entity.TWatchDevice;
import io.micronaut.data.annotation.Repository;
import io.micronaut.data.repository.PageableRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;


@Repository
public interface DeviceRepository extends PageableRepository<TWatchDevice, Long>, JpaSpecificationExecutor<TWatchDevice> { }
```
```java
import com.tinet.twatch.conf.repository.network.DeviceRepository;
import com.tinet.twatch.conf.service.dynamic.DeviceDynamicQuery;
import com.tinet.twatch.core.dto.RestResponse;
import com.tinet.twatch.core.entity.TWatchDevice;
import io.micronaut.data.model.Pageable;
import io.micronaut.http.HttpStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.PageRequest;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.util.List;

@Singleton
public class DeviceService {

    private Logger logger = LoggerFactory.getLogger(DeviceService.class);

    private DeviceRepository repository;

    @Inject
    public DeviceService(DeviceRepository repository) {
        this.repository = repository;
    }

    public RestResponse<List<TWatchDevice>> find(TWatchDevice params, int pageNo, int pageSize) {
        try {
            if (params.isEmpty()) {
                return RestResponse.success(repository.findAll(Pageable.from(pageNo, pageSize)).getContent());
            }
            return RestResponse.success(repository.findAll(DeviceDynamicQuery.spec(params), PageRequest.of(pageNo, pageSize)).getContent());
        } catch (Exception e) {
            logger.error("DeviceService.find exception: {}", e.getLocalizedMessage(), e);
            return RestResponse.fail(HttpStatus.INTERNAL_SERVER_ERROR.getCode(), "error");
        }
    }
}

```

The `TWatchDevice` is a class in core.
When I use the method `findAll()`(The `params` is empty), console throws exception as follow:
```log
11:30:20.992 [pool-1-thread-3] ERROR c.t.t.c.s.network.DeviceService - DeviceService.find exception: Not an entity: class com.tinet.twatch.core.entity.TWatchDevice
java.lang.IllegalArgumentException: Not an entity: class com.tinet.twatch.core.entity.TWatchDevice
	at org.hibernate.metamodel.internal.MetamodelImpl.entity(MetamodelImpl.java:566)
	at org.hibernate.query.criteria.internal.QueryStructure.from(QueryStructure.java:127)
	at org.hibernate.query.criteria.internal.CriteriaQueryImpl.from(CriteriaQueryImpl.java:154)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.buildCriteriaQuery(HibernateJpaOperations.java:517)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findPage$15(HibernateJpaOperations.java:493)
	at io.micronaut.data.spring.hibernate.SpringHibernateTransactionOperations.lambda$executeRead$0(SpringHibernateTransactionOperations.java:75)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at io.micronaut.data.spring.hibernate.SpringHibernateTransactionOperations.executeRead(SpringHibernateTransactionOperations.java:73)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findPage(HibernateJpaOperations.java:488)
	at io.micronaut.data.runtime.intercept.DefaultFindPageInterceptor.intercept(DefaultFindPageInterceptor.java:69)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:158)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at com.tinet.twatch.conf.repository.network.DeviceRepository$Intercepted.findAll(Unknown Source)
	at com.tinet.twatch.conf.service.network.DeviceService.find(DeviceService.java:32)
	at com.tinet.twatch.conf.controller.network.DeviceController.list(DeviceController.java:33)
	at com.tinet.twatch.conf.controller.network.$DeviceControllerDefinition$Intercepted.$$access0(Unknown Source)
	at com.tinet.twatch.conf.controller.network.$DeviceControllerDefinition$Intercepted$$proxy0.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:158)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at com.tinet.twatch.conf.controller.network.$DeviceControllerDefinition$Intercepted.list(Unknown Source)
	at com.tinet.twatch.conf.controller.network.$$DeviceControllerDefinition$InterceptedDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2991)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:297)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1461)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
and I track the code in `QueryStructure` class:
```java
public <X> Root<X> from(Class<X> entityClass) {
		EntityType<X> entityType = criteriaBuilder.getEntityManagerFactory()
				.getMetamodel()
				.entity( entityClass );
		if ( entityType == null ) {
			throw new IllegalArgumentException( entityClass + " is not an entity" );
		}
		return from( entityType );
	}
```
??? why ???

**Comment by graemerocher** [comment]
What does `TWatchDevice` look like?
