### ISSUE TITLE
Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-data#443]
This application ran OK with Micronaut Data 1.0.0 and now fails to start with 1.0.1

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/JasonTypesCodes/micronaut-json-issue
2. cd jhipster-micronaut
3. ./mvnw clean exec:exec

### Expected Behaviour

The app runs

### Actual Behaviour

The application fails to start with:

```
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
```

**Comment by jameskleeh** [comment]
Closing this because it seems the app had `micronaut-data-hibernate-jpa` and `micronaut-data-jdbc` set to 1.0.0 so likely the other transitive modules were updated to 1.0.1 causing a conflict.  I removed the set versions and it is working OK.
