### ISSUE TITLE
1.0.1: HealthMonitorTask throws exception

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#472]
After switching a project to micronaut-data 1.0.1 the `HealthMonitorTask` throws an exception and logs an error because of missing transactional boundaries.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided

### Steps to Reproduce

1. Enable health endpoint
2. Use micronaut-data 1.0.1

### Expected Behaviour
No Exception.

### Actual Behaviour
Exception and error logging from health endpoint.

```
ERROR i.m.m.h.monitor.HealthMonitorTask - Health monitor check failed with exception: No current transaction present. Consider declaring @Transactional on the surrounding metho 
io.micronaut.transaction.exceptions.NoTransactionException: No current transaction present. Consider declaring @Transactional on the surrounding method                                                         
        at io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor.intercept(TransactionalConnectionInterceptor.java:50)                                                                               
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)                                                                                                                
        at io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted.isValid(Unknown Source)                                                                                                            
        at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:86)                                                                                                
        at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)                                                       
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)                                                                                                                
        at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144)                                                                                                                                    
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                                              
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                             
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                      
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                      
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                                                
        Suppressed: io.micronaut.transaction.exceptions.NoTransactionException: No current transaction present. Consider declaring @Transactional on the surrounding method                                     
                at io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor.intercept(TransactionalConnectionInterceptor.java:50)                                                                       
                at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)                                                                                                        
                at io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted.close(Unknown Source)                                                                                                      
                at io.micronaut.management.health.indicator.jdbc.JdbcIndicator.lambda$getResult$0(JdbcIndicator.java:95)                                                                                        
                ... 8 common frames omitted                                                                                                                                                                     
        Caused by: io.micronaut.transaction.jdbc.exceptions.CannotGetJdbcConnectionException: No current JDBC Connection found. Consider wrapping this call in transactional boundaries.                        
                at io.micronaut.transaction.jdbc.DataSourceUtils.doGetConnection(DataSourceUtils.java:136)                                                                                                      
                at io.micronaut.transaction.jdbc.DataSourceUtils.getConnection(DataSourceUtils.java:94)                                                                                                         
                at io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor.intercept(TransactionalConnectionInterceptor.java:48)                                                                       
                ... 11 common frames omitted                                                                                                                                                                    
Caused by: io.micronaut.transaction.jdbc.exceptions.CannotGetJdbcConnectionException: No current JDBC Connection found. Consider wrapping this call in transactional boundaries.                                
        at io.micronaut.transaction.jdbc.DataSourceUtils.doGetConnection(DataSourceUtils.java:136)                                                                                                              
        at io.micronaut.transaction.jdbc.DataSourceUtils.getConnection(DataSourceUtils.java:94)                                                                                                                 
        at io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor.intercept(TransactionalConnectionInterceptor.java:48)                                                                               
        ... 11 common frames omitted                                                                                                                                                                            
```
### Workaround
Use micronaut-data 1.0.0 or disable health endpoint

### Environment Information

- **Operating System**: any
- **Micronaut Version:** micronaut-core 1.3.3, micronaut-data 1.0.1
- **JDK Version:** 8

**Comment by graemerocher** [comment]
This is fixed by https://github.com/micronaut-projects/micronaut-core/commit/291b18fbd7f5d9895f2a20aa19beb91b1fdfc082
