### ISSUE TITLE
UPDATE and DELETE queries do not support reactive returns

### ISSUE THREAD

**Issue by matejdro** [micronaut-projects/micronaut-data#501]
### Steps to Reproduce

1. Create repository method that performs either `DELETE` or `UPDATE` operation with `@Query` annotation.
2. Add `io.reactivex.Completable` return type for this method

For example:
```kotlin
    @Query("UPDATE user SET enabled = false WHERE id = :id") 
    fun deleteById(@NotNull id: Long): Completable
```

### Expected Behaviour

App should compile normally and query should execute normally, finishing returned completable when Query completes.

### Actual Behaviour

Compile fails with `Unable to implement Repository method: ... . Unsupported Repository method return type`.

I've also tried using `Single<Void>` or `Single<Unit>` as a return type, which compiles, but produces following exception at runtime:

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Update/delete queries cannot be typed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Update/delete queries cannot be typed
	at org.hibernate.internal.AbstractSharedSessionContract.resultClassChecking(AbstractSharedSessionContract.java:834)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:817)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:113)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$2(HibernateJpaOperations.java:162)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:133)
	at io.micronaut.data.runtime.operations.ExecutorAsyncOperations.lambda$findOptional$4(ExecutorAsyncOperations.java:113)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more
```

### Environment Information

- **Operating System**: `Arch Linux`
- **Micronaut Version:** `1.0.1`
- **JDK Version:** `OpenJDK 13.0.2`

**Comment by matejdro** [comment]
`Update/delete queries cannot be typed` also happens when I attempt to return `Single<Int>` as return type (to receive number of updated rows)
