### ISSUE TITLE
InstantiationException when using the BeanIntrospectionModule

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-data#518]
Given this JSON

```json
{
   "content":[
      {
         "id":4,
         "title":"The Institute",
         "pages":700
      },
      {
         "id":2,
         "title":"The Shining",
         "pages":600
      },
      {
         "id":1,
         "title":"The Stand",
         "pages":1000
      }
   ],
   "pageable":{
      "number":0,
      "sort":{
         "orderBy":[
            {
               "property":"title",
               "direction":"ASC",
               "ignoreCase":false,
               "ascending":true
            }
         ],
         "sorted":true
      },
      "size":10,
      "offset":0,
      "sorted":true
   },
   "totalSize":3,
   "totalPages":1,
   "empty":false,
   "size":10,
   "offset":0,
   "numberOfElements":3,
   "pageNumber":0
}
```

And this mapping:

```java
@Get("/{title}")
Page<Book> findByTitleLike(
        String title,
        @QueryValue int page,
        @QueryValue int size,
        @QueryValue(defaultValue = "title, desc") String sort);
```

Deserialization produces the following exception:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No default constructor exists (through reference chain: io.micronaut.data.model.Page["pageable"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3309)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.decode(JacksonMediaTypeCodec.java:173)
	... 48 common frames omitted
Caused by: io.micronaut.core.reflect.exception.InstantiationException: No default constructor exists
	at io.micronaut.data.model.$Pageable$Introspection.instantiate(Unknown Source)
	at io.micronaut.jackson.modules.BeanIntrospectionModule$BeanIntrospectionDeserializerModifier$1.createUsingDefault(BeanIntrospectionModule.java:379)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
```

**Comment by graemerocher** [comment]
Requires upgrading to Micronaut 2.x or disabling the Bean introspection module for the moment. Either way it is niche use case.

**Comment by rohitkg98** [comment]
Not able to use Page as a return type in Declarative Client due to this.
Can anyone guide me on how to fix it? Happy to make a PR.

**Comment by graemerocher** [comment]
@rohitkg98 the true fix just required upgrading to Micronaut 2, now that that is done nothing else is needed
