### ISSUE TITLE
@Transactional not working on repository's custom query

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-data#58]
In the docs, section `8.1.3 JDBC Repositories`, this example is highlighted:

```java
    @Transactional
    public List<Book> findByTitle(String title) {
        String sql = "SELECT * FROM Book AS book WHERE book.title = ?";
        return jdbcOperations.prepareStatement(sql, statement -> {
            statement.setString(1, title);
            ResultSet resultSet = statement.executeQuery();
            return jdbcOperations.entityStream(resultSet, Book.class).collect(Collectors.toList());
        });
    }
```

But the as you can see in this example ([hello-world.zip](https://github.com/micronaut-projects/micronaut-predator/files/3432754/hello-world.zip)) the `@Transactional` annotation doesn't seem to be honored when it's applied directly to the `BookRepository` method. Rather, I could only get it to work if I wrapped the call with another singleton that had its own `@Transactional` annotation. See `src/main/java/hello/world/Application.java`:

```java
    @EventListener
    void init(StartupEvent event) {
        final Book book = new Book("9780545010221", "Harry Potter");
        repository.save(book);

        // find books through the wrapping service
        List<Book> coolBooks = singleton.findCoolBooks();
        System.out.println("How many cool books? " + coolBooks.size());

        // now do it directly against the repository and this fails
        coolBooks = repository.findCoolBooks();
        System.out.println("How many cool books? " + coolBooks.size());

    }
```

The first query, `singleton.findCoolBooks()` succeeds but the second query, `repository.findCoolBooks()` blows up with the following exception:

```11:06:19.130 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No transaction declared. Define @Transactional on the surrounding method prior to calling getConnection()
io.micronaut.data.transaction.exceptions.NoTransactionException: No transaction declared. Define @Transactional on the surrounding method prior to calling getConnection()
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.getConnection(SpringJdbcTransactionOperations.java:79)
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.getConnection(SpringJdbcTransactionOperations.java:28)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:574)
        at hello.world.BookRepository.findCoolBooks(BookRepository.java:23)
        at hello.world.Application.init(Application.java:32)
        at hello.world.$ApplicationDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2761)
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
        at hello.world.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.lambda$publishEvent$17(DefaultBeanContext.java:1063)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1057)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:214)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
        at hello.world.Application.main(Application.java:11)
```

**Comment by graemerocher** [comment]
Caused by an upstream bug in core which is now resolved https://github.com/micronaut-projects/micronaut-core/issues/1933
