### ISSUE TITLE
Pagination  native query does not seem to be working

### ISSUE THREAD

**Issue by huyanchao** [micronaut-projects/micronaut-data#595]
When trying to use pagination  native query, the error occured

### Task List

- [ ] Steps to reproduce provided
@Query(value = "select * from sys_user",nativeQuery = true,
            countQuery = "select count(*) from sys_user")
    Page<SysUser> getUserList(Pageable pageable);
}

- [ ] Stacktrace (if present) provided
08:57:27.709 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: org.hibernate.MappingException: Unknown entity: java.lang.Long
javax.persistence.PersistenceException: org.hibernate.MappingException: Unknown entity: java.lang.Long
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1539)
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1572)
	at org.hibernate.query.internal.AbstractProducedQuery.uniqueResultOptional(AbstractProducedQuery.java:1523)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$2(HibernateJpaOperations.java:167)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:157)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:133)
	at io.micronaut.data.runtime.intercept.DefaultFindPageInterceptor.intercept(DefaultFindPageInterceptor.java:58)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:141)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at com.safe.module.dao.SysUserRepository$Intercepted.getUserList(Unknown Source)
	at com.safe.module.sevice.SysUserService.test(SysUserService.java:24)

### Environment Information

- **Operating System**: Windows10
- **Micronaut Version: 2.0.0.M3
- **JDK Version: 8

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-data/pull/772
