### ISSUE TITLE
Spring transaction does not work with Micronaut-Data with Spring Boot 2.3.1.RELEASE 

### ISSUE THREAD

**Issue by franz-see** [micronaut-projects/micronaut-data#602]
Micronaut version : 1.3.6
Spring-boot version : 2.3.1.RELEASE
micronaut-data version : 1.0.2
micronaut-data-spring version : 1.0.2

I have a working spring-boot + micronaut-data project. But just by adding the following, my tests starts to fail.

```
    <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-spring</artifactId>
      <version>${micronaut.data.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-context</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-commons</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>
```

Sample test error

```
Message: Missing bean argument value: transactionOperations
Path Taken: new DefaultJdbcRepositoryOperations(String dataSourceName,DataSource dataSource,[TransactionOperations transactionOperations],ExecutorService executorService,BeanContext beanContext,List codecs,DateTimeProvider dateTimeProvider)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:103)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:121)

```

This is the project that reproduces that issue - https://github.com/franz-see/spring-with-mn-data/tree/bug/failing-spring-data-transaction

**Comment by cemo** [comment]
I had a different variant of use case.
If you are also not using Hibernate , just remove hibernate dependency since it is transitively added.

```
  <dependency>
      <groupId>io.micronaut.data</groupId>
      <artifactId>micronaut-data-spring</artifactId>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>io.micronaut.sql</groupId>
          <artifactId>micronaut-hibernate-jpa-spring</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

But I think here is a configuration bug of Micronaut. I did not deep dive but

**Comment by cemo** [comment]
@graemerocher This is the same error I came across when I was trying to configure with Spring.
