### ISSUE TITLE
Explicit queries with simple type result failing with exception

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-data#653]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

While trying to find a workaround for #652 I defined a repository method with an explicit native query:
```java
    @Query(nativeQuery = true, 
           value = "SELECT MAX(c.number) FROM children c WHERE c.parentid = :parentId")
    Single<Integer> getMaxNumber(int parentId);
```
Unfortunately this doesn't work either because when the method `getMaxNumber`is invoked a `org.hibernate.MappingException` with the message _Unknown entity: java.lang.Integer exception_ occurs:
```java
javax.persistence.PersistenceException: org.hibernate.MappingException: Unknown entity: java.lang.Integer
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1542)
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1575)
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResultOptional(AbstractProducedQuery.java:1526)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$2(HibernateJpaOperations.java:167)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:133)
        at io.micronaut.data.runtime.operations.ExecutorAsyncOperations.lambda$findOptional$4(ExecutorAsyncOperations.java:113)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
        at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.MappingException: Unknown entity: java.lang.Integer
        at org.hibernate.metamodel.internal.MetamodelImpl.entityPersister(MetamodelImpl.java:704)
        at org.hibernate.engine.spi.SessionFactoryImplementor.getEntityPersister(SessionFactoryImplementor.java:351)
        at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.getSQLLoadable(SQLQueryReturnProcessor.java:445)
        at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processRootReturn(SQLQueryReturnProcessor.java:498)
        at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processReturn(SQLQueryReturnProcessor.java:465)
        at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.process(SQLQueryReturnProcessor.java:180)
        at org.hibernate.loader.custom.sql.SQLCustomQuery.<init>(SQLCustomQuery.java:74)
        at org.hibernate.engine.query.internal.NativeQueryInterpreterStandardImpl.createQueryPlan(NativeQueryInterpreterStandardImpl.java:44)
        at org.hibernate.engine.query.spi.QueryPlanCache.getNativeSQLQueryPlan(QueryPlanCache.java:233)
        at org.hibernate.internal.AbstractSharedSessionContract.getNativeQueryPlan(AbstractSharedSessionContract.java:608)
        at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1163)
        at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
```
### Workaround

Use an EntityManager instance to create and execute the query.

### Steps to Reproduce

1. Define an explicit query with a simple/primitive type result, e.g. Integer
2. Execute query => org.hibernate.MappingException: Unknown entity: java.lang.Integer

### Expected Behaviour

Query should execute and return an integer value

### Actual Behaviour

org.hibernate.MappingException: Unknown entity: java.lang.Integer

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0 (data 1.1.1)
- **JDK Version:** 8

**Comment by flobaader** [comment]
Any updates on that issue? @dorian-yeager
