### ISSUE TITLE
Postgres @ManyToOne Update of Null UUID Fails with SQL Error - UUID Treated as BigInt

### ISSUE THREAD

**Issue by mphouston** [micronaut-projects/micronaut-data#671]
Trying to update a record with a null foreign reference to another record fails under Postgres with a UUID id column:

```
io.micronaut.data.exceptions.DataAccessException: Error executing SQL UPDATE: ERROR: column "table_bid" is of type uuid but expression is of type bigint
``` 

This foreign reference is a field defined as:

```
  @ManyToOne(targetEntity=TableB.class)
  @MappedProperty(type = DataType.UUID)
  TableB tableB;
```

When the Micronaut-Data core method _JdbcQueryStatement.setDynamic()_ detects the UUID @MappedProperty, it tries to use the SQL for a bigint.

I temporarily 'fixed' this by overriding the method with this Groovy logic:

```
         QueryStatement<PreparedStatement, Integer> setDynamic(@NonNull PreparedStatement statement, @NonNull Integer index, @NonNull DataType dataType, Object value) {
           if (dataType == DataType.ENTITY) {
             statement.setNull(index, Types.OTHER)
             return this
           }
           return super.setDynamic(statement, index, dataType, value)
         }
```

Oddly, inserting new records seems to set the values correctly.

### Steps to Reproduce

1. Create app for Postgres and Micronaut-JDBC (SQL).
2. Create two Domains/Repositories.  One with a foreign reference to another domain using UUIDs on Postgres.
3. Create a record with a null value in the foreign reference field and save() it.
4. Update the record, still with a null value in the foreign reference field.

### Expected Behaviour

Update works.

### Actual Behaviour

Update fails with the exception:

```
io.micronaut.data.exceptions.DataAccessException: Error executing SQL UPDATE: ERROR: column "table_bid" is of type uuid but expression is of type bigint
  Hint: You will need to rewrite or cast the expression.
  Position: 44
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$updateOne$8(DefaultJdbcRepositoryOperations.java:611)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.updateOne(DefaultJdbcRepositoryOperations.java:456)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.update(DefaultJdbcRepositoryOperations.java:448)
	at io.micronaut.data.runtime.intercept.DefaultUpdateEntityInterceptor.intercept(DefaultUpdateEntityInterceptor.java:43)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:106)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at ref.issue.TableARepository$Intercepted.update(Unknown Source)
	at ref.issue.RefIssueTest.testNullRefIssue(RefIssueTest.java:30)
	. . .
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0
- **Micronaut-Data Version:** 1.1.3
- **JDK Version:** Open JDK 14.

### Example Application

https://github.com/mphouston/mn-issues/tree/master/ref-issue

Run: _./gradlew test_

**Comment by mphouston** [comment]
BTW, Since I have a work-around, this is not urgent.
