### ISSUE TITLE
Hibernate exception when using native query to return a count

### ISSUE THREAD

**Issue by tcomerps** [micronaut-projects/micronaut-data#747]
There seems to be an issue with native queries in repositories that return counts. The exception that is returned is:

```
org.hibernate.MappingException: Unknown entity: java.lang.Long
	at org.hibernate.metamodel.internal.MetamodelImpl.entityPersister(MetamodelImpl.java:704) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.engine.spi.SessionFactoryImplementor.getEntityPersister(SessionFactoryImplementor.java:351) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.getSQLLoadable(SQLQueryReturnProcessor.java:445) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processRootReturn(SQLQueryReturnProcessor.java:498) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.processReturn(SQLQueryReturnProcessor.java:465) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.loader.custom.sql.SQLQueryReturnProcessor.process(SQLQueryReturnProcessor.java:180) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.loader.custom.sql.SQLCustomQuery.<init>(SQLCustomQuery.java:74) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.engine.query.internal.NativeQueryInterpreterStandardImpl.createQueryPlan(NativeQueryInterpreterStandardImpl.java:44) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.engine.query.spi.QueryPlanCache.getNativeSQLQueryPlan(QueryPlanCache.java:233) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.getNativeQueryPlan(AbstractSharedSessionContract.java:608) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1163) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533) ~[hibernate-core-5.4.20.Final.jar:5.4.20.Final]
```

### Steps to Reproduce

This fails:
```kotlin
@Repository
interface MyModelRepository : CrudRepository<MyModel, Int> {

    @Query(value = "select count(*) from my_model", nativeQuery = true)
    fun countBy(): Long
}
```

This works:
```kotlin
@Repository
interface MyModelRepository : CrudRepository<MyModel, Int> {

    @Query(value = "select count(*) from MyModel")
    fun countBy(): Long
}
```

### Environment Information

- **Operating System**: macOS 10.15.6
- **Micronaut Version:** 2.0.3
- **Micronaut Data Version:** 1.1.3
- **JDK Version:** OpenJDK 11

**Comment by graemerocher** [comment]
Duplicates #653
