### ISSUE TITLE
parallel test execution throws IllegalStateException

### ISSUE THREAD

**Issue by vmj** [micronaut-projects/micronaut-data#792]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate an application: `mn create-app -l=java --jdk=11 -b=gradle -t=spock -f=data-jdbc,jdbc-tomcat,h2 demo`
2. Change into `demo`: `cd demo`
3. Overwrite the spock version in `build.gradle`: `testImplementation("org.spockframework:spock-core:2.0-M4-groovy-3.0")`
4. Make test resources directory: `mkdir -p src/test/resources`
5. Enable parallel test execution by adding file `src/test/resources/SpockConfig.groovy`:
    ```groovy
    runner {
        parallel {
            enabled true
        }
    }
    ```
6. Make the example test run a few times, e.g. by adding a `where` block:
    ```groovy
    @MicronautTest
    class DemoSpec extends Specification {

        @Inject
        EmbeddedApplication<?> application

        void 'test it works'() {
            expect:
            application.running

            where:
            id << (0..100).asList()
        }
    }
    ```
7. Run the tests: `./gradlew --no-build-cache clean test`

### Expected Behaviour

Tests should pass. I.e. `BUILD SUCCESSFUL`.

### Actual Behaviour

Most of the time some of the tests fail with an error:

```
java.lang.IllegalStateException: No value for key [org.apache.tomcat.jdbc.pool.DataSource@2bac95a9{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.h2.Driver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=false; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE; username=sa; validationQuery=SELECT 1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=3000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; useStatementFacade=true; }] bound to thread [ForkJoinPool-1-worker-5]
	at io.micronaut.transaction.support.TransactionSynchronizationManager.unbindResource(TransactionSynchronizationManager.java:234)
	at io.micronaut.transaction.jdbc.DataSourceTransactionManager.doCleanupAfterCompletion(DataSourceTransactionManager.java:289)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.cleanupAfterCompletion(AbstractSynchronousTransactionManager.java:1074)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.processRollback(AbstractSynchronousTransactionManager.java:949)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.rollback(AbstractSynchronousTransactionManager.java:889)
	at io.micronaut.transaction.test.DefaultTestTransactionInterceptor.rollback(DefaultTestTransactionInterceptor.java:64)
	at io.micronaut.test.transaction.TestTransactionInterceptorListener.afterTestExecution(TestTransactionInterceptorListener.java:55)
	at io.micronaut.test.extensions.AbstractMicronautExtension.fireListeners(AbstractMicronautExtension.java:140)
	at io.micronaut.test.extensions.AbstractMicronautExtension.afterTestExecution(AbstractMicronautExtension.java:91)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$null$1(MicronautSpockExtension.java:81)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Some of the tests fail with https://github.com/micronaut-projects/micronaut-test/issues/322

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 2.1.2
- **JDK Version:**
    ```
    openjdk version "11.0.9" 2020-10-20 LTS
    OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
    OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
    ```

**Comment by graemerocher** [comment]
I don't see us fixing this, the tests are not designed to be run in parallel and you can use forkEvery in the build config to achieve the same thing
