### ISSUE TITLE
Issues when using IN() inside WITH and passing multiple values

### ISSUE THREAD

**Issue by JTier** [micronaut-projects/micronaut-data#835]
I am experiencing issues when using `IN ()` clauses inside `WITH` statements with PostgreSQL instance. The query works fine with only one value inside the collection but once multiple values are provided inside the collection it fails with column mismatch error.

### Expected Behaviour

Should split our input values and replace them in the query and then return our expected results

### Actual Behaviour

The query fails during preparation with the following exception;

```
Unable to set PreparedStatement value: The column index is out of range: 4, number of columns: 3.
io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: The column index is out of range: 4, number of columns: 3.
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.newDataAccessException(JdbcQueryStatement.java:274)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setLong(JdbcQueryStatement.java:140)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setLong(JdbcQueryStatement.java:33)
	at io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:142)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:93)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:33)
	at io.micronaut.data.jdbc.operations.AbstractSqlRepositoryOperations.setStatementParameter(AbstractSqlRepositoryOperations.java:402)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.prepareStatement(DefaultJdbcRepositoryOperations.java:975)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:303)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findStream$4(DefaultJdbcRepositoryOperations.java:294)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findStream(DefaultJdbcRepositoryOperations.java:292)
	at io.micronaut.data.runtime.intercept.DefaultFindStreamInterceptor.intercept(DefaultFindStreamInterceptor.java:49)
	at io.micronaut.data.runtime.intercept.DefaultFindStreamInterceptor.intercept(DefaultFindStreamInterceptor.java:34)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:82)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:82)
```

### Environment Information

- **Operating System**: MacOS Mojave
- **Micronaut Version:** 2.1.1
- **JDK Version:** 14.0.1

### Example Application

So taking some basic examples, we have the following query which works as expected with multiple entries inside the collection param, I believe this relates to the fixes from #496.

```
@Query(value = "SELECT id FROM public.role WHERE UPPER(name) IN ( :permittedRoles ) ")
protected abstract Stream<T> query(Set<String> permittedRoles);
```

However taking that same query and placing it inside a `WITH` clause we begin to experience some issues;

```
@Query(value = "WITH test_query AS ( SELECT id FROM public.role WHERE UPPER(name) IN ( :permittedRoles ) ) "
  + "SELECT re.* FROM test_query re")
protected abstract Stream<T> query(Set<String> permittedRoles);
```

With this query if we pass a single String into the permitted roles collection the query will work fine and return our expected results, however once we pass in more than one entry we receive the column index exception.

**Comment by dstepanov** [comment]
This was fixed by https://github.com/micronaut-projects/micronaut-data/pull/851
