### ISSUE TITLE
Dynamic Sorting is not working as expected

### ISSUE THREAD

**Issue by vishnuvijaypr** [micronaut-projects/micronaut-data#842]
As discussed with @graemerocher , suggested to do this changes  ** @Join(value=“user”, alias=“u”) and then sort order of u.firstName** , but problem is still there, so please suggest me with the changes that need to be done

**Steps to Reproduce**
1)Install MYSQL
create a user root with password as root

2)Create play schema in mysql
Enter mysql -u root -p
Enter the password
In the mysql console create schema using this comand CREATE SCHEMA play;

3)Run the application 
4)hit http://localhost:8080/v1/user from browser or postman (get call)

**Expected Behaviour**
Need to have sort on users firstName

**Actual Behaviour**
But an error occurs {"message":"Internal Server Error: Cannot sort on non-existent property path: u.firstName"}
With detail stack trace
"C:\Program Files\Java\jdk-11.0.6\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4\lib\idea_rt.jar=60758:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\vishnu\Desktop\dev\micronautExplore\target\classes;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-inject\2.2.0\micronaut-inject-2.2.0.jar;C:\Users\vishnu\.m2\repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;C:\Users\vishnu\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-core\2.2.0\micronaut-core-2.2.0.jar;C:\Users\vishnu\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\vishnu\.m2\repository\com\github\spotbugs\spotbugs-annotations\4.0.3\spotbugs-annotations-4.0.3.jar;C:\Users\vishnu\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\vishnu\.m2\repository\org\yaml\snakeyaml\1.26\snakeyaml-1.26.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-validation\2.2.0\micronaut-validation-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http\2.2.0\micronaut-http-2.2.0.jar;C:\Users\vishnu\.m2\repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http-client\2.2.0\micronaut-http-client-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\reactivex\rxjava2\rxjava\2.2.10\rxjava-2.2.10.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http-client-core\2.2.0\micronaut-http-client-core-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-websocket\2.2.0\micronaut-websocket-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http-netty\2.2.0\micronaut-http-netty-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-buffer-netty\2.2.0\micronaut-buffer-netty-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-handler\4.1.54.Final\netty-handler-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-resolver\4.1.54.Final\netty-resolver-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-codec-http2\4.1.54.Final\netty-codec-http2-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-handler-proxy\4.1.54.Final\netty-handler-proxy-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-common\4.1.54.Final\netty-common-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-buffer\4.1.54.Final\netty-buffer-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-transport\4.1.54.Final\netty-transport-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-codec\4.1.54.Final\netty-codec-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-codec-socks\4.1.54.Final\netty-codec-socks-4.1.54.Final.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-runtime\2.2.0\micronaut-runtime-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-aop\2.2.0\micronaut-aop-2.2.0.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.11.2\jackson-databind-2.11.2.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.11.2\jackson-annotations-2.11.2.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.11.2\jackson-core-2.11.2.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.11.2\jackson-datatype-jdk8-2.11.2.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.11.2\jackson-datatype-jsr310-2.11.2.jar;C:\Users\vishnu\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\vishnu\.m2\repository\io\micronaut\sql\micronaut-jdbc-hikari\3.3.1\micronaut-jdbc-hikari-3.3.1.jar;C:\Users\vishnu\.m2\repository\io\micronaut\sql\micronaut-jdbc\3.3.1\micronaut-jdbc-3.3.1.jar;C:\Users\vishnu\.m2\repository\com\zaxxer\HikariCP\3.4.5\HikariCP-3.4.5.jar;C:\Users\vishnu\.m2\repository\io\micronaut\data\micronaut-data-hibernate-jpa\2.2.0\micronaut-data-hibernate-jpa-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\data\micronaut-data-runtime\2.2.0\micronaut-data-runtime-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\data\micronaut-data-model\2.2.0\micronaut-data-model-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\data\micronaut-data-tx\2.2.0\micronaut-data-tx-2.2.0.jar;C:\Users\vishnu\.m2\repository\jakarta\persistence\jakarta.persistence-api\2.2.3\jakarta.persistence-api-2.2.3.jar;C:\Users\vishnu\.m2\repository\org\hibernate\hibernate-core\5.4.23.Final\hibernate-core-5.4.23.Final.jar;C:\Users\vishnu\.m2\repository\org\jboss\logging\jboss-logging\3.4.1.Final\jboss-logging-3.4.1.Final.jar;C:\Users\vishnu\.m2\repository\net\bytebuddy\byte-buddy\1.10.17\byte-buddy-1.10.17.jar;C:\Users\vishnu\.m2\repository\antlr\antlr\2.7.7\antlr-2.7.7.jar;C:\Users\vishnu\.m2\repository\org\jboss\jandex\2.1.3.Final\jandex-2.1.3.Final.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;C:\Users\vishnu\.m2\repository\javax\activation\javax.activation-api\1.2.0\javax.activation-api-1.2.0.jar;C:\Users\vishnu\.m2\repository\org\dom4j\dom4j\2.1.3\dom4j-2.1.3.jar;C:\Users\vishnu\.m2\repository\org\hibernate\common\hibernate-commons-annotations\5.1.2.Final\hibernate-commons-annotations-5.1.2.Final.jar;C:\Users\vishnu\.m2\repository\org\glassfish\jaxb\jaxb-runtime\2.3.1\jaxb-runtime-2.3.1.jar;C:\Users\vishnu\.m2\repository\org\glassfish\jaxb\txw2\2.3.1\txw2-2.3.1.jar;C:\Users\vishnu\.m2\repository\com\sun\istack\istack-commons-runtime\3.0.7\istack-commons-runtime-3.0.7.jar;C:\Users\vishnu\.m2\repository\org\jvnet\staxex\stax-ex\1.8\stax-ex-1.8.jar;C:\Users\vishnu\.m2\repository\com\sun\xml\fastinfoset\FastInfoset\1.2.15\FastInfoset-1.2.15.jar;C:\Users\vishnu\.m2\repository\io\micronaut\data\micronaut-data-tx-hibernate\2.2.0\micronaut-data-tx-hibernate-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\sql\micronaut-hibernate-jpa\3.3.1\micronaut-hibernate-jpa-3.3.1.jar;C:\Users\vishnu\.m2\repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta.transaction-api-1.3.3.jar;C:\Users\vishnu\.m2\repository\javax\xml\bind\jaxb-api\2.3.1\jaxb-api-2.3.1.jar;C:\Users\vishnu\.m2\repository\io\micronaut\aws\micronaut-function-aws-api-proxy\2.2.3\micronaut-function-aws-api-proxy-2.2.3.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http-server\2.2.0\micronaut-http-server-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-router\2.2.0\micronaut-router-2.2.0.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\serverless\aws-serverless-java-container-core\1.5.2\aws-serverless-java-container-core-1.5.2.jar;C:\Users\vishnu\.m2\repository\javax\ws\rs\javax.ws.rs-api\2.1\javax.ws.rs-api-2.1.jar;C:\Users\vishnu\.m2\repository\commons-fileupload\commons-fileupload\1.4\commons-fileupload-1.4.jar;C:\Users\vishnu\.m2\repository\commons-io\commons-io\2.2\commons-io-2.2.jar;C:\Users\vishnu\.m2\repository\org\apache\httpcomponents\httpmime\4.5.6\httpmime-4.5.6.jar;C:\Users\vishnu\.m2\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar;C:\Users\vishnu\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.30\jcl-over-slf4j-1.7.30.jar;C:\Users\vishnu\.m2\repository\io\micronaut\aws\micronaut-function-aws\2.2.3\micronaut-function-aws-2.2.3.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-function\2.2.0\micronaut-function-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\micronaut\aws\micronaut-aws-common\2.2.3\micronaut-aws-common-2.2.3.jar;C:\Users\vishnu\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\vishnu\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\vishnu\.m2\repository\mysql\mysql-connector-java\8.0.22\mysql-connector-java-8.0.22.jar;C:\Users\vishnu\.m2\repository\com\google\protobuf\protobuf-java\3.14.0\protobuf-java-3.14.0.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\aws-lambda-java-core\1.1.0\aws-lambda-java-core-1.1.0.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\aws-lambda-java-events\2.2.7\aws-lambda-java-events-2.2.7.jar;C:\Users\vishnu\.m2\repository\joda-time\joda-time\2.6\joda-time-2.6.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\aws-java-sdk-s3\1.11.727\aws-java-sdk-s3-1.11.727.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\aws-java-sdk-kms\1.11.727\aws-java-sdk-kms-1.11.727.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\aws-java-sdk-core\1.11.727\aws-java-sdk-core-1.11.727.jar;C:\Users\vishnu\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\vishnu\.m2\repository\org\apache\httpcomponents\httpclient\4.5.9\httpclient-4.5.9.jar;C:\Users\vishnu\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\vishnu\.m2\repository\software\amazon\ion\ion-java\1.0.2\ion-java-1.0.2.jar;C:\Users\vishnu\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.11.2\jackson-dataformat-cbor-2.11.2.jar;C:\Users\vishnu\.m2\repository\com\amazonaws\jmespath-java\1.11.727\jmespath-java-1.11.727.jar;C:\Users\vishnu\.m2\repository\io\micronaut\micronaut-http-server-netty\2.2.0\micronaut-http-server-netty-2.2.0.jar;C:\Users\vishnu\.m2\repository\io\netty\netty-codec-http\4.1.54.Final\netty-codec-http-4.1.54.Final.jar com.digitap.Application
2020-12-02 19:52:45     INFO  c.z.h.HikariDataSource - HikariPool-1 - Starting...
2020-12-02 19:52:45     INFO  c.z.h.HikariDataSource - HikariPool-1 - Start completed.
2020-12-02 19:52:45     INFO  o.h.Version - HHH000412: Hibernate ORM core version 5.4.23.Final
2020-12-02 19:52:45     INFO  o.h.a.c.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2020-12-02 19:52:46     INFO  o.h.d.Dialect - HHH000400: Using dialect: org.hibernate.dialect.MySQL57Dialect
2020-12-02 19:52:47     INFO  i.m.r.Micronaut - Startup completed in 4209ms. Server Running: http://localhost:8080
2020-12-02 19:52:59     ERROR i.m.h.s.n.RoutingInBoundHandler - Unexpected error occurred: Cannot sort on non-existent property path: u.firstName
java.lang.IllegalArgumentException: Cannot sort on non-existent property path: u.firstName
	at io.micronaut.data.model.query.builder.AbstractSqlLikeQueryBuilder.lambda$buildOrderBy$37(AbstractSqlLikeQueryBuilder.java:1525)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.data.model.query.builder.AbstractSqlLikeQueryBuilder.buildOrderBy(AbstractSqlLikeQueryBuilder.java:1525)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findAll$6(HibernateJpaOperations.java:271)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findAll(HibernateJpaOperations.java:264)
	at io.micronaut.data.runtime.intercept.DefaultFindPageInterceptor.intercept(DefaultFindPageInterceptor.java:56)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:82)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:82)
	at com.digitap.repository.PdTransactionIdMappingRepository$Intercepted.findByAgentIdAndAgentFirstNameContainsAndEnterpriseIdAndIsScheduled(Unknown Source)
	at com.digitap.controller.UserController.testJoin(UserController.java:38)
	at com.digitap.controller.$UserControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:255)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1365)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$6(RoutingInBoundHandler.java:1070)
	at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:80)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:697)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:553)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:148)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

Process finished with exit code -1

**Environment Information**
Operating System: windows 10
Micronaut Version: Micronaut Version: 2.1.2
JDK Version: 11.0.8

**Example application**
https://github.com/IEEEKSIT/micronautPlay

**Comment by radovanradic** [comment]
I know this is an old issue, but just looked at it today.
Adding this `@Join("user")` to the repository method which would look like: 
```
@Join("user")
Page<PdTransactionIdMapping> findByAgentIdAndAgentFirstNameContainsAndEnterpriseIdAndIsScheduled
            (int agentId, String name, int enterpriseId, PdTransactionIdMapping.IsScheduled isScheduled, Pageable pageable);
```
and creating sort like this in the controller:
```
@Get(value = "/user", produces = MediaType.APPLICATION_JSON)
public Page<PdTransactionIdMapping> testJoin() {
        Sort.Order order = new Sort.Order("user.firstName", Sort.Order.Direction.DESC, false);
        Pageable pageable = Pageable.from(0, 25, Sort.of(order));

        Page<PdTransactionIdMapping> pdTransactionIdMappings = pdTransactionIdMappingRepository
                .findByAgentIdAndAgentFirstNameContainsAndEnterpriseIdAndIsScheduled
                        (25399, "vishnu", 2, PdTransactionIdMapping.IsScheduled.FALSE, pageable);

        return pdTransactionIdMappings;
}
```
generates and executes this query:
```
SELECT pdTransactionIdMapping_ FROM com.play.dao.PdTransactionIdMapping AS pdTransactionIdMapping_ 
JOIN FETCH pdTransactionIdMapping_.user pdTransactionIdMapping_user_ 
WHERE (pdTransactionIdMapping_.agent.id = :p1 
AND pdTransactionIdMapping_.agent.firstName LIKE CONCAT('%',:p2,'%') 
AND pdTransactionIdMapping_.enterprise.id = :p3 
AND pdTransactionIdMapping_.isScheduled = :p4) 
ORDER BY pdTransactionIdMapping_user_.firstName DESC
```
which should resolve the issue.

Since no code is needed, will close this issue now. Please reopen or submit new issue if you still see issue(s) with this.
