### ISSUE TITLE
native image raised error: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType

### ISSUE THREAD

**Issue by szhaoyu** [micronaut-projects/micronaut-data#873]
### Steps to Reproduce

1. create a micronaut application with micronaut-data-hibernate-jpa(2.2.3)
2. exec native-image 
3. run the output image, and raised the error:
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not create DynamicParameterizedType for type: org.hibernate.type.EnumType
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2665)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2204)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 2.2.3
- **JDK Version:** GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)

Thanks for help !

**Comment by graemerocher** [comment]
I can't reproduce this, maybe if you provide an example

**Comment by Phil-Ba** [comment]
Actually I can reproduce this. The issue seems to pop up when the J8 Date enum _DayOfWeek_ is used as field of an entity.
Quarkus seems to have had the same issue and fixed it: https://github.com/quarkusio/quarkus/issues/7653 
Should I create a new issue, or will this one be reopened?

**Comment by graemerocher** [comment]
Can you provide an example? If so create a new issue with the example linked
