### ISSUE TITLE
No bean of type io.micronaut.data.operations.PrimaryRepositoryOperations exists

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-data#887]
Hi, I've just upgraded my project to 2.3.0 and I am getting the exception mentioned below.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git`
2. checkout branch `update-to-micronaut-2.3.x`
3. start the environment as described in this [doc](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/book-api#start-environment)
4. build and run docker native as described in this [doc](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/book-api/micronaut-book-api#docker-in-native-mode)
5. the exception is thrown when a request is submitted

### Stacktrace

```
ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: No backing RepositoryOperations configured for repository. Check your configuration and try again
io.micronaut.context.exceptions.ConfigurationException: No backing RepositoryOperations configured for repository. Check your configuration and try again
	at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:124)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:78)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at com.mycompany.micronautbookapi.repository.BookRepository$Intercepted.save(Unknown Source)
	at com.mycompany.micronautbookapi.service.BookServiceImpl.saveBook(BookServiceImpl.java:31)
	at com.mycompany.micronautbookapi.rest.BookController.saveBook(BookController.java:39)
	at com.mycompany.micronautbookapi.rest.$BookControllerDefinition$Intercepted.$$access$$saveBook(Unknown Source)
	at com.mycompany.micronautbookapi.rest.$BookControllerDefinition$$exec3.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:87)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at com.mycompany.micronautbookapi.rest.$BookControllerDefinition$Intercepted.saveBook(Unknown Source)
	at com.mycompany.micronautbookapi.rest.$BookControllerDefinition$$exec3.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1391)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:155)
	at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$6(RoutingInBoundHandler.java:1096)
	at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:80)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$2.doOnComplete(RoutingInBoundHandler.java:1022)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor$1.doOnComplete(JsonContentProcessor.java:140)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)
	at io.micronaut.jackson.parser.JacksonProcessor.doOnComplete(JacksonProcessor.java:137)
	at io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:70)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor.doOnComplete(JsonContentProcessor.java:165)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:416)
	at io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:403)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:429)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:294)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:257)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:163)
	at io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:248)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:547)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.operations.PrimaryRepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2322)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:733)
	at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:121)
	... 94 common frames omitted
```

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.3.0
- **JDK Version:** 11

### Example Application

- https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/book-api/micronaut-book-api

**Comment by graemerocher** [comment]
I applied the following patch to your example:

```diff
From 3d63f7c0d6d68b3d9700f369f6a4dca50857e625 Mon Sep 17 00:00:00 2001
From: graemerocher <graeme.rocher@gmail.com>
Date: Mon, 25 Jan 2021 12:03:46 +0100
Subject: [PATCH] Update example to 2.3.0

---
 book-api/micronaut-book-api/pom.xml | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/book-api/micronaut-book-api/pom.xml b/book-api/micronaut-book-api/pom.xml
index c50b811..0ad7349 100755
--- a/book-api/micronaut-book-api/pom.xml
+++ b/book-api/micronaut-book-api/pom.xml
@@ -10,15 +10,15 @@
     <parent>
         <groupId>io.micronaut</groupId>
         <artifactId>micronaut-parent</artifactId>
-        <version>2.2.2</version>
+        <version>2.3.0</version>
     </parent>

     <properties>
         <packaging>jar</packaging>
         <jdk.version>11</jdk.version>
         <release.version>11</release.version>
-        <micronaut.version>2.2.2</micronaut.version>
-        <micronaut.data.version>2.2.1</micronaut.data.version>
+        <micronaut.version>2.3.0</micronaut.version>
+        <micronaut.data.version>2.2.4</micronaut.data.version>
         <exec.mainClass>com.mycompany.micronautbookapi.Application</exec.mainClass>
         <micronaut.runtime>netty</micronaut.runtime>
         <org.mapstruct.version>1.4.1.Final</org.mapstruct.version>
--
2.24.3 (Apple Git-128)
```

Then ran:

```
./mvnw package -Dpackaging=native-image
./target/micronaut-book-api
```

And it seemed to work fine for me with the endpoint http://localhost:8080/api/books returning an empty list

Maybe it is something wrong with your custom build scripts

**Comment by ivangfr** [comment]
Hi @graemerocher ,

I think I've found the problem... When I updated from `2.2.2` to `2.3.0`, I've based on the new generated code provided by https://micronaut.io/launch/ as I always do.

I noticed that
```
        <dependency>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>svm</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <scope>provided</scope>
        </dependency>
```
and
```
    <path>
        <groupId>io.micronaut</groupId>
        <artifactId>micronaut-graal</artifactId>
        <version>${micronaut.version}</version>
    </path>
```
were removed.

That's why I removed them from my code as you can see in [`update-micronaut-to-2.3.0` comparison with master](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/compare/update-to-micronaut-2.3.x)

Putting them back, the app work in native mode and I don't have the exception described above.

Btw, I removed the graal dependencies and path mentioned above from all apps in the project. Should I put them back?

Thanks!

**Comment by graemerocher** [comment]
`micronaut-graal` is needed

**Comment by ivangfr** [comment]
Maybe `Micronout Launch` needs some adjustments when `Maven` build tool is selected. For instance, `GraalVM` dependencies are not included; When added `Jib`, its plugin is not included as well.

**Comment by alvarosanchez** [comment]
Those dependencies are added from the parent POM via a profile that gets activated if you have a `${env.JAVA_HOME}/bin/native-image` file. See https://github.com/micronaut-projects/micronaut-core/issues/4578 for more details.

@ivangfr were you trying with a GraalVM JDK? Can you check the output of `mvn help:active-profiles`?

Regarding Jib, it's also defined in the parent POM.

**Comment by ivangfr** [comment]
Hi @alvarosanchez 

Here is the output of `mvn help:active-profiles`
```
➜  micronaut-book-api git:(update-to-micronaut-2.3.x) ./mvnw help:active-profiles
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------< com.mycompany.micronautbookapi:micronaut-book-api >----------
[INFO] Building micronaut-book-api 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-help-plugin:3.2.0:active-profiles (default-cli) @ micronaut-book-api ---
[INFO] 
Active Profiles for Project 'com.mycompany.micronautbookapi:micronaut-book-api:jar:1.0.0':

The following profiles are active:

 - jdk-9-or-later (source: io.micronaut:micronaut-parent:2.3.0)



[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.267 s
[INFO] Finished at: 2021-01-26T09:19:41-03:00
[INFO] ------------------------------------------------------------------------
```

I don't have `GraalVM native-image` installed in my host machine. I prefer to build the docker native image inside a container.

**Comment by alvarosanchez** [comment]
Still, this expects that you are running locally with GraalVM JDK, since the classes are compiled in your host machine, then copied to the container to run `native-image` there.

Perhaps implementing https://github.com/micronaut-projects/micronaut-maven-plugin/issues/56 would help

**Comment by alvarosanchez** [comment]
Note that you can workaround it by passing `-Pgraalvm` to your Maven command line

**Comment by alvarosanchez** [comment]
First, if you have a `Dockerfile` in the project root, the Maven plugin will just pick it up when building, sou you can just `mvn package` and you will get your project compiled and your `Dockerfile` built in one go.

Secondly, you don't need your own `Dockerfile` to change the `FROM`. Instead, you can simply run:

```
$ ./mvnw -Pgraalvm package -Dpackaging=docker-native -Djib.from.image=frolvlad/alpine-glibc:alpine-3.12
```

**Comment by ivangfr** [comment]
That's nice @alvarosanchez Thanks for the tips. I will apply them and try the `-Pgraalvm`. I let you know.

**Comment by ivangfr** [comment]
But, the **Micronaut** `Dockerfile` I am used to see has two `FROM`s
```
FROM ghcr.io/graalvm/graalvm-ce:java11-21.0.0 as graalvm
...
FROM frolvlad/alpine-glibc
...
```
By setting `-Djib.from.image=frolvlad/alpine-glibc:alpine-3.12`, it changes the 1st `FROM` and not the 2nd one.

So, the command
```
./mvnw -Pgraalvm package -Dpackaging=docker-native -Djib.from.image=frolvlad/alpine-glibc:alpine-3.12
```
doesn't work.

On the other hand, the following command works and it's handy in case I want to try a different `GraalVM` version
```
./mvnw -Pgraalvm package -Dpackaging=docker-native -Djib.from.image=ghcr.io/graalvm/graalvm-ce:java11-21.0.0
```

**Comment by alvarosanchez** [comment]
Doh, you are right, currently you can't change the second `FROM`. I think that should be possible, will create an issue.

**Comment by alvarosanchez** [comment]
FYI: https://github.com/micronaut-projects/micronaut-maven-plugin/issues/96

**Comment by ivangfr** [comment]
Before closing this issue, I'd like to comment that this issue (`No bean of type io.micronaut.data.operations.PrimaryRepositoryOperations exists`) was happening because I removed `org.graalvm.nativeimage:svm` and `org.graalvm.sdk:graal-sdk` dependencies.

When using https://micronaut.io/launch/, by adding `graalvm` as a feature, the dependencies mentioned before are not added in `pom.xml`. It made me remove them.

Thanks!
