### ISSUE TITLE
Data annotation process not working with jax-rs processor

### ISSUE THREAD

**Issue by dalbrekt** [micronaut-projects/micronaut-data#899]
With micronaut-jaxrs-processor and micronaut-data-processor enabled application fail to start.

Not sure which processor is the cause of failure but it's Micronaut data throwing an exception.

Removing micronaut-jaxrs-processor and using micronaut rest annotations is working as expected.

### Steps to Reproduce

1. Checkout https://github.com/dalbrekt/micronaut-data-jax-rs 
2. run `mvn clean mn:run` from  project root

### Expected Behaviour

Application should start and http://localhost:8080/instances should return 200 and 3 items.

### Actual Behaviour

Throws exception when starting:
```
java.lang.IllegalStateException: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:97)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at com.seal.insight.router.repo.RoutesRepository$Intercepted.save(Unknown Source)
        at com.seal.insight.router.Application.init(Application.java:25)
        at com.seal.insight.router.$ApplicationDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3295)
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at com.seal.insight.router.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1307)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1292)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:248)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at com.seal.insight.router.Application.main(Application.java:19)
```
### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 2.3.1
- **JDK Version:** 11.0.9.hs-adpt

### Example Application

https://github.com/dalbrekt/micronaut-data-jax-rs

More or less a copy of https://github.com/micronaut-projects/micronaut-jaxrs/tree/master/examples/example-jdbc but of the latest Micronaut version and generated with the launcher. data-jdbc and jax-rs features selected.

**Comment by dstepanov** [comment]
`<micronaut.jaxrs.version>2.0.1</micronaut.jaxrs.version>`
Solves the problem.
