### ISSUE TITLE
Micronaut Data JPA repository throws TypedQuery related IllegalArgumentException in native image

### ISSUE THREAD

**Issue by alexey-lapin** [micronaut-projects/micronaut-data#927]
Hi!
I am trying to introduce Graal support to my Micronaut project but I am getting unexpected behavior with JPA.
I extracted essential code to a separate project.
This project uses micronaut-application-plugin, micronaut-data-jpa, h2.
As part of the ports and adapters approach, there is a wrapper around micronaut data repository. It is `JpaUserRepositoryAdapter` class.

If I run the app as a jar, everything is ok.
If I run a native image, an exception occurs, when the repository wrapper is used.

### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce
1. `git clone https://github.com/alexey-lapin/pg-micronaut-graal.git`
2. build native image `./gradlew nativeImage`
3. run app `build/native-image/application`

### Stacktrace
java.lang.IllegalArgumentException: Type specified for TypedQuery [pg.micronaut.graal.domain.model.User] is incompatible with query return type [class java.util.UUID]
        at org.hibernate.internal.AbstractSharedSessionContract.resultClassChecking(AbstractSharedSessionContract.java:863)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:817)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:113)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findOne$2(HibernateJpaOperations.java:170)
        at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findOne(HibernateJpaOperations.java:136)
        at io.micronaut.data.hibernate.operations.HibernateJpaOperations.exists(HibernateJpaOperations.java:245)
        at io.micronaut.data.runtime.intercept.DefaultExistsByInterceptor.intercept(DefaultExistsByInterceptor.java:48)
        at io.micronaut.data.runtime.intercept.DefaultExistsByInterceptor.intercept(DefaultExistsByInterceptor.java:33)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:80)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at pg.micronaut.graal.domain.repository.DataUserRepository$Intercepted.existsById(Unknown Source)
        at pg.micronaut.graal.domain.repository.JpaUserRepositoryAdapter.save(JpaUserRepositoryAdapter.java:36)
        at pg.micronaut.graal.Application.init(Application.java:32)
        at pg.micronaut.graal.$ApplicationDefinition$$exec1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:3321)
        at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
        at pg.micronaut.graal.Application$ApplicationEventListener$init1$Intercepted.onApplicationEvent(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.notifyEventListeners(DefaultBeanContext.java:1307)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1292)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:248)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at pg.micronaut.graal.Application.main(Application.java:25)

### Environment Information
- **Operating System**: Linux
- **Micronaut Version:** 2.3.3
- **JDK Version:** GraalVM CE 21.0.0.2

### Example Application
https://github.com/alexey-lapin/pg-micronaut-graal

**Comment by alexey-lapin** [comment]
Some updates

**Short note**:
add `java.util.UUID` to graal's `reflect-config.json` like so:
```java
@Introspected(classes = UUID.class)
public class GraalConfig {
}
```
or using `@TypeHint`

After that repository works fine, no `IllegalArgumentException` is thrown.

**Long note**:
During the debug process, I added some logging and found that **io.micronaut.data.hibernate.operations.HibernateJpaOperations#findOne** method has preparedQuery.getResultType().getName() equals to *pg.micronaut.graal.domain.model.User*, which is incorrect (should be *java.util.UUID*)

Then I found that in **io.micronaut.data.runtime.intercept.DefaultExistsByInterceptor#intercept** method context.classValue(DataMethod.class, DataMethod.META_MEMBER_ID_TYPE) returns **null** and getRequiredRootEntity(context) is *pg.micronaut.graal.domain.model.User*

So, context.classValue(DataMethod.class, DataMethod.META_MEMBER_ID_TYPE) returns null because it seems that application in native image does not have access to *java.util.UUID* class.
Actually, ClassUtils.forName("java.util.UUID", classLoader) in native image returns empty Optional.

Configuring graal reflect access to *java.util.UUID* solves the issue and *ClassUtils* starts returning the actual UUID class.

I didn't find any place in Micronaut where UUID is type-hinted like dates for example:
https://github.com/micronaut-projects/micronaut-core/blob/149bdd46d0b75161d7a20cc9c9a6fb76cfb47b42/context/src/main/java/io/micronaut/runtime/converters/time/TimeConverterRegistrar.java#L50
Should it be type-hinted in Micronaut core?

Also, I found that *ClassUtils* logs frequently on loading load class *java.util.UUID* (maybe every time Micronaut Data code touches it):
```
DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class java.util.UUID
DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class java.util.UUID
INFO  p.m.g.c.ExistsByInterceptorWrapper - >> context idType: java.util.UUID
INFO  p.m.g.c.ExistsByInterceptorWrapper - >> context rootEntityType: java.util.UUID
DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class java.util.UUID
DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class java.util.UUID
INFO  p.m.g.c.HibernateJpaOperationsWrapper - >> findOne() query: SELECT article_.id FROM pg.micronaut.graal.domain.model.Article AS article_ WHERE (article_.id = :p1)
INFO  p.m.g.c.HibernateJpaOperationsWrapper - >> findOne() resultType: java.util.UUID
```
