### ISSUE TITLE
Repository @Join not working with Page

### ISSUE THREAD

**Issue by chridahl** [micronaut-projects/micronaut-data#939]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entity A holding one many-to-one association to entity B.
2. Setup entity B to hold one many-to-one association to entity C.
3. Create a Jdbc CrudRepository for entity A
4. Setup ```findAll``` in repository as such:

```java
    @Join(value = "b", type = Join.Type.LEFT_FETCH)
    @Join(value = "b.c", type = Join.Type.LEFT_FETCH)
    Page<A> findAll(Pageable pageable);
```

### Expected Behaviour

I would expect the same behaviour as when returning List instead of Page; 

```java
    @Join(value = "b", type = Join.Type.LEFT_FETCH)
    @Join(value = "b.c", type = Join.Type.LEFT_FETCH)
    List<A> findAll(Pageable pageable);
```

Which works fine.

### Actual Behaviour

I receive the following error:

```
Caused by: java.lang.IllegalArgumentException: Invalid association path. Element [c] is not an association.
	at io.micronaut.data.model.query.DefaultQuery.join(DefaultQuery.java:139)
	at io.micronaut.data.model.query.QueryModel.join(QueryModel.java:289)
	at io.micronaut.data.processor.visitors.RepositoryTypeElementVisitor.visitMethod(RepositoryTypeElementVisitor.java:354)
	at io.micronaut.annotation.processing.visitor.LoadedVisitor.visit(LoadedVisitor.java:156)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitExecutable(TypeElementVisitorProcessor.java:398)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor$1.accept(TypeElementVisitorProcessor.java:300)
	at io.micronaut.annotation.processing.SuperclassAwareTypeVisitor.visitDeclared(SuperclassAwareTypeVisitor.java:80)
	at io.micronaut.annotation.processing.SuperclassAwareTypeVisitor.visitDeclared(SuperclassAwareTypeVisitor.java:57)
```

### Environment Information

- **Operating System**: Windows 10, version 2004
- **Micronaut Version:** 2.2.3
- **JDK Version:** Oracle 11.0.9

**Comment by graemerocher** [comment]
Can you try Micronaut 2.4.0?

**Comment by chridahl** [comment]
Thanks for the feedback @graemerocher.

I've tried with 2.4.0 and unfortunately the same exception is thrown.

**Comment by dstepanov** [comment]
@chridahl Can you please create a simple project where it's reproduced?
