### ISSUE TITLE
Support SQLite embeded

### ISSUE THREAD

**Issue by devMls** [micronaut-projects/micronaut-data#949]
Hi

I am trying to ship embed database with my micronaut graalvm app.

H2 not support graalvm app, then i am over the idea of ship SQLLite xerial database.

But micronaut not support the sqlLite specific dialect.

Is it planned support it? any other embeded database recommendation?

**Comment by graemerocher** [comment]
H2 is supported in java 8

**Comment by ilopmar** [comment]
And also with Java 11. We have tests for both Micronaut Data JDBC/JPA and H2

**Comment by devMls** [comment]
I am facing this error, in the graalvm compilation, looks like h2 use features like not supported in graalvm:

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readDouble(Bits.java:184)
Call path from entry point to org.h2.util.Bits.readDouble(byte[], int):
        at org.h2.util.Bits.readDouble(Bits.java:184)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readDoubleLE(Bits.java:198)
Call path from entry point to org.h2.util.Bits.readDoubleLE(byte[], int):
        at org.h2.util.Bits.readDoubleLE(Bits.java:198)
       at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readInt(Bits.java:128)
Call path from entry point to org.h2.util.Bits.readInt(byte[], int):
        at org.h2.util.Bits.readInt(Bits.java:128)
        at org.h2.security.AES.encryptBlock(AES.java:143)
        at org.h2.security.AES.encrypt(AES.java:127)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:68)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readIntLE(Bits.java:142)
Call path from entry point to org.h2.util.Bits.readIntLE(byte[], int):
        at org.h2.util.Bits.readIntLE(Bits.java:142)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readInt(EWKBUtils.java:206)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:396)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:129)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:323)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readLong(Bits.java:156)
Call path from entry point to org.h2.util.Bits.readLong(byte[], int):
        at org.h2.util.Bits.readLong(Bits.java:156)
        at org.h2.value.Value.convertToLong(Value.java:958)
        at org.h2.value.Value.convertTo(Value.java:766)
        at org.h2.value.Value.convertTo(Value.java:723)
        at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:565)
        at com.oracle.svm.reflect.PreparedStatement_setObject_5b494a5a8f7fcd76e8cd88a6cab852968d728fd3_3170.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.uuidToBytes(Bits.java:212)
Call path from entry point to org.h2.util.Bits.uuidToBytes(long, long):
        at org.h2.util.Bits.uuidToBytes(Bits.java:211)
        at org.h2.value.ValueUuid.getBytes(ValueUuid.java:201)
        at org.h2.jdbc.JdbcResultSet.getBytes(JdbcResultSet.java:1072)
        at org.h2.store.LobStorageBackend.readBlock(LobStorageBackend.java:232)
        at org.h2.store.LobStorageBackend$LobInputStream.fillBuffer(LobStorageBackend.java:770)
        at org.h2.store.LobStorageBackend$LobInputStream.readFully(LobStorageBackend.java:743)
        at org.h2.store.LobStorageBackend$LobInputStream.read(LobStorageBackend.java:729)
        at com.jogamp.common.util.IOUtil$StreamMonitor.run(IOUtil.java:912)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeDouble(Bits.java:300)
Call path from entry point to org.h2.util.Bits.writeDouble(byte[], int, double):
        at org.h2.util.Bits.writeDouble(Bits.java:300)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.writeDouble(EWKBUtils.java:162)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.addCoordinate(EWKBUtils.java:146)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:718)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:608)
        at org.h2.value.ValueGeometry.get(ValueGeometry.java:117)
        at org.h2.value.Transfer.readValue(Transfer.java:771)
        at org.h2.server.TcpServerThread.setParameters(TcpServerThread.java:257)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:331)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:175)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeInt(Bits.java:240)
Call path from entry point to org.h2.util.Bits.writeInt(byte[], int, int):
        at org.h2.util.Bits.writeInt(Bits.java:240)
        at org.h2.store.Data.writeInt(Data.java:166)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:61)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.writeLong(Bits.java:270)
Call path from entry point to org.h2.util.Bits.writeLong(byte[], int, long):
        at org.h2.util.Bits.writeLong(Bits.java:270)
        at org.h2.security.SecureFileStore.xorInitVector(SecureFileStore.java:102)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:67)
        at org.h2.store.FileStoreOutputStream.w

**Comment by ilopmar** [comment]
Are you using our Gradle plugin? Are you using JPA or JDBC?

There is a known issue that H2 currenlty doesn't work with our Gradle plugin and JDK11. Last time I checked it has been fixed in GraalVM master branch and it will be included in GraalVM 21.1.

The workaround is using JDBC, JPA with Java 8 or not using the Gradle plugin.

**Comment by devMls** [comment]
Hi

I am using graalvm 21.0.0.2, with micronaut data JPA and maven. Maybe I should wait to new graalvm version will be released. If i finish my project before, i try to use java 8, this was a first intent to find possible not compatible libraries between my dependencies. If it gonna be fixed I cand wait

**Comment by ilopmar** [comment]
Right, I'll add to my TODO list trying this again with the GraalVM master branch to make sure it still works.
According to their [release schedule](https://www.graalvm.org/release-notes/version-roadmap/) they will release 21.1 on April 20th 2021.

**Comment by devMls** [comment]
thanks you!

PD: Me produce curiosidad donde trabaja gente en Madrid, que esta activa en un proyecto tan puntero como micronaut

**Comment by ilopmar** [comment]
> PD: Me produce curiosidad donde trabaja gente en Madrid, que esta activa en un proyecto tan puntero como micronaut

Jajaja, desde casa :-P

**Comment by ilopmar** [comment]
@devMls o te refieres a empresa?

**Comment by dstepanov** [comment]
You can probably try dialect ANSI
